equinor/lighthouse-client

src/apps/3DModel/src/3DModel.tsx
src/apps/apps.ts

-   [ x ] I have performed a self-review of my own code.
-   [ x ] My code is easy to read, and comments are added where needed.

activating 3d viewer on 3d route

---

src/apps/Loop/loopApp.tsx
src/components/CompletionView/src/DataViewerApi/DataViewState.ts
src/components/CompletionView/src/Tabs/ListTab.tsx
src/packages/Table/Components/Table.tsx
src/packages/Table/Readme.md
src/packages/Table/Utils/registerReactTableHooks.ts
src/packages/Table/types.ts

Table component supports column ordering and will add the correct column order before table is painted.
Completes: [AB#152112](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/152112)

feat: support column ordering in table component

---

src/packages/Diagrams/src/Visuals/HorizontalBarVisual/Hooks/useHorizontalBarChart.ts
src/packages/Diagrams/src/Visuals/HorizontalBarVisual/HorizontalBarVisual.tsx
src/packages/Diagrams/src/Visuals/HorizontalBarVisual/Readme.md
src/packages/Diagrams/src/Visuals/HorizontalBarVisual/Types/barVisualOptions.ts
src/packages/Diagrams/src/Visuals/HorizontalBarVisual/Utils/createSeriesByKeys.ts
src/packages/Diagrams/src/Visuals/HorizontalBarVisual/index.ts

A version of BarVisual, where the bars are horizontal, instead of vertical.
Difference here is minimnal, and setup is the same as BarVisual
Completes: [AB152126](https://dev.azure.com/Equinor/Johan%20Castberg%20-%20Portal/_workitems/edit/152126/)

Feature/ Horizontal Bar Visual Chart

---

.github/workflows/snyk.yml

Testing snyk workflow

---

packages/httpClient/src/baseClient.ts
src/AppClient.tsx
src/Core/Client/ClientContext/clientContext.tsx
src/Core/Client/Hooks/useApiClient.ts
src/Core/Client/index.ts
src/components/AppIcon/AppIcon.tsx
src/components/Layouts/MainLayout.tsx
src/components/Menu/MainMenu.tsx
src/components/Routes/ComponentWrapper.tsx
src/components/Routes/Routes.tsx
src/components/TopBar/TopBar.tsx
src/modules/powerBI/src/Api/fusionApi.ts
tsconfig.json
vite.config.ts

Completes: [AB#178522](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/178522)

useApiClinet - Hook

---

src/packages/Diagrams/src/Visuals/ConstructionVisual/ConstructionVisual.tsx

Register zoom plugin for Construction visual.

fix: register zoomplugin in construction visual

---

src/packages/Diagrams/src/Utils/cutoffUtils.ts
src/packages/Diagrams/src/Visuals/ConstructionVisual/ConstructionVisual.tsx

Refactor functions and variables with better names.

chore: rename functions and variables in construction visual

---

src/AppClient.tsx
src/Core/ErrorBoundary/Components/ErrorFallback.tsx
src/Core/ErrorBoundary/Components/ErrorFallbackSidesheet.tsx
src/Core/ErrorBoundary/index.tsx
src/Core/GroupView/Components/GroupView/GroupView.tsx
src/Core/PageViewer/index.tsx
src/Core/WorkSpace/src/WorkSpace.tsx
src/components/Loading/LoadingPage.tsx
src/components/Routes/ComponentWrapper.tsx
src/packages/Sidesheet/Components/PopoutSidesheet.tsx
tsconfig.json
vite.config.ts

Error boundary on client, for each route and for sidesheet
Completes: [AB#178453](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/178453)

Error boundary on client, for each route and for sidesheet

---

src/Core/AppBuilder/Types/AppGroupe.ts
src/Core/Client/ClientContext/clientContext.tsx
src/apps/apps.ts
src/components/Layouts/MainLayout.tsx
src/components/Menu/FullscreenMainMenu.tsx
src/components/Menu/MainMenu.tsx
src/components/Menu/Styles.ts
src/components/Menu/utils.tsx
src/components/Routes/Routes.tsx
src/components/TopBar/TopBar.tsx

Completes: [AB#139756](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/139756)

First version of fullscreen main menu with some related menu fixes/additions

---

src/apps/Construction/index.tsx

Adding installation tab to construction progress app.

feat: add installation power bi to construction progress

---

src/apps/Construction/index.tsx
src/packages/KPI/src/Components/KpiBar/KpiBar.tsx
src/packages/KPI/src/Components/KpiItem/KpiItem.tsx

Include option to add tooltip content to a kpi item.
Added tooltip content to critical status kpi item in construction

[Kpi & Construction] - feat: add tooltip to kpi item

---

src/apps/Construction/DetailsPage/components/footers/SumColumnFooter.tsx
src/apps/Construction/DetailsPage/components/footers/SumColumnFooterCount.tsx
src/apps/Construction/DetailsPage/components/footers/SumColumnFooterCountTotal.tsx
src/apps/Construction/DetailsPage/components/footers/SumColumnFooterSum.tsx
src/apps/Construction/DetailsPage/tableConfig.tsx
src/apps/Construction/DetailsPage/types.ts
src/apps/Construction/DetailsPage/utils.tsx

Refactored some of the types and util functions for displaying the details view in Construction progress - Work Prep.
Also now showing workorder stauses W01 - W08 instead of E10 - E40

[Construction] -  chore: refactor table config and details view

---

src/modules/powerBI/src/Api/fusionApi.ts

[PowerBi] - fix: update base uri for powerbi

---

src/Core/PageViewer/index.tsx

fix: remove semicolon from html

---

src/Core/Client/Functions/HttpClient.ts
src/Core/PageViewer/Components/PageViewerPages/PageViewerPages.tsx
src/Core/PageViewer/Types/State.ts
src/apps/Construction/index.tsx
src/modules/powerBI/src/Api/fusionApi.ts
src/modules/powerBI/src/PowerBI.tsx
src/modules/powerBI/src/api.ts

Feature/hotfix: fusion powerbi

---

src/apps/Construction/index.tsx
src/packages/Diagrams/src/Visuals/HorizontalBarVisual/Components/GroupingSelectors.tsx
src/packages/Diagrams/src/Visuals/HorizontalBarVisual/Components/index.ts
src/packages/Diagrams/src/Visuals/HorizontalBarVisual/Hooks/useHorizontalBarChart.ts
src/packages/Diagrams/src/Visuals/HorizontalBarVisual/HorizontalBarVisual.tsx
src/packages/Diagrams/src/Visuals/HorizontalBarVisual/Types/barVisualOptions.ts

Add option to have grouping functionality in horizontal bar chart. It groups on category(?) and series. Added to construction progress, work prep graph.

[Diagrams] - feat: grouping horizontal graph

---

src/packages/Diagrams/src/Components/GetChartsStyles.ts
src/packages/Diagrams/src/Visuals/HorizontalBarVisual/HorizontalBarVisual.tsx

fix: scroll

---

src/apps/Construction/index.tsx
src/packages/Diagrams/src/Components/GetCharts.tsx
src/packages/Diagrams/src/Types/analyticsOptions.tsx
src/packages/Diagrams/src/Visuals/CriticalWoTable/CriticalWoTable.tsx
src/packages/Diagrams/src/Visuals/CriticalWoTable/components/WoNumbers.tsx

Add option to include grouping functionality to Critical WO table diagram. 

[Diagrams] - Feature/construction progress wo table select grouping

---

src/Core/Client/Functions/RegisterActions.ts
src/Core/Client/Functions/Settings.ts
src/Core/Client/Service/createClient.ts
src/Core/Client/Service/setupUserData.ts
src/Core/Client/Types/ClientSettings.ts
src/Core/httpClient/src/graphUtils.ts
src/components/TopBar/TopBar.tsx

Added user data to global state. 
Completes: [AB#181954](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/181954)

Add user data to global state

---

src/components/ParkView/Components/GardenView.tsx
src/components/ParkView/Components/GroupingSelector.tsx

fieldsettings would break hanging gardens if not set in config even though its optional.

[Garden] - fix: fieldsettings optional checks

---

src/apps/ScopeChangeRequest/Components/DetailView/Components/Attachments.tsx
src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx

can now download attachments

---

src/components/Menu/FullscreenMainMenuStyles.ts

More compact mega menu.
Completes: [AB#182184](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/182184)

Some cleanup and more compact menu styles

---

src/components/Menu/MainMenu.tsx
src/components/Menu/MainMenuStyles.ts
src/components/Menu/Styles.ts
src/components/TopBar/Logo/Logo.tsx

Removed Logo and Home icon, also removed the possibility to click on groups
Completes: [AB#182186](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/182186)
Completes: [AB#182180](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/182180)

Removed Logo and made groupes not clickable

---

src/packages/Table/Components/Cells/ProgressCell.tsx
src/packages/Table/Components/Cells/index.tsx
src/packages/Table/Utils/utils.tsx
src/packages/Table/types.ts

Generic progress(bar) custom table cell. Accepts percentage values as numbers (0-100) and displays a progress bar.
Completes: [AB#145793](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/145793)

Generic progress(bar) custom table cell

---

src/apps/Construction/Components/CriticalWoTable/CriticalWoTable.tsx
src/apps/Construction/Components/CriticalWoTable/components/WoNumbers.tsx
src/apps/Construction/Components/CriticalWoTable/types/index.ts
src/apps/Construction/Components/CriticalWoTable/utils/index.ts
src/apps/Construction/index.tsx

Completes: [AB#183800](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/183800)

[Construction Progress] - Chore/critical wo table add more weeks

---

src/apps/Construction/index.tsx
src/packages/Diagrams/src/Utils/cutoffUtils.ts
src/packages/Diagrams/src/Visuals/ConstructionVisual/index.ts
src/packages/Diagrams/src/Visuals/ConstructionVisual/theme.ts

Completes: [AB#183830](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/183830)

[Construction Visual] - feat: add theme colors to graph

---

src/Core/Dashboard/Components/DashboardView/Dashboard.tsx
src/Core/Dashboard/Components/Header/Header.tsx
src/Core/Dashboard/Components/Header/HeaderStyles.ts

[DashBoard] - chore: make tab chips into tabs

---

src/packages/KPI/src/Components/KpiItem/KpiItem.tsx
src/packages/KPI/src/Components/KpiItem/KpiItemStyles.ts

Made KPI styling similar to what is shown in figma.
New:
Old:

[KPI] - chore: update KPI styling

---

src/apps/ScopeChangeRequest/Components/Workflow/Contributors.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Workflow.tsx
src/apps/ScopeChangeRequest/Components/Workflow/WorkflowCriterias.tsx

fix duplicate key in iterator

---

src/packages/KPI/src/Components/KpiItem/KpiItem.tsx
src/packages/KPI/src/Components/KpiItem/KpiItemStyles.ts

Change styling so doesnt take that much space and looks like what is sketched in figma.

[KPI] - chore: update styling

---

src/apps/Construction/Components/CriticalWoTable/CriticalWoTable.tsx
src/apps/Construction/Components/CriticalWoTable/components/WoNumbers.tsx
src/apps/Construction/Components/CriticalWoTable/utils/index.ts

Small refactoring
* Add return statements
* Make util less verbose..

[Construction] - Chore/critical wo table refactoring

---

src/packages/Diagrams/src/Components/GetCharts.tsx
src/packages/Diagrams/src/Utils/cutoffUtils.ts
src/packages/Diagrams/src/Visuals/ConstructionVisual/Components/Graph.tsx
src/packages/Diagrams/src/Visuals/ConstructionVisual/Components/Legend/Legend.tsx
src/packages/Diagrams/src/Visuals/ConstructionVisual/Components/Legend/index.ts
src/packages/Diagrams/src/Visuals/ConstructionVisual/Components/Legend/styles.tsx
src/packages/Diagrams/src/Visuals/ConstructionVisual/Components/index.ts
src/packages/Diagrams/src/Visuals/ConstructionVisual/ConstructionVisual.tsx
src/packages/Diagrams/src/Visuals/ConstructionVisual/Utils/config.ts
src/packages/Diagrams/src/Visuals/ConstructionVisual/Utils/htmlLegendPlugin.tsx
src/packages/Diagrams/src/Visuals/ConstructionVisual/index.ts

Made the accumulated line on construction visual graph dashed and also updated the type for series for better type hinting when customizing specific datasets.
Completes: [AB#183830](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/183830)

[Construction Visual] - chore: add dashed line to accumulated line

---

.eslintrc.json
src/apps/Construction/index.tsx
src/modules/powerBI/src/Components/PageNavigation.tsx
src/modules/powerBI/src/Components/index.ts
src/modules/powerBI/src/Hooks/index.ts
src/modules/powerBI/src/Hooks/useActivePage.ts
src/modules/powerBI/src/Hooks/useGetPages.ts
src/modules/powerBI/src/PowerBI.tsx

Completes: [AB#183806](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/183806)

[PowerBI] - Feature/powerbi custom page navigation

---

src/packages/Diagrams/src/Utils/cutoffUtils.ts
src/packages/Diagrams/src/Visuals/ConstructionVisual/Components/Graph.tsx
src/packages/Diagrams/src/Visuals/ConstructionVisual/Utils/config.ts
src/packages/Diagrams/src/Visuals/ConstructionVisual/Utils/htmlLegendPlugin.tsx

When using the filter, the graph would not render the bars and lines using ReactDOM.Render method for the html plugin.
hotfix is to use javascript to render the legend instead.

[Construction Visual] - fix: html legend when filtering

---

src/Core/Client/Home/PbiHome/PbiHome.tsx
src/Core/Client/Service/appConfig.ts
src/apps/apps.ts
src/components/Menu/FullscreenMainMenu.tsx
src/components/Menu/FullscreenMainMenuStyles.ts
src/components/Menu/MainMenu.tsx
src/components/Menu/utils.tsx
src/components/TopBar/TopBar.tsx
src/components/TopBar/TopBarStyle.ts

Env on title and other chores
Completes: [AB#184736](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/184736) [AB#184731](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/184731)

Env on title and other chores

---

src/packages/Table/Utils/ColumnDefault.tsx
src/packages/Table/Utils/columnGenerators.tsx

Bump to 90px margin for tables with few columns to avoid scrollbar

---

src/packages/Diagrams/src/Visuals/HorizontalBarVisual/Utils/createSeriesByKeys.ts

There is one object that makes the horizontal bar graph in Construction Progress to crash and not render any bars:
The object that makes the graph fail contains these properties:
```
{
actualCompletionDate: null
actualStartupDate: null
category: null
commissioningPackageNo: null
createdDate: null
description: null
discipline: null
earnedManHours: null
estimatedManHours: null
expendedManHours: null
facility: "JCA"
holdBy: null
isVoided: false
jobStatus: null
jobStatusCutoffs: (3) [{…}, {…}, {…}]
location: null
materialStatus: null
milestone: null
onshoreOffshore: null
plannedCompletionDate: null
plannedStartupDate: null
project: null
projectProgress: null
remainingManHours: null
responsible: null
sourceIdentity: null
subMilestone: null
title: null
typeOfWork: null
updatedDate: null …
```

[HorizontalBarVisual] - hotfix: handle null value

---

src/components/Menu/MainMenu.tsx
src/components/Menu/MainMenuStyles.ts

Fixing a smal issue of not all in a lin is clickable.

More compact links in menu and all is clickable

---

src/AppClient.tsx
src/apps/apps.ts

removed prod from swcr and work-order and removed global compact mode eds

---

src/apps/Construction/index.tsx

Change the uri for punch analytics pbi report in construction progress.

[Construction Progress] - chore: change punch analytics uri

---

src/Core/Client/Functions/Settings.ts
src/Core/Client/Service/appsProvider.ts
src/Core/Client/Service/createClient.ts
src/Core/Client/Types/AppManifest.ts
src/Core/Client/Utils/environment.ts
src/Core/Client/index.ts
src/Core/DataFactory/Components/AddMenu.tsx
src/apps/apps.ts
src/components/Menu/MainMenu.tsx
src/components/Menu/MenuItem.tsx

AppFilter on env, now allowing dev test and prod filters

feature/env-filtering 

---

src/packages/Form/Readme.md
src/packages/Form/src/Hooks/useForm.ts
src/packages/Form/src/Types/form.ts

Wrote a readme for the form package which describes how to use it
Completes: 
[AB#170415](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/170415)

Form implementation guid

---

src/packages/Table/Components/Cells/ArrayCell.tsx
src/packages/Table/Components/Cells/index.tsx
src/packages/Table/Utils/utils.tsx
src/packages/Table/types.ts

add custom array cell type

---

src/packages/Table/Components/Cells/RelativeDateCell.tsx
src/packages/Table/Components/Cells/index.tsx
src/packages/Table/Utils/utils.tsx
src/packages/Table/types.ts

Add support for formatting to relative date

---

src/components/TopBar/TopBar.tsx
src/components/TopBar/TopBarStyle.ts

added disabled search field in top-bar
Completes: [AB#185978](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/185978)

chore/search in top-bar

---

src/Core/Dashboard/Components/Header/Header.tsx
src/Core/Dashboard/Components/Header/HeaderStyles.ts
src/modules/powerBI/src/Components/PageNavigation.tsx

[Dashboard & PowerBI] - chore: make tabs height smaller

---

Changelog.md
README.md

doc/Update README.md

---

src/apps/ScopeChangeRequest/Api/Search/PCS/searchFunctionalRole.ts
src/apps/ScopeChangeRequest/Api/Search/PCS/searchPcs.ts
src/apps/ScopeChangeRequest/Components/DetailView/Components/OriginLink.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestForm.tsx
src/apps/ScopeChangeRequest/Components/SearchableDropdown/PCSPersonRoleSearch.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/ScopeChangeSidesheet.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Components/CriteriaDetail.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Components/WorkflowCriteria.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Types/actions.ts
src/apps/ScopeChangeRequest/Hooks/useScopeChangeAccess.ts
src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx
src/apps/ScopeChangeRequest/Sections/AnalyticsConfig.tsx
src/apps/ScopeChangeRequest/Types/scopeChangeRequest.ts

Feature scopechange visual changes

---

pipelines/frontend-build.yml

fix: add app name to build job

---

src/modules/powerBI/src/Components/Filter/FilterGroup/FilterGroup.tsx
src/modules/powerBI/src/Components/Filter/FilterGroup/Styles.tsx
src/modules/powerBI/src/Components/Filter/FilterItems/FilterItems.tsx
src/modules/powerBI/src/Components/Filter/FilterItems/Item.tsx
src/modules/powerBI/src/Components/Filter/FilterItems/Styles.tsx
src/modules/powerBI/src/Components/Filter/PowerBIFilter.tsx

When user clicks on a label, only that filter item will be applied and all others will be deselected.

[PowerBI] - feat: add functionality for single select click on filter

---

src/modules/powerBI/src/Components/Filter/Styles.tsx

Ability to scroll when filter item groups overflows.

[PowerBI] - fix: add scroll when filter item groups overflows

---

src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx

add filters for scopechange

---

src/apps/ScopeChangeRequest/Api/ScopeChange/Request/initiateScopeChange.ts
src/apps/ScopeChangeRequest/Components/Sidesheet/ScopeChangeSidesheet.tsx

Initiate request

---

src/apps/apps.ts

Release scopechange to test

---

.env
public/client-config.json

Detter er en start på en flere stegs rakket men ønsker å få ting på plass før jeg sriver oppstarten om.
Completes: [AB#189488](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/189488)

chore/added tenantId and clientId to client config and env file

---

src/apps/ScopeChangeRequest/Components/Sidesheet/ScopeChangeSidesheet.tsx
src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx

Quick fixes

---

src/AppClient.tsx

added default config

---

src/Core/WorkSpace/src/Components/DataViewerHeader/HeaderStyles.ts
src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceViewStyles.ts
src/Core/WorkSpace/src/Components/WorkSpaceTabs/WorkSpaceTabs.tsx

Remove padding from workspace panel tab so scroll bar doesnt overflow.

[Workspace] - fix: scroll inside workspace (garden)

---

src/apps/Handover/index.ts

Register table view for handover app.

[Handover app] - chore: register table view for handover

---

src/packages/Sidesheet/Components/ResizableSidesheet.tsx

fix: height and scroll for sidesheet

---

src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetStatuses/CellWithLink.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/SidesheetHeader.tsx
src/apps/Handover/Garden/hooks/useHandoverResource.ts
src/apps/ScopeChangeRequest/Functions/kFormatter.ts
src/apps/ScopeChangeRequest/Sections/AnalyticsConfig.tsx
src/apps/apps.ts
src/apps/swcr/CustomViews/SwcrSideSheet.tsx
src/apps/swcr/index.ts

Hotfix prod links

---

src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestForm.tsx
src/apps/ScopeChangeRequest/Hooks/React-Query/useScopechangeMutation.ts
src/packages/Filter/Context/FilterProvider.tsx

Scopechange persist filter when invalidate list

---

src/apps/Handover/Garden/CustomViews/HandoverGardenHeader.tsx
src/apps/Handover/Garden/CustomViews/index.ts
src/apps/Handover/index.ts

Completes: [AB#194027](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/194027)

[Handover Garden] - chore: make header titles not bold

---

src/apps/Handover/Garden/utility/handoverItemMapping.ts

Completes: [AB#194018](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/194018)

[Handover Garden] - chore: change os status dots color

---

src/apps/Handover/Garden/CustomViews/HandoverGardenItem/GardenItemStyles.ts

Completes: [AB#194017](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/194017)

[Handover Garden] - chore: change handover item outline color

---

src/Core/WorkSpace/src/Components/DataViewerHeader/HeaderStyles.ts
src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceView.tsx
src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceViewStyles.ts
src/Core/WorkSpace/src/Components/WorkSpaceTabs/WorkSpaceTabs.tsx
src/Core/WorkSpace/src/Components/WorkSpaceTabs/WorkSpaceTabsStyles.ts
src/apps/Handover/Garden/components/HandoverItemPopover/index.tsx
src/apps/Handover/Garden/components/HandoverItemPopover/styles.tsx
src/apps/Handover/Garden/components/commonStyles.ts
src/apps/Handover/Garden/components/statusItems.ts
src/apps/Handover/Garden/utility/getStatusBarData.ts
src/apps/Handover/index.tsx
src/components/ParkView/Components/GardenView.tsx
src/components/ParkView/Styles/common.ts

Added one KPI, need to get more info about the other ones before adding them.
Completes: [AB#194031](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/194031)
Completes: [AB#194026](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/194026)

[Handover] - Chore/handover register kpi

---

src/apps/Construction/index.tsx

Remove the built in filter pane from Installation report.

[Construction Progress] - chore: remove pbi filter pane for installation

---

src/Core/httpClient/src/baseClient.ts
src/apps/Construction/index.tsx
src/modules/powerBI/src/Api/fusionApi.ts

fix powerbi reports

---

src/Core/Client/Home/Task/Task.tsx
src/apps/Handover/index.tsx
src/apps/swcr/index.ts

chore: use production in production, else use ci for fusion

---

src/apps/Commissioning/index.tsx
src/apps/Construction/index.tsx

fixed pages not working

---

src/apps/Handover/index.tsx
src/packages/Table/Components/Cells/NumberCell.tsx
src/packages/Table/Components/Cells/index.tsx
src/packages/Table/Utils/utils.tsx
src/packages/Table/types.ts

Added a number cell in the table component. Using it in the Handover app.
Completes: [AB#194029](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/194029)

[Table & Handover] - feat: add number cell for table

---

src/apps/Handover/Garden/components/HandoverItemPopover/index.tsx
src/apps/Handover/Garden/components/HandoverItemPopover/styles.tsx

Add description to popover and also fix a spacing issue inside the popover if description in very long.
Completes: [AB#194023](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/194023)

[Handover] - chore: add description to popover and fix spacing

---

src/apps/swcr/index.ts

Added some initial filters to SWCR app.

[SWCR] - chore: add initial filter to swcr

---

src/Core/Client/Home/Task/Task.tsx
src/Core/Client/Types/ScopeAndUrls.ts
src/Core/Notifications/API/getReadNotifications.ts
src/Core/Notifications/API/getUnreadNotifications.ts
src/Core/Notifications/API/readNotification.ts
src/modules/powerBI/src/Api/fusionApi.ts

added new fusion urls

---

src/Core/Notifications/Components/NotificationCard.tsx
src/Core/Notifications/Components/NotificationsDrawer.tsx
src/Core/Notifications/Hooks/useNotificationCenter.ts
src/Core/WorkSpace/src/Components/FallbackSidesheet/Fallback.tsx
src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceView.tsx
src/Core/WorkSpace/src/WorkSpaceApi/Api.ts
src/Core/WorkSpace/src/WorkSpaceApi/State.ts
src/Core/WorkSpace/src/WorkSpaceApi/WorkSpaceTypes.ts
src/Core/WorkSpace/src/WorkSpaceApi/useWorkSpace.ts
src/apps/Handover/index.tsx
src/apps/HeatTraceInstallation/HeatTraceInstallationApp.tsx
src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx
src/apps/WorkOrder/index.tsx
src/apps/handoverApp.ts
src/apps/swcr/index.ts

Object driven URL

---

src/apps/Handover/Garden/hooks/useHandoverResource.ts

[Handover] - Fix: handover resources api endpoint

---

src/Core/Client/Types/ScopeAndUrls.ts

chore: add dataproxy to scope and urls

---

src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceView.tsx
src/Core/WorkSpace/src/Context/DataProvider.tsx

fix data fetch on sidesheet mount

---

src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceView.tsx

clear url when sidesheet closes

---

src/packages/authentication/src/authService.ts

get active account

---

src/Core/WorkSpace/src/Context/DataProvider.tsx

hotfix workspace

---

src/packages/authentication/src/authService.ts

revert auth change

---

src/Core/WorkSpace/src/Context/DataProvider.tsx

validate response

---

src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceView.tsx
src/Core/WorkSpace/src/Components/WorkSpaceTabs/WorkSpaceTabs.tsx
src/Core/WorkSpace/src/Context/DataProvider.tsx

fixed loading icon

---

src/apps/swcr/hooks/useSignatures.ts

Using dataProxy instead of fusion and fix contextId if app is production.

[SWCR] - fix: api endpoint for swcr signatures

---

src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceView.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RequestDetailView.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestForm.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Components/WorkflowIcon.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Contributor/Components/Contributors.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/CriteriaDetail.tsx
src/apps/ScopeChangeRequest/Hooks/React-Query/useScopechangeMutation.ts
src/apps/ScopeChangeRequest/Hooks/React-Query/useScopechangeQueryKeyGen.ts
src/apps/ScopeChangeRequest/WorkspaceConfig/Table/WorkflowCompact.tsx
src/apps/ScopeChangeRequest/WorkspaceConfig/Table/WorkflowDot.tsx
src/apps/ScopeChangeRequest/WorkspaceConfig/Table/tableConfig.tsx
src/components/TopBar/TopBar.tsx

[AB#196884](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/196884)

fix sidesheet keeps redirecting

---

Changelog.md
src/components/TopBar/TopBar.tsx

updated changelog

---

src/apps/ScopeChangeRequest/Api/ScopeChange/Workflow/signCriteria.ts
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/SignWithComment.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/WorkflowCriteria.tsx

[AB#197065](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/197065)

Reject and close functionality scope change

---

src/Core/PerformanceObserver/PerformanceObserver.tsx
src/Core/PerformanceObserver/usePerformanceObserver.ts
src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx
src/Core/WorkSpace/src/Components/DataViewerHeader/HeaderStyles.ts

Devtools added to workspace, shows a warning if you make many concurrent api calls. 

Performance observer devtools

---

src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx
src/Core/WorkSpace/src/Components/WorkSpace/WorkspaceErrorPage.tsx
src/Core/WorkSpace/src/Components/WorkSpaceTabs/WorkSpaceTabs.tsx
src/Core/WorkSpace/src/Context/DataProvider.tsx
src/Core/WorkSpace/src/Functions/checkResponseCode.ts
src/Core/WorkSpace/src/Hooks/useIntervalTimestamp.tsx
src/Core/WorkSpace/src/WorkSpaceApi/WorkSpaceTypes.ts
src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx
src/apps/Handover/index.tsx
src/apps/ScopeChangeRequest/Components/DetailView/Components/RelatedObjects/CommPkg/CommPkg.tsx
src/apps/ScopeChangeRequest/Components/DetailView/Components/RelatedObjects/CommPkg/commPkgIcon.tsx
src/apps/ScopeChangeRequest/WorkspaceConfig/dataOptions.ts
src/apps/WorkOrder/index.tsx
src/apps/handoverApp.ts
src/apps/swcr/index.ts
src/packages/Filter/Services/creatFilter.ts

Completes: 
[AB#200149](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/200149)
[AB#200151](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/200151)

Response validation implemented

---

src/apps/ScopeChangeRequest/Api/ScopeChange/Request/getHistory.ts
src/apps/ScopeChangeRequest/Components/DetailView/Components/History/HistoryItem.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/WorkflowCriteria.tsx
src/apps/ScopeChangeRequest/Schemas/scopeChangeRequestSchema.ts
src/apps/ScopeChangeRequest/Types/scopeChangeRequest.ts

fix crash in test

---

src/apps/ScopeChangeRequest/Components/STID/Components/AdvancedDocumentSearch.tsx

Completes:
[AB#200404](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/200404)

make advanced search reflect chosen type

---

src/apps/ScopeChangeRequest/Components/SearchableDropdown/RelatedObjectsSearch/RelatedObjectsSearch.tsx

add commPkgIcon to related objects search

---

src/Core/WorkSpace/src/Components/WorkSpaceTabs/WorkSpaceTabs.tsx
src/apps/ScopeChangeRequest/Components/DetailView/Components/RequestDetailView/Double.tsx
src/apps/ScopeChangeRequest/Components/DetailView/Components/RequestDetailView/RequestDetailViewStyles.ts
src/apps/ScopeChangeRequest/Components/DetailView/Components/RequestDetailView/Single.tsx

clear loading indicators

---

src/apps/ScopeChangeRequest/WorkspaceConfig/Table/tableConfig.tsx

 [Scope-change] Pending contribution icon table

---

src/apps/ScopeChangeRequest/Components/Workflow/Contributor/Components/Contributors.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Step/Components/WorkflowStep.tsx

Completes:
[AB#201656](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/201656)

hide contributor on other than current step

---

src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceView.tsx
src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceViewStyles.ts

fix/workspace sidesheet  push main container

---

src/apps/ScopeChangeRequest/Api/Search/STID/searchDocuments.ts
src/apps/ScopeChangeRequest/Components/DetailView/Components/ChevronList/ChevronList.tsx
src/apps/ScopeChangeRequest/Components/SearchableDropdown/RelatedObjectsSearch/RelatedObjectsSearch.tsx
src/apps/ScopeChangeRequest/Components/SearchableDropdown/RelatedObjectsSearch/RelatedObjectsStyles.ts
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/WorkflowCriteria.tsx
src/apps/ScopeChangeRequest/Hooks/Search/useReferencesSearch.ts

[Scope change] pushing pixels

---

src/apps/apps.ts
src/apps/workPreparation/index.ts

app names and work prep
Completes: [AB#203422](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/203422)

[Menu] App names and work prep

---

src/apps/ScopeChangeRequest/Components/DetailView/Components/RelatedObjects.tsx
src/apps/ScopeChangeRequest/Components/DetailView/Components/RelatedObjects/Area/Area.tsx
src/apps/ScopeChangeRequest/Components/DetailView/Components/RelatedObjects/CommPkg/CommPkg.tsx
src/apps/ScopeChangeRequest/Components/DetailView/Components/RelatedObjects/Discipline/Discipline.tsx
src/apps/ScopeChangeRequest/Components/DetailView/Components/RelatedObjects/Systems/System.tsx
src/apps/ScopeChangeRequest/Components/DetailView/Components/RelatedObjects/Tags/Tag.tsx
src/apps/ScopeChangeRequest/Components/DetailView/Components/RequestDetailView/Double.tsx
src/apps/ScopeChangeRequest/Components/DetailView/Components/RequestDetailView/Single.tsx
src/apps/ScopeChangeRequest/Hooks/React-Query/useIsReferencesLoading.ts
src/apps/ScopeChangeRequest/Hooks/useEagerLoadingReferences.ts
src/apps/ScopeChangeRequest/Types/scopeChangeRequest.ts

[Scope-change] fix loading spinner sidesheet

---

src/apps/ScopeChangeRequest/Components/DetailView/Components/RequestDetailView/RequestDetailViewStyles.ts
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/CriteriaDetail.tsx

Completes:
[AB#204077](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/204077)
[AB#203956](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/203956)
[AB#203952](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/203952)

[Scope-change] Fixes/pixels

---

src/apps/ScopeChangeRequest/Api/STID/getDocumentById.ts

[Hot-fix] fix STID document lookup failing

---

src/packages/Table/Components/Table.tsx

[Table] fix right align numbers table

---

src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceView.tsx
src/Core/WorkSpace/src/WorkSpaceApi/WorkSpaceTypes.ts
src/Core/WorkSpace/src/WorkSpaceApi/useWorkSpace.ts
src/Core/WorkSpace/src/WorkSpaceApi/workspaceApi.ts
src/Core/WorkSpace/src/WorkSpaceApi/workspaceState.ts

Default tab on load workspace

---

src/apps/ScopeChangeRequest/Api/PCS/getAreaByCode.ts

getAreaByCode failing

---

src/apps/Handover/index.tsx
src/apps/WorkOrder/index.tsx
src/apps/swcr/index.ts

chore: change default tabs to garden

---

src/apps/Handover/Garden/components/commonStyles.ts
src/apps/Handover/index.tsx

Completes: [AB#203811](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/203811)

[Handover] - fix: styling on status in table

---

src/apps/WorkOrder/Garden/components/WorkOrderItem/WorkOrderItem.tsx
src/apps/WorkOrder/Garden/components/WorkOrderItem/styles.ts
src/components/ParkView/Components/VirtualGarden/GardenItemContainer.tsx
src/components/ParkView/Components/VirtualGarden/VirtualGarden.tsx
src/components/ParkView/Models/gardenOptions.ts

[Garden] - feat: Highlight selected garden item

---

src/Core/PowerBiViewer/src/Components/PowerBiViewerHeader/PowerBiViewerHeader.tsx
src/Core/PowerBiViewer/src/Components/PowerBiViewerHeader/PowerBiViewerHeaderStyles.ts
src/components/Menu/Components/CompactMenu/CompactMenu.tsx
src/components/Menu/Components/CompactMenu/CompactMenuStyles.ts
src/components/Menu/Components/Favourites/FavouritesStyles.ts
src/components/Menu/Components/MenuItem/MenuItemStyles.ts
src/components/Menu/Components/Sheard/Styles.ts
src/components/Messages/Service/Hooks/useServiceMessage.ts
src/components/TopBar/Logo/Logo.tsx

- PowerBIViewer Header fix.
- font size endres til 14px i ytterste meny
- tekst må top alignes slik at den beholder samme toppunkt
- litt mer luft mellom "expanded menu" og resten (ref Figma)
- ikon og portal heading iht Figma
- lik avstand mellom Favourites, divider og første menypunkt i alle menynivåer
- divider må være høyre-aligna med chevrons
- default text color skal være 3D3D3D
Completes: [AB#200494](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/200494)

[Menu] pixel pushing

---

src/Core/DataFactory/Functions/createDataFactory.ts
src/Core/DataFactory/Hooks/useFactories.ts
src/Core/DataFactory/Types/factory.ts
src/apps/ScopeChangeRequest/WorkspaceConfig/dataCreatorConfig.ts

Completes: 
[AB#205176](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/205176)

[Data Factory] Optional access check

---

src/apps/WorkOrder/Garden/components/Popover/WorkOrderPopover.tsx
src/apps/WorkOrder/Garden/components/WorkOrderItem/WorkOrderItem.tsx
src/apps/WorkOrder/Garden/components/WorkOrderItem/styles.ts
src/apps/WorkOrder/index.tsx

Completes: [AB#202581](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/202581)

[Workorder] - chore: add size icon, flag, progress to wo item

---

src/apps/Checklist/index.ts
src/apps/Punch/index.ts
src/apps/apps.ts

added checklist and punch analytics.

[Checklist - Punch ]- PowerBiViewer

---

Changelog.md
src/apps/apps.ts

Update changelog and - Piping and Heat trace released to test

[chore] - changelog

---

src/apps/swcr/CustomViews/SwcrGardenItem.tsx

Completes: [AB#205560](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/205560)

[SWCR] - chore: add border to selected swcr garden item

---

src/AppClient.tsx

Completes: [AB#203777](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/203777)

[Portal] - chore: add extra height to scrollbar

---

src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx
src/Core/WorkSpace/src/Components/WorkSpace/HeaderFilterWrapper.tsx
src/components/Icon/FilterIconFilled.tsx

[Filter] Visual changes

---

src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RequestTab.styles.ts
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/WorkflowCriteria.tsx

[Scope change] Visual fixes

---

src/apps/swcr/index.ts
src/apps/swcr/utilities/tableSetup.tsx

[SWCR]- chore: table config

---

src/packages/Filter/Components/FilterGroup/FilterGroup-Styles.ts
src/packages/Filter/Components/FilterGroup/FilterGroup.tsx
src/packages/Filter/Components/FilterGroup/FilterGroupStyles.ts
src/packages/Filter/Components/FilterItem/FilterItem-Styles.ts
src/packages/Filter/Components/FilterView/FilterView-style.ts
src/packages/Filter/Components/FilterView/FilterView.tsx

New compact filter styles requested by Atle and CC

[Workspace] - Compact filter styles - Atle Style

---

src/apps/WorkOrder/index.tsx
src/apps/WorkOrder/utility/tableConfig.tsx
src/packages/Table/Components/Cells/ProgressCell.tsx

[Workorder] - chore: table config

---

src/apps/swcr/index.ts
src/apps/swcr/utilities/filterSetup.ts

[SWCR] - chore: filter config

---

src/apps/Installation/index.ts
src/apps/apps.ts
src/apps/workPreparation/index.ts

Små oppdateringer  på powerbi og fjerning av apper.
Completes: [AB#205989](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/205989) [AB#205991](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/205991)

[Power-bi] - Power-bi-updates

---

src/Core/WorkSpace/src/Components/WorkSpace/WorkspaceFilterWrapper.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetBanner/SidesheetBanner.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/hooks/mutations/useRequestMutations.ts
src/apps/ScopeChangeRequest/hooks/queries/useScopeChangeAccess.ts
src/apps/ScopeChangeRequest/hooks/sidesheet/useSidesheetEffects.tsx

[Scope change] Sidesheet small fixes

---

src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceView.tsx

[Workspace] Filter hotfix

---

src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
src/apps/ScopeChangeRequest/Components/MenuButton/Components/IconMenu.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetBanner/SidesheetBanner.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RequestTab.styles.ts
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RequestTab.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/SignWithComment.tsx
src/apps/ScopeChangeRequest/api/ScopeChange/Request/patchScopeChange.ts
src/apps/ScopeChangeRequest/hooks/mutations/useRequestMutations.ts
src/packages/Sidesheet/Components/ResizableSidesheet.tsx

[Scope change] Last minute fixes

---

src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/SignWithComment.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/WorkflowCriteria.tsx

[Scope change] Reject with comment

---

src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/useWorkflowSigning.tsx

Didnt add comment

---

src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Area/Area.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Discipline/Discipline.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Tags/Tag.tsx

[Scope change] References long text break

---

src/packages/Filter/Hooks/useFilterApi.ts

fix filter count performance

---

Changelog.md

[Changelog] - update

---

src/packages/Filter/Hooks/useFilterApi.ts
src/packages/Filter/functions/doesItemPass.ts

fix array count

---

src/apps/Handover/Garden/CustomViews/HandoverSideSheet.tsx

[Handover] - fix: add scroll to sidesheet

---

src/packages/Filter/Components/FilterGroup/FilterGroup.tsx
src/packages/Filter/Components/FilterItem/FilterItem.tsx
src/packages/Filter/Hooks/useFilterApi.ts

[Filter] Count performance

---

src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx

[Release control] Add circuit filters

---

src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx
src/packages/Filter/Hooks/useFilterApi.ts

[Release control] Filter sort 

---

src/apps/DisciplineReleaseControl/Components/Workflow/Components/WorkflowFilterDot.tsx
src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx

Fix for width on step filter dots

---

Changelog.md
src/apps/apps.ts

- [PipingAndHeatTrace] - Release.
- [PowerBiFilter] - new styles and virtualization.
- [Filter] - Count optimization
--- 
Completes: [AB#206612](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/206612)

changelog-v0.3.0

---

src/Core/PowerBiViewer/src/Components/PowerBiViewerHeader/PowerBiViewerHeader.tsx
src/Core/PowerBiViewer/src/PowerBiViewer.tsx
src/Core/PowerBiViewer/src/PowerBiViewerStyles.ts
src/modules/powerBI/src/Components/Filter/FilterGroup/Styles.tsx
src/modules/powerBI/src/Components/Filter/FilterItems/FilterItems.tsx
src/modules/powerBI/src/Components/Filter/FilterItems/Item.tsx
src/modules/powerBI/src/Components/Filter/FilterItems/Styles.tsx
src/modules/powerBI/src/Components/Filter/Header/Styles.tsx
src/modules/powerBI/src/Components/Filter/PowerBIFilter.tsx
src/modules/powerBI/src/Components/Filter/Styles.tsx
src/modules/powerBI/src/PowerBI.tsx
src/modules/powerBI/src/Types/options.ts
src/packages/Filter/Components/FilterGroup/FilterGroupStyles.ts
src/packages/Filter/Components/FilterView/FilterView-style.ts

[PowerBI]- Filter styles v2

---

src/Core/WorkSpace/src/Components/DataLoadFailed/DumpsterFireDialog.tsx
src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceView.tsx
src/Core/WorkSpace/src/Components/WorkSpaceTabs/WorkSpaceTabs.tsx

[Workspace] Fix error dialog not mounting

---

src/apps/ScopeChangeRequest/hooks/observers/useOctopusErrorHandler.ts

[Scope change] Fix error parsing

---

src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Area/Area.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/CommPkg/CommPkg.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Discipline/Discipline.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Systems/System.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Tags/Tag.tsx
src/apps/ScopeChangeRequest/Components/PersonRoleSearch/PCSPersonRoleSearch.tsx
src/apps/ScopeChangeRequest/hooks/React-Query/useIsReferencesLoading.ts
src/apps/ScopeChangeRequest/hooks/React-Query/usePreloadCaching.ts
src/apps/ScopeChangeRequest/hooks/Search/usePcsSearch.ts
src/apps/ScopeChangeRequest/keys/ProCoSysQueries.ts

[Scope change] improve queries for PCS

---

src/apps/swcr/utilities/packages.ts

[SWCR] - fix: week number prefix 0 if less than 10

---

src/components/ParkView/Components/GroupingSelector.tsx

Sort the Grouping options inside the Select alphabetically.

[Garden] - chore: sort grouping items

---

src/apps/swcr/CustomViews/StatusFilter.tsx
src/apps/swcr/utilities/filterSetup.tsx

Completes: [AB#203841](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/203841)

[SWCR] - chore: sort status filter items and add custom render

---

src/apps/WorkOrder/utility/tableConfig.tsx
src/packages/Table/Components/Cells/ProgressCell.tsx
src/packages/Table/Components/Cells/StatusCell.tsx
src/packages/Table/Components/Cells/YearWeekCell.tsx
src/packages/Table/Components/Cells/index.tsx
src/packages/Table/Components/Styles.ts
src/packages/Table/Utils/utils.tsx
src/packages/Table/types.ts

[Table & Workorder]- fix:workorder table cells

---

src/packages/Table/Components/Cells/ProgressCell.tsx

[Table] - chore: update styling for progress cell

---

src/apps/Handover/Garden/CustomViews/HandoverGardenItem/GardenItemStyles.ts
src/apps/WorkOrder/Garden/components/WorkOrderItem/styles.ts

[Workorder & Handover] - fix: remove minwidth styling

---

src/apps/ScopeChangeRequest/workspaceConfig/statusBarConfig.ts

[Scope change] KPI last 7 days

---

src/Core/WorkSpace/src/Tabs/ListTab.tsx

[AB#203939](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/203939)

[Table] Padding around table

---

src/Core/WorkSpace/src/Tabs/ListTab.tsx

[Table] Fix scrollbar

---

src/apps/ScopeChangeRequest/Components/DetailView/References.tsx

[Scope change] No references message

---

src/Core/WorkSpace/src/index.ts
src/apps/DisciplineReleaseControl/Components/Electro/Components/Cable.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/CircuitAndStarter.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/HeatTracingCable.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/JunctionBox.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/Line.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/TestDot.tsx
src/apps/DisciplineReleaseControl/Components/Electro/ElectroNode.tsx
src/apps/DisciplineReleaseControl/Components/Electro/ElectroView.tsx
src/apps/DisciplineReleaseControl/Components/Electro/electroViewHelpers.ts
src/apps/DisciplineReleaseControl/Components/Electro/styles.ts
src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlSidesheet.tsx
src/apps/DisciplineReleaseControl/Functions/statusHelpers.ts
src/apps/DisciplineReleaseControl/Styles/ReleaseControlColors.tsx
src/apps/DisciplineReleaseControl/Styles/SidesheetWrapper.tsx
src/components/ParkView/Components/VirtualGarden/HeaderContainer.tsx

[Piping and Heat trace] - single line diagram improvements

---

src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/SignWithComment.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/SignWithComment/SignWithComment.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/SignWithComment/signWithComment.styles.ts
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/WorkflowCriteria.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/WorkflowCriteria/WorkflowCriteria.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/WorkflowCriteria/workflowCriteria.styles.ts
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/index.ts
src/apps/ScopeChangeRequest/hooks/mutations/useWorkflowSigning.tsx

[Scope change] Workflow refactor

---

src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceViewStyles.ts
src/Core/WorkSpace/src/Components/WorkSpaceTabs/WorkSpaceTabsStyles.ts
src/Core/WorkSpace/src/Tabs/ListTab.tsx
src/components/Layouts/MainLayoutStyles.ts

fixinf layout in workspace for tablel garden and powerbi
Completes: [AB#209574](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/209574)

[WorkSpace] - fixing layout

---

src/apps/apps.ts

Link to AKSO procedures directly from portal menu under collaboration
Completes: [AB#207407](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/207407)

[AKSO procedures] - Added link

---

src/apps/ScopeChangeRequest/workspaceConfig/statusBarConfig.ts

[Scope change] Revert status bar

---

src/Core/Client/Service/setupUserData.ts

[Core] - add user to window

---

src/Core/Notifications/Components/NotificationCard.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTab.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTabTitle.tsx
src/apps/ScopeChangeRequest/Components/WoProgressBars/EstimateBar.tsx
src/apps/ScopeChangeRequest/Components/WoProgressBars/ExpendedProgressBar.tsx
src/apps/ScopeChangeRequest/Components/WoProgressBars/ProgressBar.tsx
src/apps/ScopeChangeRequest/Components/WoProgressBars/ProgressBarContainer.styles.ts
src/apps/ScopeChangeRequest/Components/WorkOrderTable/CompactWorkOrder/CompactWorkOrder.tsx
src/apps/ScopeChangeRequest/Components/WorkOrderTable/WorkOrderTable.tsx
src/apps/ScopeChangeRequest/Components/WorkOrderTable/workOrderTable.styles.ts
src/apps/ScopeChangeRequest/api/FAM/getWorkOrderById.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx
src/packages/Table/Components/Cells/RelativeDateCell.tsx

[Scope change] Wo table adjustments

---

src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx
src/Core/WorkSpace/src/Components/WorkSpaceTabs/WorkSpaceTabsStyles.ts
src/Core/WorkSpace/src/Util/tabsConfig.ts
src/Core/WorkSpace/src/WorkSpaceApi/workspaceState.ts
src/apps/Handover/index.tsx
src/apps/swcr/index.ts

[Workspace] - PowerBi is now Analytics and added Handover Anatytics Report

---

src/apps/ScopeChangeRequest/Components/WoProgressBars/EstimateBar.tsx
src/apps/ScopeChangeRequest/Components/WoProgressBars/ExpendedProgressBar.tsx
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[Scope change] Databars in table

---

src/apps/ScopeChangeRequest/Components/Form/ScopeChangeForm.styles.ts
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx

[Scope change] Fix save button dissapear in draft

---

src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RequestTab.tsx

[Scope change] No attachments linked

---

src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Log/LogTab.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTab.tsx

[AB#210787](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/210787)

[Scope change] Fix scrollbar tabs

---

src/apps/DisciplineReleaseControl/Components/Electro/Components/Cable.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/HeatTracingCable.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/JunctionBox.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/Line.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/SpaceHeater.tsx
src/apps/DisciplineReleaseControl/Components/Electro/ElectroNode.tsx
src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx

Completes: [AB#210804](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/210804)

[PipingAndHeatTrace] - sld space heater

---

src/packages/Sidesheet/Components/ResizableSidesheet.tsx

[Portal] Sidesheet max scroll width

---

src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx

[Workspace] Re-add circular progress

---

src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceViewStyles.ts

Make workspace wrapper a grid with three rows (filter, expanded filter, and workspace content like garden)
Fixed horizontal scroll bar to show inview.

[Workspace] - fix: styling for workspace wrapper

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[AB#206461](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/206461)

[Scope change] fix width table config

---

src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx

[Scope change] Fix save button

---

src/apps/ScopeChangeRequest/Atoms/editModeAtom.ts
src/apps/ScopeChangeRequest/Atoms/scopeChangeAtom.ts
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/hooks/queries/useScopeChangeAccess.ts
src/apps/ScopeChangeRequest/hooks/sidesheet/useSidesheetEffects.tsx

Completes:
[AB#211025](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211025)

[Scope change] Fix edit mode button available while in edit mode

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

Completes:
[AB#211064](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211064)

[Scope change] Remove '-' from empty cells

---

src/apps/ScopeChangeRequest/Components/DetailView/Attachments.tsx

Completes: 
[AB#211068](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211068)

[Scope change] Fix attachments font size

---

src/apps/ScopeChangeRequest/Components/Workflow/Contributor/Components/Contributors.tsx
src/apps/ScopeChangeRequest/api/ScopeChange/Access/Workflow/Step/Contributor/canContribute.ts
src/apps/ScopeChangeRequest/keys/queries.ts

[AB#211033](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211033)

[Scope change] Fix cancel query

---

src/apps/ScopeChangeRequest/Components/AdvancedDocumentSearch/AdvancedDocumentSearch.tsx

[Scope change] Wrong title in advanced references

---

src/Core/Notifications/Components/NotificationCard.tsx
src/Core/WorkSpace/src/Context/LocationProvider.tsx

Completes:
[AB#211100](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211100)

[Notifications] Fix redirect url

---

src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx

[Scope change] Add powerBI

---

src/apps/ScopeChangeRequest/Components/Workflow/Contributor/Components/Contributors.tsx

Completes:
[AB#211023](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211023)

[Scope change] Contributor update comment

---

Changelog.md
package.json

[Release] Patch notes

---

src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Tags/Tag.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/WrapperStyles.tsx
src/apps/ScopeChangeRequest/Components/SearchReferences/SearchReferences.tsx
src/apps/ScopeChangeRequest/api/Search/PCS/searchTags.ts
src/apps/ScopeChangeRequest/api/Search/STID/searchDocuments.ts
src/apps/ScopeChangeRequest/api/Search/searchType.ts
src/apps/ScopeChangeRequest/hooks/queries/useUnpackRelatedObjects.ts
src/apps/ScopeChangeRequest/types/ProCoSys/Tag.ts

Completes:
[AB#211036](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211036)

[Scope change] Fix tag metadata

---

Changelog.md
package.json
src/Core/WorkSpace/src/Context/LocationProvider.tsx
src/apps/ScopeChangeRequest/Atoms/editModeAtom.ts
src/apps/ScopeChangeRequest/Atoms/scopeChangeAtom.ts
src/apps/ScopeChangeRequest/Components/AdvancedDocumentSearch/AdvancedDocumentSearch.tsx
src/apps/ScopeChangeRequest/Components/DetailView/Attachments.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Tags/Tag.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/WrapperStyles.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
src/apps/ScopeChangeRequest/Components/SearchReferences/SearchReferences.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/Components/WoProgressBars/EstimateBar.tsx
src/apps/ScopeChangeRequest/Components/WorkOrderTable/CompactWorkOrder/CompactWorkOrder.tsx
src/apps/ScopeChangeRequest/Components/WorkOrderTable/WorkOrderTable.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Contributor/Components/Contributors.tsx
src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx
src/apps/ScopeChangeRequest/api/ScopeChange/Access/Workflow/Step/Contributor/canContribute.ts
src/apps/ScopeChangeRequest/api/Search/PCS/searchTags.ts
src/apps/ScopeChangeRequest/api/Search/STID/searchDocuments.ts
src/apps/ScopeChangeRequest/api/Search/searchType.ts
src/apps/ScopeChangeRequest/hooks/queries/useScopeChangeAccess.ts
src/apps/ScopeChangeRequest/hooks/queries/useUnpackRelatedObjects.ts
src/apps/ScopeChangeRequest/hooks/sidesheet/useSidesheetEffects.tsx
src/apps/ScopeChangeRequest/keys/queries.ts
src/apps/ScopeChangeRequest/types/ProCoSys/Tag.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

Patch Release Castberg Project Portal v0.4.1

---

src/components/Menu/Components/MenuItem/MenuItemStyles.ts
src/components/Menu/Components/Sheard/Styles.ts
src/components/TopBar/Logo/Logo.tsx
src/components/TopBar/TopBar.tsx
src/components/TopBar/TopBarStyle.ts

alle menypunkt må ha samme font size (14px). De som var 13 ble 14 og de som var 14 ble 13 i forrige oppdatering
Portal tittel "Johan Castberg Portal" må venstre alignes med menypunktene, ref Figma
Ikon må endres, ref Figma
Completes: [AB#201923](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/201923)
[AB#200494](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/200494)

[Portal]- Font size must be 14 and logo aligment plus bold for F#¤%

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

Completes:
[AB#211061](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211061)

[Scope change] Widen title field table

---

src/apps/ScopeChangeRequest/Components/DetailView/Attachments.tsx

[Scope change] Attachments overflow

---

src/apps/ScopeChangeRequest/workspaceConfig/statusBarConfig.ts

Old value format 500K = 500 000
New format 500 000
Completes:
[AB#211597](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211597)

[Scope change] KPI value format

---

src/apps/ScopeChangeRequest/Components/SearchReferences/searchReferences.styles.ts

Completes: 
[AB#211600](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211600)

[Scope change] Fix references overlap

---

src/Core/WorkSpace/src/Context/LocationProvider.tsx

[Scope change] Fix api call loop, after rerender

---

src/apps/ScopeChangeRequest/Components/AdvancedDocumentSearch/AdvancedDocumentSearch.tsx
src/apps/ScopeChangeRequest/api/Search/STID/searchDocuments.ts

Completes: 
[AB#211560](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211560)

[Scope change] Remove DOC_ prefix

---

src/packages/Sidesheet/Components/ResizableSidesheet.tsx

Completes: [AB#191723](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/191723)

[SideSheet] - font header set to 24px

---

src/apps/apps.ts

[Apps] - chore: change env to prod for swcr, wo, handover

---

src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx

[Scope change] Remove PowerBI

---

src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTab.tsx

[Scope change] Disable workorders

---

src/Core/Assignments/Components/AssignmentsCard.tsx

[Assignments] Hotfix null date

---

src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTab.tsx

[Scope change] Remove workorders

---

src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/SignWithComment/SignWithComment.tsx

Completes:
[AB#211965](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211965)

[Scope change] Enter prevent refresh

---

src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestForm.tsx

[Scope change] Disable retry

---

src/Core/WorkSpace/src/Context/LocationProvider.tsx
src/apps/ScopeChangeRequest/workspaceConfig/dataOptions.ts

[Workspace] Fix/failed to mount sidesheet

---

src/apps/ScopeChangeRequest/api/PCS/getDocumentIdByNo.ts

[Scope change] fix origin id undefined

---

src/apps/ScopeChangeRequest/Components/DetailView/References.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RequestTab.tsx

[Scope change] No references msg changed

---

src/apps/ScopeChangeRequest/api/Search/STID/searchDocuments.ts
src/apps/ScopeChangeRequest/hooks/queries/useUnpackRelatedObjects.ts

Completes:
[AB#211968](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211968)

[Scope change] Fix document metadata

---

src/apps/ScopeChangeRequest/Components/Workflow/Components/WorkflowIcon.tsx

Completes:
[AB#211040](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211040)

[Scope change] Fix workflow icon shrinking with long comment

---

src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTab.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/workOrderTab.styles.ts
src/apps/ScopeChangeRequest/api/FAM/getWorkOrderById.ts

Completes: 
[AB#212261](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/212261)

[Scope change] Added no workorders  linked

---

Changelog.md
package.json

[Release] Changelog

---

src/Core/Assignments/Components/AssignmentsTab.tsx
src/Core/Client/Home/Task/Task.tsx
src/components/ActionCenter/ActionCenterSidesheet.tsx

[Assignments] Renamed to tasks

---

src/Core/Client/Home/PbiHome/PbiHome.tsx
src/Core/Client/Home/clientHome.tsx
src/Core/PowerBiViewer/src/PowerBiViewer.tsx
src/apps/workPreparation/index.ts

fix home screen power bi and added page tp work prep

---

src/apps/ScopeChangeRequest/api/ScopeChange/Access/Workflow/Step/Criteria/canReassign.ts
src/apps/ScopeChangeRequest/api/ScopeChange/Access/Workflow/Step/Criteria/canSign.ts
src/apps/ScopeChangeRequest/api/ScopeChange/Access/Workflow/Step/Criteria/canUnsign.ts
src/apps/ScopeChangeRequest/api/ScopeChange/Access/Workflow/Step/canManageContributors.ts
src/apps/ScopeChangeRequest/api/ScopeChange/Access/canVoid.ts
src/apps/ScopeChangeRequest/api/ScopeChange/Access/requestAccess.ts
src/apps/ScopeChangeRequest/api/ScopeChange/Request/getHistory.ts
src/apps/ScopeChangeRequest/api/ScopeChange/Request/getScopeChange.ts
src/apps/ScopeChangeRequest/api/ScopeChange/getCategories.ts
src/apps/ScopeChangeRequest/api/ScopeChange/getPhases.ts
src/apps/ScopeChangeRequest/keys/queries.ts

[Scope change] Add abort signals to all queries

---

src/components/Menu/Components/Favourites/Favourites.tsx
src/components/Menu/Context/MenuContext.tsx

Storing the menu state in local storage.
Completes: [AB#211167](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211167)

[Portal]- Persisting menu state

---

src/apps/apps.ts

Completes: [AB#212337](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/212337)

[Portal] - Release Fusion PBI reports to prod

---

src/apps/ScopeChangeRequest/workspaceConfig/dataCreatorConfig.ts

[Scope change] Data creator title

---

Changelog.md
package.json
src/apps/apps.ts

Changlog-1.1.0

---

src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/hooks/context/useScopeChangeContext.ts

[Scope change] Fix atom context

---

src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetBanner/SidesheetBanner.tsx

Completes: 
[AB#212380](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/212380)

[Scope change] Link to origin in banner

---

src/Core/Assignments/Hooks/useAssignments.ts

Completes: 
[AB#212600](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/212600)

[Assignments] Fix assignments date sort

---

src/apps/ScopeChangeRequest/Components/MenuButton/Components/IconMenu.tsx
src/apps/ScopeChangeRequest/Components/MenuButton/Components/MenuButton.tsx

Completes: 
[AB#211648](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211648)

[Scope change] Fix menu ref not updating

---

src/apps/ScopeChangeRequest/Components/AdvancedDocumentSearch/index.ts
src/apps/ScopeChangeRequest/Components/DetailView/References.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Tags/Tag.tsx
src/apps/ScopeChangeRequest/Components/StidDocument/StidDocument.tsx
src/apps/ScopeChangeRequest/Components/StidDocument/stidDocument.styles.ts
src/apps/ScopeChangeRequest/api/Search/PCS/searchTags.ts
src/apps/ScopeChangeRequest/hooks/queries/useUnpackRelatedObjects.ts

[Scope change] Small visual fixes

---

src/apps/ScopeChangeRequest/functions/FAM/generateFAMRequest.ts
src/apps/ScopeChangeRequest/types/FAM/famQuery.ts

[Scope change] Prepare for fam migration

---

src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTab.tsx
src/apps/ScopeChangeRequest/Components/WorkOrderTable/WorkOrderTable.tsx
src/apps/ScopeChangeRequest/api/FAM/getWorkOrderById.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

Completes:
[AB#211075](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211075)

[Scope change] Fix workorder link

---

src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestForm.tsx

Completes:
[AB#212723](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/212723)

[Scope change] add warning dialog to create

---

Changelog.md
package.json

[Release] Add changelog and bump version

---

src/Core/Assignments/Components/AssignmentsCard.tsx
src/Core/Assignments/Hooks/useAssignments.ts
src/Core/Assignments/Types/assignment.ts

Remove all the assignments that are closed
Completes:
[AB#212820](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/212820)

[Assignments] Filter closed assignments

---

src/components/Menu/Components/CompactMenu/CompactMenu.tsx
src/components/Menu/Components/Favourites/FavouritesStyles.ts
src/components/Menu/Components/GroupeItem/GroupeItem.tsx
src/components/TopBar/TopBar.tsx

menu icon and favorites not according to design
Completes: [AB#213442](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/213442)
[AB#207812](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/207812)

[Portal] - bug/menu icon and favorites not according to design

---

src/apps/ScopeChangeRequest/Components/WorkOrderTable/Utils/generateColumn.ts
src/apps/ScopeChangeRequest/Components/WorkOrderTable/WorkOrderTable.tsx

[Scope change] WO refactor

---

src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx
src/apps/ScopeChangeRequest/workspaceConfig/filter/filterConfig.ts
src/apps/ScopeChangeRequest/workspaceConfig/filter/guesstimate/guesstimate.ts

Completes:
[AB#212755](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/212755)

[Scope change] Added guesstimate filter

---

src/apps/ScopeChangeRequest/Components/AdvancedDocumentSearch/AdvancedDocumentSearch.tsx
src/apps/ScopeChangeRequest/Components/AdvancedDocumentSearch/advancedSearch.styles.ts
src/apps/ScopeChangeRequest/Components/SearchReferences/SearchReferences.tsx

Completes:
[AB#213825](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/213825)

[Scope change] Removed required meta tag

---

src/apps/ScopeChangeRequest/workspaceConfig/sGarden/gardenConfig.ts

Completes:
[AB#209437](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/209437)

[Scope change] Garden sort workflow status

---

src/apps/ScopeChangeRequest/Components/AdvancedDocumentSearch/AdvancedDocumentSearch.tsx
src/apps/ScopeChangeRequest/Components/SearchReferences/SearchReferences.tsx

Completes: 
[AB#213877](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/213877)

[Scope change] Remove discipline from references

---

src/packages/Filter/Components/FilterView/FilterTypes.tsx
src/packages/Filter/Components/FilterView/FilterView-style.ts

Completes: 
[AB#212317](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/212317)

[Workspace] Added reset filter

---

src/apps/ScopeChangeRequest/Components/Inputs/FormTextField.tsx

Completes:
[AB#212843](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/212843)

[Scope change] bigger description field

---

src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx
src/Core/WorkSpace/src/Components/Presets/Presets.tsx
src/Core/WorkSpace/src/Tabs/GardenTab.tsx
src/Core/WorkSpace/src/Util/gardenBookmarks/gardenApiAtom.ts
src/Core/WorkSpace/src/Util/gardenBookmarks/gardenStateSnapshotAtom.ts
src/Core/WorkSpace/src/Util/gardenBookmarks/generateGardenSnapshot.ts
src/Core/WorkSpace/src/Util/gardenBookmarks/interceptGardenOptions.ts
src/Core/WorkSpace/src/WorkSpaceApi/WorkSpaceTypes.ts
src/Core/WorkSpace/src/WorkSpaceApi/workspaceApi.ts
src/Core/WorkSpace/src/WorkSpaceApi/workspaceState.ts
src/apps/DisciplineReleaseControl/Components/Garden/gardenSetup.ts
src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx
src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx
src/components/ParkView/Components/Garden.tsx
src/components/ParkView/Components/GardenView.tsx
src/components/ParkView/Components/VirtualGarden/Container.tsx
src/components/ParkView/Models/gardenApi.ts
src/components/ParkView/hooks/useGardenApi.ts

[Workspace] PoC garden presets

---

src/apps/ScopeChangeRequest/Components/Form/BaseForm/ScopeChangeBaseForm.tsx
src/apps/ScopeChangeRequest/Components/Form/Origin.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestForm.tsx

Completes: 
[AB#207143](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/207143)

[Scope change] add DCR field as origin

---

src/Core/Assignments/Components/AssignmentsTab.tsx

[Assignments] No tasks message

---

src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/AddContributor.tsx
src/apps/ScopeChangeRequest/api/ScopeChange/Workflow/addContributor.ts

[Scope change] Refactor contributor mutation

---

src/apps/ScopeChangeRequest/Components/Inputs/Origins/SelectPunch.tsx
src/apps/ScopeChangeRequest/api/PCS/validatePunch.ts

Benefits:
Cleaner code.
Will cancel previous API calls automatically
Will actually differ between failing to reach the api and api saying the punch list doesnt exist

[Scope change] Refactor punch validation

---

src/Core/Client/Functions/Readers.ts
src/Core/Client/Service/createClient.ts
src/Core/Client/Service/setupContext.ts
src/Core/Client/Types/ScopeAndUrls.ts
src/apps/Handover/index.tsx
src/apps/WorkOrder/index.tsx
src/apps/swcr/index.ts

Completes: [AB#214146](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/214146)

[Portal] - using the fusion context

---

src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/Criteria.tsx

[Scope change] Hide contributors on old steps

---

src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTab.tsx
src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts

[Scope change] Prepare for wo's

---

src/AppClient.tsx
src/Core/Client/ClientLoad/ClientFailed.tsx
src/Core/Client/ClientLoad/ClientLoading.tsx
src/Core/Client/ClientLoad/client.styles.ts
src/Core/Client/Service/createClient.ts
src/Core/Client/Service/setupContext.ts
src/Core/Client/styleProvider.ts
src/index.tsx

[Portal] fix failing fusion contexts api call breaking portal load

---

src/Core/WorkSpace/src/Components/Presets/Presets.tsx

[Workspace] Fix EDS Chip z-index

---

src/packages/Filter/Components/FilterView/FilterTypes.tsx
src/packages/Filter/Components/FilterView/FilterView.tsx
src/packages/Filter/Hooks/useFilterApi.ts

Completes: 
[AB#214277](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/214277)

[Workspace] Clear filter on hide 

---

src/Core/Client/Service/appConfig.ts
src/Core/Client/Service/createClient.ts
src/Core/Client/Service/envConfig.ts
src/index.tsx
src/packages/authentication/src/useAuthenticate.ts

[Fix] Portal login at start

---

src/Core/Client/Service/ClientBuilder.ts
src/Core/Client/Service/createClient.ts
src/Core/Client/Service/setupApps.ts
src/Core/Client/Types/App.ts
src/Core/PowerBiViewer/src/PowerBiViewer.tsx
src/Core/PowerBiViewer/src/Types/State.ts
src/apps/Installation/index.ts
src/apps/PowerBI/BusinessCaseReport.tsx
src/apps/PowerBI/LCIReport.tsx
src/apps/PowerBI/SafetyPerformanceReport.tsx
src/components/Routes/ComponentWrapper.tsx
src/components/Routes/Routes.tsx

Fixed context and added new installation report
Completes: [AB#215184](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/215184) [AB#215186](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/215186)

[PBI] - Fixed context and added new installation report

---

Changelog.md
package.json

Changelog 1.1.3

---

Changelog.md
package.json
src/Core/Client/Service/ClientBuilder.ts
src/Core/Client/Service/appConfig.ts
src/Core/Client/Service/createClient.ts
src/Core/Client/Service/envConfig.ts
src/Core/Client/Service/setupApps.ts
src/Core/Client/Types/App.ts
src/Core/PowerBiViewer/src/PowerBiViewer.tsx
src/Core/PowerBiViewer/src/Types/State.ts
src/apps/Installation/index.ts
src/apps/PowerBI/BusinessCaseReport.tsx
src/apps/PowerBI/LCIReport.tsx
src/apps/PowerBI/SafetyPerformanceReport.tsx
src/components/Routes/ComponentWrapper.tsx
src/components/Routes/Routes.tsx
src/index.tsx
src/packages/authentication/src/useAuthenticate.ts

- [Client] Hotfix auth issue
- [Installation] new report in devlopment
- [LCI Hanging Garden]  Context in report
- [Business Case] Contexts report
- [Safety Performance] Contexts report

Release Castberg Project Portal v1.1.3

---

src/apps/DisciplineReleaseControl/Components/Electro/Components/HeatTracingCable.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/Line.tsx
src/apps/DisciplineReleaseControl/Components/Electro/ElectroNode.tsx
src/apps/DisciplineReleaseControl/Components/Electro/ElectroView.tsx
src/apps/DisciplineReleaseControl/Components/Electro/electroViewHelpers.ts
src/apps/DisciplineReleaseControl/Components/Electro/styles.ts
src/apps/DisciplineReleaseControl/Components/Garden/GardenItemStyles.ts
src/apps/DisciplineReleaseControl/Components/Garden/ReleaseControlGardenGroupView.tsx
src/apps/DisciplineReleaseControl/Components/Garden/ReleaseControlGardenItem.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlHTSidesheet.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlSidesheet.tsx
src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx
src/apps/DisciplineReleaseControl/Types/pipetest.ts
src/components/ParkView/Components/VirtualGarden/GardenItemContainer.tsx
src/components/ParkView/Models/gardenOptions.ts
src/components/ParkView/index.ts
src/packages/Filter/index.ts

Completes: [AB#201224](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/201224)

HT sidesheet and garden custom group view for HT

---

src/Core/Client/Service/appsProvider.ts
src/Core/Client/Types/AppManifest.ts
src/Core/PowerBiViewer/src/Api/powerBiViewerApi.ts
src/Core/PowerBiViewer/src/Components/PowerBiViewerHeader/PowerBiViewerHeader.tsx
src/Core/PowerBiViewer/src/Types/State.ts
src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx
src/apps/apps.ts
src/components/Routes/Routes.tsx

[App manifest] - chore: change group type to be string

---

src/Core/PowerBiViewer/src/Api/powerBiViewerApi.ts

[PowerBIViewer] - hotfix: undefined check on group

---

src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlSidesheet.tsx

Completes: AB#[214266](https://dev.azure.com/Equinor/Johan%20Castberg%20-%20Portal/_workitems/edit/214266)

Keep insulation warning pinned and not scrollable

---

src/apps/DisciplineReleaseControl/Components/Sidesheet/workOrderTab.styles.ts

Completes: [AB#214258](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/214258)

Scrollbars in workorder tab

---

src/packages/BookmarksManager/src/components/BookmarkDropdown/BookmarkList.tsx

[Bookmarks Manager] - fix: check for bookmarks length

---

src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestForm.tsx

[Scope change] Only send valid guesstimates

---

src/apps/ScopeChangeRequest/Components/Form/ScopeChangeForm.styles.ts

 [Scope change] Fix styling form

---

src/apps/ScopeChangeRequest/workspaceConfig/filter/filterConfig.ts

[Scope change] Add disciplines filter

---

src/apps/MechanicalCompletion/utils/config/tableConfig.tsx
src/packages/Table/Components/Cells/DescriptionCell.tsx

Completes: [AB#216022](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/216022)

[MC Garden] - chore: first version table config

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/WorkflowCompact.tsx

Completes:
[AB#210763](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/210763)

[Scope change] Add popover to workflow step

---

src/Core/Atom/example.md
src/Core/Atom/functions/createAtom.ts
src/Core/Atom/index.ts
src/Core/Atom/types/atom.ts
tsconfig.json
vite.config.ts

[Portal] Atom wrapper

---

src/Core/WorkSpace/src/Components/WorkSpace/WorkSpaceViewStyles.ts
src/Core/WorkSpace/src/Tabs/GardenTab.tsx
src/components/ParkView/Components/VirtualGarden/styles/Container.styles.ts

[Workspace & Garden] - fix: scroll  in garden when filter is open

---

src/apps/MechanicalCompletion/components/StatusFilter/HandoverStatusFilter.tsx
src/apps/MechanicalCompletion/components/StatusFilter/McStatusFilter.tsx
src/apps/MechanicalCompletion/components/StatusFilter/StatusFilter.styles.ts
src/apps/MechanicalCompletion/components/StatusFilter/index.ts
src/apps/MechanicalCompletion/components/index.ts
src/apps/MechanicalCompletion/index.ts
src/apps/MechanicalCompletion/utils/config/filterConfig.tsx
src/apps/MechanicalCompletion/utils/helpers/index.ts
src/apps/MechanicalCompletion/utils/helpers/mcStatusPriority.ts

Completes: [AB#215746](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/215746)

[MC Garden] - chore: mc garden filter

---

src/apps/apps.ts

[Apps] - chore: change env for Mc Garden to test

---

src/apps/MechanicalCompletion/utils/config/gardenSetup.ts

[Mechanical Completion] - chore: change default group by to rfcc

---

src/components/ParkView/Styles/common.ts

[Garden] - fix: scroll in normal garden

---

src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx

[Workspace] - fix: double bookmarks in pbi in workspace

---

src/apps/Installation/index.ts

removed old configuration making new configuration ready for production
Completes: [AB#216910](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/216910)

[Installation]- new report config

---

src/apps/DisciplineReleaseControl/Components/Garden/gardenFunctions.ts
src/apps/DisciplineReleaseControl/Components/Garden/gardenSetup.ts
src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx
src/apps/DisciplineReleaseControl/Functions/statusHelpers.ts
src/apps/DisciplineReleaseControl/Types/pipetest.ts

Completes: [AB#214851](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/214851)

Step name filter (steps included in pipetest)

---

src/apps/Installation/index.ts

[HotFix] -changes installation configuration to one report config

---

src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RequestTab.tsx

[Scope change] Indent checkbox

---

src/apps/DisciplineReleaseControl/Components/Electro/Components/Cable.tsx
src/apps/DisciplineReleaseControl/Components/Electro/ElectroNode.tsx
src/apps/DisciplineReleaseControl/Types/eleNetwork.ts

Completes: [AB#217128](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/217128)

Added 'ghost cable' to display junction box correctly if it has no cable

---

src/apps/ScopeChangeRequest/Atoms/FormAtomApi/formAtomApi.ts
src/apps/ScopeChangeRequest/Components/DataCreator/DataCreatorWrapper.tsx
src/apps/ScopeChangeRequest/Components/Form/Inputs/PhaseSelect/PhaseSelect.tsx
src/apps/ScopeChangeRequest/Components/Form/Inputs/ScopeSelect/ScopeSelect.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
src/apps/ScopeChangeRequest/hooks/queries/useUnpackRelatedObjects.ts
src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts

[Scope change] Fix clear form state

---

src/Core/WorkSpace/src/Context/BookmarkContext.tsx
src/Core/WorkSpace/src/Context/ViewProvider.tsx
src/Core/WorkSpace/src/Tabs/PowerBiTab.tsx
src/modules/powerBI/src/Components/Filter/PowerBIFilter.tsx

[Workspace] - fix: pass bookmark option to pbi

---

Changelog.md
package.json

[Changelog] - Release/1.2.0

---

src/Core/WorkSpace/src/Context/ViewProvider.tsx

[Workspace] - fix: change parameter name to correct attribute for pbi bookmark

---

src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx

Completes: [AB#217504](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/217504)

Removed some filters from being default active in piping and heat trace

---

src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx

Completes: [AB#217511](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/217511)

Renamed quick grouping/filter buttons in piping and heat trace

---

src/apps/DisciplineReleaseControl/Atoms/formAtomApi.ts
src/apps/DisciplineReleaseControl/Components/Factory/FactoryComponent.tsx
src/apps/DisciplineReleaseControl/Components/Form/ReleaseControlProcessForm.tsx
src/apps/DisciplineReleaseControl/Components/Form/releaseControlProcessForm.styles.ts
src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx
src/apps/ScopeChangeRequest/Components/Form/Inputs/ScopeChangeReferences/ScopeChangeReferences.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestForm.tsx
src/apps/ScopeChangeRequest/Components/SearchReferences/SearchReferences.tsx

[Discipline release control] Create DRC

---

src/apps/ScopeChangeRequest/workspaceConfig/filter/filterConfig.ts

Completes: 
[AB#217790](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/217790)
[AB#217785](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/217785)

[Scope change] Add filters, scope, warranty case

---

src/packages/Table/Components/Cells/YearWeekCell.tsx

[Table] - chore: add prefix 0 to weeknumber if less than 10

---

src/apps/MechanicalCompletion/utils/config/filterConfig.tsx

Completes: [AB#218004](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/218004)

[Mechanical Completion] - chore: change order of filter and hide area

---

src/apps/MechanicalCompletion/utils/config/filterConfig.tsx

Completes: [AB#218008](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/218008)

[Mechanical Completion] - fix: rename from m03 m04

---

src/apps/MechanicalCompletion/utils/config/gardenSetup.ts

Completes: [AB#218006](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/218006)

[Mechanical Completion] - chore: changed to forecast and rfcmc

---

src/apps/Handover/index.tsx

[Handover] - chore: initial grouping set to forecast

---

src/apps/ScopeChangeRequest/Components/Form/Inputs/OriginSourceSelect/OriginSourceSelect.tsx

Completes: 
[AB#217793](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/217793)

[Scope change] Fix origin source not showing initial value

---

src/apps/DisciplineReleaseControl/Components/Form/Inputs/Description/Description.tsx
src/apps/DisciplineReleaseControl/Components/Form/Inputs/PlannedStartDate/PlannedStartDate.tsx
src/apps/DisciplineReleaseControl/Components/Form/Inputs/References/References.tsx
src/apps/DisciplineReleaseControl/Components/Form/Inputs/Title/Title.tsx
src/apps/DisciplineReleaseControl/Components/Form/Inputs/index.ts
src/apps/DisciplineReleaseControl/Components/Form/ReleaseControlProcessForm.tsx

[DRC] Refactor create form

---

src/apps/ScopeChangeRequest/Components/DataCreator/DataCreatorWrapper.tsx
src/apps/ScopeChangeRequest/Components/Form/Inputs/IsWarrantyCheckbox/IsWarrantyCheckbox.tsx
src/apps/ScopeChangeRequest/Components/Form/Inputs/MaterialsInput/MaterialsInput.tsx
src/apps/ScopeChangeRequest/Components/Form/Inputs/OriginIdPicker/OriginIdPicker.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestForm.tsx
src/apps/ScopeChangeRequest/Components/Form/StyledCheckbox/StyledCheckbox.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RequestTab.tsx
src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts
src/components/JSXSwitch/Components/Case.tsx
src/components/JSXSwitch/Components/Switch.tsx
src/components/JSXSwitch/index.ts
tsconfig.json
vite.config.ts

Completes:
[AB#215212](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/215212)

[Scope change] Added materials checkboxes

---

src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx
src/components/ParkView/Components/GardenView.tsx
src/components/ParkView/Components/VirtualGarden/Container.tsx
src/components/ParkView/Models/gardenOptions.ts
src/components/ParkView/Utils/groupBy.ts

[Workspace] Add default collapsed on garden

---

Changelog.md
package.json

[Changelog] Add to changelog

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[Scope change] Move column

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[Scope change] Refactor table config

---

src/apps/ScopeChangeRequest/Atoms/FormAtomApi/formAtomApi.ts

Completes: 
[AB#218449](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/218449)

[Scope change] Clear atom state

---

src/apps/ScopeChangeRequest/hooks/React-Query/useScopechangeMutation.ts

[Scope change] Disable retries on mutations

---

src/apps/ScopeChangeRequest/Components/DataCreator/DataCreatorWrapper.tsx
src/packages/Sidesheet/Components/ResizableSidesheet.tsx
src/packages/Sidesheet/Functions/openSidesheet.ts
src/packages/Sidesheet/Hooks/useInternalSidesheetFunction.tsx
src/packages/Sidesheet/State/sidesheetState.ts
src/packages/Sidesheet/Types/SidesheetApi.ts
src/packages/Sidesheet/context/sidesheetContext.ts

Completes: 
[AB#218409](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/218409)

[Sidesheet] Confirmation dialog when switching sidesheets while having unsaved changes

---

src/apps/swcr/utilities/gardenSetup.ts
src/apps/swcr/utilities/sortFunctions.ts

[SWCR] - fix: sort date columns

---

src/apps/WorkOrder/Garden/utility/getSubtitleHeader.ts
src/packages/GardenUtils/src/dateUtils.ts

Completes: [AB#212403](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/212403)

[Workorder] - fix: remaining hours on current week

---

src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetStatuses/McStatusCell.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetStatuses/RfccStatusCell.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetStatuses/RfocStatusCell.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetStatuses/WorkerOrderStatusCell.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/McPackagesTab.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/NcrTab.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/PunchTab.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/QueryTab.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/SwcrTab.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/UnsignedActionTab.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/UnsignedTasksTab.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/WorkOrdersTab.tsx
src/apps/MechanicalCompletion/components/McSidesheet/Tabs/NcrTab.tsx
src/apps/MechanicalCompletion/components/McSidesheet/Tabs/PunchTab.tsx
src/apps/MechanicalCompletion/components/McSidesheet/Tabs/WorkordersTab.tsx
src/apps/WorkOrder/Garden/components/WorkOrderSidesheet/Tabs/Cells/AvailableItemCell.tsx
src/apps/WorkOrder/Garden/components/WorkOrderSidesheet/Tabs/MccrTab.tsx
src/packages/GardenUtils/src/components/cells/CellWithLink.tsx
src/packages/GardenUtils/src/components/sidesheet/TabTable.tsx
src/packages/Table/Utils/utils.tsx
src/packages/Table/types.ts

Completes: [AB#213441](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/213441)

[Table] - fix: sort by number

---

src/apps/ReleaseControl/ReleaseControlApp.tsx
src/apps/ReleaseControl/workspaceConfig/dataOptions.ts
src/apps/ReleaseControl/workspaceConfig/filter/filterConfig.ts
src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts
src/apps/apps.ts

[RC] Release control initial release

---

src/apps/Handover/Garden/CustomViews/HandoverGardenItem/HandoverGardenItem.tsx
src/apps/Handover/Garden/components/HandoverItemPopover/index.tsx
src/components/ParkView/Components/VirtualGarden/GardenItemContainer.tsx
src/components/ParkView/Components/VirtualGarden/Layout.tsx
src/components/ParkView/Components/VirtualGarden/VirtualGarden.tsx
src/components/ParkView/Models/gardenOptions.ts
src/packages/GardenUtils/src/components/index.ts
src/packages/GardenUtils/src/components/popover/PopoverWrapper.tsx

[GardenUtils & Handover] - feat: popover in virtual garden

---

src/apps/MechanicalCompletion/utils/config/gardenSetup.ts
src/apps/MechanicalCompletion/utils/config/tableConfig.tsx

Completes: [AB#219421](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/219421)

[Mechanical Completion] - chore: use planned instead of forecast

---

src/apps/WorkOrder/Garden/utility/index.ts
src/apps/WorkOrder/components/FollowUpStatusFilter.tsx
src/apps/WorkOrder/components/index.ts
src/apps/WorkOrder/utility/filterConfig.tsx

Completes: [AB#211142](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211142)

[Workorder] - feat: follow up status filter

---

src/apps/Handover/Garden/CustomViews/HandoverGardenItem/HandoverGardenItem.tsx
src/apps/Handover/Garden/components/HandoverItemPopover/index.tsx
src/apps/Handover/Garden/components/HandoverItemPopover/styles.tsx
src/apps/MechanicalCompletion/components/CustomItemView/CustomItemView.tsx
src/apps/MechanicalCompletion/components/Popover/PopoverContent.styles.ts
src/apps/MechanicalCompletion/components/Popover/PopoverContent.tsx
src/apps/WorkOrder/Garden/components/Popover/WorkOrderPopover.tsx
src/apps/WorkOrder/Garden/components/WorkOrderItem/WorkOrderItem.tsx
src/packages/GardenUtils/src/components/popover/PopoverProgressBar.ts

Completes: [AB#203853](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/203853)
Completes: [AB#202235](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/202235)

[MC, WO, Handover] - feat: popover for mc, wo, handover

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

Completes: [AB#209421](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/209421)

[Scope change] Disciplines in table

---

Changelog.md
package.json

[Changelog] - Release 1.3.0

---

Changelog.md
package.json

[Changelog] Changelog 1.3.1 bugfix

---

src/modules/powerBI/src/Components/Filter/FilterGroup/FilterGroup.tsx
src/modules/powerBI/src/Components/Filter/PowerBIFilter.tsx

[PowerBI] - fix: use keys in useeffect and sort filter group

---

src/apps/Handover/Garden/CustomViews/HandoverGardenItem/HandoverGardenItem.tsx
src/apps/MechanicalCompletion/components/CustomItemView/CustomItemView.tsx
src/apps/WorkOrder/Garden/components/WorkOrderItem/WorkOrderItem.tsx

Completes: [AB#219796](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/219796)

[MC & Handover & WO] - fix: popover stuck

---

src/modules/powerBI/src/Components/Filter/FilterItems/FilterItems.tsx
src/modules/powerBI/src/Components/Filter/FilterItems/Item.tsx
src/modules/powerBI/src/Components/Filter/PowerBIFilter.tsx
src/modules/powerBI/src/Types/filter.ts
src/modules/powerBI/src/Utils/constants.ts
src/modules/powerBI/src/Utils/filterSelectionUtils.ts
src/modules/powerBI/src/Utils/getActiveFilterGroups.ts
src/modules/powerBI/src/Utils/getFilters.ts
src/modules/powerBI/src/Utils/index.ts
src/modules/powerBI/src/Utils/transformData.ts

[PowerBI] - fix: use basic filter to deal with limitation of condition

---

src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx

[Workspace] Create button styling

---

src/apps/ScopeChangeRequest/hooks/sidesheet/useSidesheetEffects.tsx

[Scope change] Sticky menu items

---

src/modules/powerBI/src/Components/Filter/FilterItems/FilterItems.tsx

[PowerBI] - fix: memo checked for select all

---

src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx
src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx

[PowerBI] Add powerbi to scope change

---

Changelog.md
package.json

[Test] Release 1.4.0

---

src/components/TopBar/DevBar/DevBar.tsx

Lets you easily identify which version the different environments are running

[Portal] Add version to banner

---

src/components/TopBar/BreadCrumbs/Breadcrumbs.tsx
src/components/TopBar/TopBar.tsx
src/components/TopBar/TopBarStyle.ts

Completes:
[AB#200562](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/200562)

[Portal] Navigation breadcrumbs

---

src/apps/MechanicalCompletion/utils/config/tableConfig.tsx

[MC] - chore: rename table headers

---

src/apps/Handover/utility/config/tableConfig.tsx

[Handover] - chore: rename table header

---

src/apps/WorkOrder/components/EstimateBar.tsx
src/apps/WorkOrder/components/ExpendedProgressBar.tsx
src/apps/WorkOrder/components/ProgressBarContainer.styles.ts
src/apps/WorkOrder/components/index.ts
src/apps/WorkOrder/utility/tableConfig.tsx

Completes: [AB#205778](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/205778)

[Workorder] - feat: databars on hours in table

---

src/apps/Handover/Garden/CustomViews/HandoverGardenItem/GardenItemStyles.ts
src/apps/Handover/Garden/CustomViews/HandoverGardenItem/HandoverGardenItem.tsx
src/apps/Handover/Garden/components/Icons/WarningIcon.tsx

Completes: [AB#183842](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/183842)

[Handover] - feat: show warning icon if os and rfcc accepted

---

src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSideSheet.tsx

Very simple scroll into view for tabs, should update EDS since they should have a fix for this in the component itself.

[Handover] - quickfix: tabs scroll into view when clicked

---

src/apps/ScopeChangeRequest/Components/Attachments/RequestAttachmentsList/RequestAttachmentsList.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeForm.styles.ts

[Scope change] Edit mode attachments styling fix

---

src/components/TopBar/BreadCrumbs/Breadcrumbs.tsx

[Portal] Location breadcrumbs show group name for group view

---

src/components/Menu/Components/MenuItem/MenuItem.tsx

[Portal] Hide disabled menu items

---

src/Core/WorkSpace/src/Icons/Help.tsx
src/Core/WorkSpace/src/Tabs/HelpPageTab.tsx
src/Core/WorkSpace/src/Util/tabsConfig.ts
src/Core/WorkSpace/src/WorkSpaceApi/WorkSpaceTypes.ts
src/Core/WorkSpace/src/WorkSpaceApi/workspaceApi.ts
src/Core/WorkSpace/src/WorkSpaceApi/workspaceState.ts
src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx

[Workspace] Help page tab

---

src/apps/ScopeChangeRequest/workspaceConfig/sGarden/gardenConfig.ts
src/components/ParkView/Components/VirtualGarden/DefaultGardenItem.tsx
src/components/ParkView/Components/VirtualGarden/GardenItemContainer.tsx
src/components/ParkView/Components/VirtualGarden/styles/Package.styles.ts
src/components/ParkView/Context/ParkViewProvider.tsx
src/components/ParkView/Models/gardenOptions.ts

[Workspace] Default garden color function

---

src/apps/Tasks/TasksApp.tsx
src/apps/apps.ts

[Tasks] Workspace

---

packages/echo3dViewer/src/services/echo3dBaseSelectionHandler.ts
src/packages/ModelViewer/ModelViewer.tsx
src/packages/ModelViewer/ModelViewerStyles.ts
src/packages/ModelViewer/components/selectionMenu.tsx
src/packages/ModelViewer/context/modelViewerContext.tsx
src/packages/ModelViewer/icons/ElectroIcon.tsx
src/packages/ModelViewer/types/plants.ts

Possibility to turn on/off the rest of the 3D model
Completes: [AB#214098](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/214098)

feature/Possibility to turn on/off the rest of the 3D model

---

Changelog.md
package.json

Changelog 1.4.2

---

src/Core/Client/Service/createClient.ts
src/FusionModules/DataCreatorModule/provider.ts

[Fix] access checks blocking portal load

---

src/packages/Table/Components/GoupedCell.tsx
src/packages/Table/Types/types.ts

[Table] - fix: stop propagation on expand click

---

src/apps/apps.ts

[Mechanical Completion] - chore: change mc to prod env

---

src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx

[Workspace] Fix creator title

---

Changelog.md
package.json

Changelog 1.4.3

---

src/apps/ScopeChangeRequest/Components/AdvancedDocumentSearch/AdvancedDocumentSearch.tsx

[Scope change] Placeholder text missing

---

src/apps/ScopeChangeRequest/Components/Form/Inputs/DescriptionInput/DescriptionInput.tsx

[Scope change] Growing description field

---

Changelog.md
package.json
src/Core/Client/Service/createClient.ts
src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx
src/Core/WorkSpace/src/Components/ToggleButton.tsx
src/FusionModules/DataCreatorModule/provider.ts
src/apps/ScopeChangeRequest/Components/AdvancedDocumentSearch/AdvancedDocumentSearch.tsx
src/apps/ScopeChangeRequest/Components/Form/Inputs/DescriptionInput/DescriptionInput.tsx
src/apps/ScopeChangeRequest/api/PCS/getAreaByCode.ts
src/apps/ScopeChangeRequest/api/PCS/getCommPkgById.ts
src/apps/ScopeChangeRequest/api/PCS/getDisciplines.ts
src/apps/ScopeChangeRequest/api/PCS/getFunctionalRoles.ts
src/apps/ScopeChangeRequest/api/PCS/getSystems.ts
src/apps/ScopeChangeRequest/api/PCS/getTagById.ts
src/apps/ScopeChangeRequest/keys/ProCoSysQueries.ts
src/apps/apps.ts
src/components/ParkView/Components/VirtualGarden/styles/Container.styles.ts
src/packages/Table/Components/GoupedCell.tsx
src/packages/Table/Types/types.ts

Castberg Release 1.4.3

---

src/Core/WorkSpace/src/Tabs/GardenTab.tsx
src/components/ParkView/Components/VirtualGarden/styles/Container.styles.ts

[Garden] Fix scroll in garden

---

src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx

[Scope change] PowerBI dev fix

---

src/apps/MechanicalCompletion/index.ts

Completes: [AB#215725](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/215725)

[Mechanical Completion] - chore: analytics config for mc

---

Changelog.md
package.json

[Changelog] - Release 1.4.4

---

Changelog.md
package.json
src/Core/WorkSpace/src/Tabs/GardenTab.tsx
src/apps/MechanicalCompletion/index.ts
src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx
src/components/ParkView/Components/VirtualGarden/styles/Container.styles.ts

Release Castberg project portal v1.4.4

---

src/apps/MechanicalCompletion/index.ts

[MC] - chore: prod check for pbi mc

---

Changelog.md
package.json

[Changelog] - Release 1.4.5

---

src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/Criteria.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Workflow.tsx
src/apps/ScopeChangeRequest/hooks/mutations/useWorkflowSigning.tsx
src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx
src/apps/ScopeChangeRequest/workspaceConfig/statusBarConfig.ts
src/packages/Filter/__tests__/doesItemPass.test.ts

[Scope change] filter crashing table

---

src/apps/ScopeChangeRequest/api/PCS/Batch/getAllTagsFromMcPkg.ts
src/apps/ScopeChangeRequest/api/PCS/getTagById.ts

[Scope change] Lookup tags from mc pkg

---

src/apps/DisciplineReleaseControl/Components/Garden/gardenSetup.ts
src/apps/DisciplineReleaseControl/Functions/statusHelpers.ts
src/apps/DisciplineReleaseControl/Types/pipetest.ts
src/apps/DisciplineReleaseControl/WorkspaceConfig/Table/tableConfig.tsx

Completes: [AB#222033](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/222033)

Group by new HT cable RFC instead of earliest pipetest RFC

---

src/apps/Checklist/index.ts
src/apps/PowerBI/QueryReport.tsx
src/apps/PowerBI/index.ts
src/apps/Query/index.ts
src/apps/apps.ts

[Checklist & Query] - chore: add pages to query and checklist

---

src/Core/PowerBiViewer/src/Components/PowerBiViewerHeader/PowerBiViewerHeader.tsx
src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx

[Workspace & PBI Viewer] - chore: remove prod check for bookmark dropdown

---

src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTab.tsx
src/apps/ScopeChangeRequest/api/FAM/getWorkOrderById.ts

[Scope change] Hotfix prod

---

Changelog.md
package.json

[Changelog] Release 1.4.6

---

src/apps/ScopeChangeRequest/hooks/sidesheet/useSidesheetEffects.tsx

[Scope change] Small UI tweaks

---

src/Core/WorkSpace/src/Tabs/ListTab.tsx
src/packages/Table/Components/Table.tsx
src/packages/Table/Components/TableConfigBar/ColumnPicker/ColumnPicker.tsx
src/packages/Table/Components/TableConfigBar/ColumnPicker/columnPicker.styles.ts
src/packages/Table/Components/TableConfigBar/TableConfigBar.tsx
src/packages/Table/Hooks/useColumns.ts

[Table] Added column picker

---

src/apps/ScopeChangeRequest/Components/DetailView/References.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Area/Area.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/CommPkg/CommPkg.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Discipline/Discipline.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Systems/System.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Tags/Tag.tsx
src/apps/ScopeChangeRequest/Components/StidDocument/StidDocument.tsx

[Scope change] New design references

---

src/apps/ScopeChangeRequest/Atoms/FormAtomApi/formAtomApi.ts
src/apps/ScopeChangeRequest/Components/DetailView/References.tsx
src/apps/ScopeChangeRequest/Components/SearchReferences/SearchReferences.tsx
src/apps/ScopeChangeRequest/api/ScopeChange/Request/initiateScopeChange.ts
src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[Scope change] Punch as reference

---

src/apps/ScopeChangeRequest/workspaceConfig/statusBarConfig.ts

[Scope change] Fix KPI approved count

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[Scope change] Fix custom columns breaking on group

---

src/Core/WorkSpace/src/Tabs/ListTab.tsx

[Workspace] Fix column picker resetting

---

src/apps/Handover/utility/config/filterSetup.ts

Completes: [AB#223131](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/223131)

[Handover] - chore: Comm status filter

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[Scope change] fix sorting on mhrs columns

---

src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx

[Scope change] update page id PBI

---

src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlSidesheet.tsx

Remove 3D to fix error?

---

src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlSidesheet.tsx

Remove 3D to fix prod sidesheet

---

Changelog.md
package.json

Changelog 1.4.8

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[Scope change] Fix sorting on category, scope, state

---

Changelog.md
package.json

Changelog 1.4.9

---

src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlSidesheet.tsx

[HT-PipeTest] - Change tab title to 3d

---

src/Core/WorkSpace/src/Components/DataViewerHeader/CreatorButton/CreatorButton.tsx
src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx
src/Core/WorkSpace/src/Components/DataViewerHeader/HeaderStyles.ts
src/Core/WorkSpace/src/Components/DataViewerHeader/HeaderTabButtons/HeaderTabButtons.tsx
src/Core/WorkSpace/src/Components/DataViewerHeader/PowerBIPages/PowerBIPages.tsx
src/Core/WorkSpace/src/Components/DataViewerHeader/PowerBiHeader.tsx
src/Core/WorkSpace/src/Components/DataViewerHeader/RefreshButton/RefreshButton.tsx
src/Core/WorkSpace/src/Components/DataViewerHeader/WorkspaceHeader.tsx
src/Core/WorkSpace/src/Components/Search/Search.tsx
src/apps/Handover/index.tsx
src/apps/ReleaseControl/hooks/useSidesheetEffects.tsx
src/components/OverlayMenu/src/components/ButtonMenu/ButtonMenu.tsx
src/components/OverlayMenu/src/components/IconMenu/IconMenu.tsx
src/components/OverlayMenu/src/types/menuItem.ts
src/packages/Sidesheet/Types/SidesheetApi.ts

[Workspace] Add search to workspace

---

src/apps/Loop/components/LoopGroupBySelect.tsx
src/apps/Loop/components/Sidesheet/Banner.tsx
src/apps/Loop/components/Sidesheet/BannerItem.tsx
src/apps/Loop/components/Sidesheet/LoopSidesheet.tsx
src/apps/Loop/components/index.ts
src/apps/Loop/index.tsx
src/apps/Loop/types/customGroupByKeys.ts
src/apps/Loop/types/index.ts
src/apps/Loop/types/loop.ts
src/apps/Loop/utility/config/filterConfig.ts
src/apps/Loop/utility/config/gardenConfig.ts
src/apps/Loop/utility/config/index.ts
src/apps/Loop/utility/config/sidesheetConfig.ts
src/apps/Loop/utility/config/tableConfig.ts
src/apps/Loop/utility/helpers/fam.ts
src/apps/Loop/utility/helpers/getGroupByKey.ts
src/apps/apps.ts
src/apps/functions.ts
src/apps/widgets.ts

[Loop] - feat: init loop app (only dev)

---

src/apps/ScopeChangeRequest/Components/ErrorBanner/ErrorBanner.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/hooks/queries/useGetScopeChangeRequest.ts

[Scope change] Clear errors on request change

---

src/apps/Loop/utility/config/gardenConfig.ts
src/apps/Loop/utility/helpers/getGroupByKey.ts

[Loop] - fix: null date check

---

src/apps/WorkOrder/Garden/components/Popover/WorkOrderPopover.tsx

[Workorder] - fix: popover mccr showing wrong status

---

Changelog.md
package.json
src/apps/apps.ts

Changelog 1.5.0 + release control test

---

src/apps/Construction/Components/SidesheetContent.tsx
src/apps/ReleaseControl/components/RelatedObjects/Tag.tsx
src/apps/ScopeChangeRequest/Components/DetailView/OriginLink.tsx
src/apps/ScopeChangeRequest/Components/DetailView/References.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/CommPkg/CommPkg.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Punch/Punch.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Systems/System.tsx
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/Tags/Tag.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RequestTab.tsx
src/apps/ScopeChangeRequest/Components/WorkOrderTable/CompactWorkOrder/CompactWorkOrder.tsx
src/apps/ScopeChangeRequest/Components/WorkOrderTable/WorkOrderTable.tsx
src/packages/ProCoSysUrls/procosysUrl.ts
tsconfig.json
vite.config.ts

[Portal] Central URL object for PCS

---

src/packages/Table/Components/Cells/StatusCell.tsx

[Table] - chore: redesign of status cell

---

src/apps/Loop/index.tsx

Completes: [AB#225237](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/225237)

[Loop] - chore: add analytics to loop

---

src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlSidesheet.tsx

3D nologer works beacuse of echo model loading change

fix/ 3D nologer works beacuse of echo model loading change

---

src/packages/BookmarksManager/src/hooks/useBookmarks.ts

[Bookmarks]- fix: use hook for saving bookmark to invalidate

---

src/packages/Table/Types/types.ts

[Table] - chore: better typing for custom column cell props
