equinor/lighthouse-client

src/apps/Commissioning/index.tsx, src/apps/Construction/index.tsx, src/apps/apps.ts
Updated the checklist analytics PBI report to use a report specific for JCA
Disabled some tabs for construction and commissioning app
Removed tabs are shown below
Construction 
1. SWCR analytics
2. LCI hanging garden
Comissioning
1. Work prep
2. LCI hanging
3. WO analytics
=> Updated checklist analytics and disabled some tabs

src/packages/Sidesheet/Components/PopoutSidesheet.tsx
When Sidesheet content is overflowing, add scrollbar to the sidesheet component wrapper.
=> fix: add scrollbar when overflow in sidesheet

src/packages/Table/Components/Cells/DateCell.tsx
DateCell component would show 1970 or something if string was empty. Will now show an empty string if the string passed to the component is empty.
=> [Table] - fix: DateCell component handles empty string value

src/apps/Construction/index.tsx
Critical status in construction progress means a workorder that has not reached W04 and it is 4 weeks or less until planned start date.
=> [Construction] - fix: change count in critical status kpi

src/apps/Construction/Components/DetailsPage/tableConfig.tsx, src/apps/Construction/Components/DetailsPage/utils.tsx
A commit from #120 made tsc super slow (adding type to this huge column config and using functions to return different object). 
Before:
Files:             1894
Lines:           373965
Nodes:           698977
Identifiers:     227992
Symbols:         387970
Types:           100351
Instantiations:  895822
Memory used:    427975K
I/O read:         0.16s
I/O write:        0.00s
Parse time:       3.76s
Bind time:        1.19s
Check time:      53.91s
Emit time:        0.00s
Total time:      58.86s
Now: 
Files:             1893
Lines:           373987
Nodes:           699772
Identifiers:     228276
Symbols:         388426
Types:           103230
Instantiations: …
=> fix: revert to older tableconfig

src/Core/WorkSpace/src/Tabs/ListTab.tsx, src/apps/HeatTraceInstallation/HeatTraceInstallationApp.tsx, src/packages/Table/Components/Styles.ts, src/packages/Table/Utils/ColumnDefault.tsx, src/packages/Table/Utils/columnGenerators.tsx, src/packages/Table/Utils/generateColumns.tsx, src/packages/Table/Utils/utils.tsx, src/packages/Table/types.ts
Custom column widths.
Table will always fill out 100% of available width on screen.
Completes: [AB#155003](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/155003)
=> Custom column widths + 100% table width

src/apps/Construction/Utils/formatNumber.ts, src/apps/Construction/Utils/index.ts, src/apps/Construction/index.tsx
Numbers should be shown as 5 000, 55 000 123 000 etc.. 
Move this functionality to KPI component?
Completes: [AB#186019](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/186019)
=> [Construction Progress] - chore: add number formatting

src/modules/powerBI/src/Utils/getFilters.ts
Certain filters that come from PowerBI shouldnt be shown in the filter pane. If such a filter exists, it will have the prefix 'xx'.
=> [PowerBI] - chore: remove hidden filters based on prefix

src/modules/powerBI/src/Components/Filter/FilterItems/FilterItems.tsx, src/modules/powerBI/src/Components/Filter/PowerBIFilter.tsx
When using "Select All" functionality in a filter, only the visible filters will be affected.
Meaning if you have 5 filter items, type something in the search input so only 2 are visible, choose select all, only the 2 visible will be affected. 
=> [PowerBI] - Fix: Only affect visible filter items with select all

src/modules/powerBI/src/PowerBI.tsx
Inside a PowerBI report there may be "chiclet slicers". If one of these are clicked, it will have an impact on the filters that can be applied. We only want to cause this state update when the type of the slicer is "chiclet", so we can prevent unnecessary state updates when other visuals are clicked. 
=> [PowerBI] - fix: update state when chiclet slicers are triggered

src/apps/Handover/Garden/CustomViews/HandoverGardenHeader.tsx, src/apps/Handover/Garden/CustomViews/HandoverGardenItem/GardenItemStyles.ts, src/apps/Handover/Garden/CustomViews/HandoverGardenItem/HandoverGardenItem.tsx
It's a wish to have the handover package item to be 180x28px 
When expanded the width will be 100%.
When multiple group by's it will be a bit smaller than the group by item, not sure yet what is wanted there still WIP.
=> [Handover] - chore: fixed size on handover package and header

src/apps/WorkOrder/Garden/components/WorkOrderItem/WorkOrderItem.tsx, src/apps/WorkOrder/Garden/components/WorkOrderItem/styles.ts, src/components/ParkView/Components/VirtualGarden/Container.tsx, src/components/ParkView/Components/VirtualGarden/GardenItemContainer.tsx, src/components/ParkView/Components/VirtualGarden/VirtualGarden.tsx, src/components/ParkView/Models/gardenOptions.ts
Add itemwidth prop to calculate item width when column is expanded. The description now will appear after the item, and the item will have the same size after expanding column. 
=> [Workorder & Virtual Garden] - feat: expand workorder column with description

src/Core/WorkSpace/src/WorkSpaceApi/workspaceApi.ts
When opening a sidesheet in a Garden, it will rerender and might cause a useLayoutEffect to trigger (scroll to highlighted column).
The code for it in VirtualGarden.tsx : 
```tsx
const highlightedColumn = useMemo(
() =>
highlightColumn ? highlightColumn(gardenKey.toString(), customGroupByKeys) : undefined,
[highlightColumn, gardenKey, customGroupByKeys]
);
useLayoutEffect(() => {
if (highlightedColumn) {
const scrollIndex = sortedColumns.findIndex(
(column) => column.value === highlightedColumn
);
scrollIndex !== -1 && columnVirtualizer.scrollToIndex(scrollIndex, { align: 'center' });
}
}, [sortedColumns, columnVirtualizer.scrollToIndex, highlightedColumn]);
```
Inside app config we can declare customGroupByKeys (e.g. Handover config), or not (e.g. SWCR & Workorder). 
If customGroupByKeys …
=> [Garden & Sidesheet & Workspace] - hotfix: default value of customgroupbykeys 

src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx
fam url from config:
"FAM": "https://fam-api-prod.azurewebsites.net/",
=> [Piping & HT] - fix: remove double slash from api url

src/modules/powerBI/src/Components/Filter/FilterGroup/FilterGroup.tsx, src/modules/powerBI/src/Components/Filter/PowerBIFilter.tsx
Bug: When I set an active filter, the whole filter will rerender and scroll me back to the top.
=> [PowerBI] - fix: sort filtergroups when state is set

src/packages/Table/Components/Table.tsx
Request to blank out all other aggregated fields fields when something is grouped:
=> [Table] - chore: remove aggregated when grouping

package.json, yarn.lock
Vite v2.7.1 to v.2.9.10
A few things: 
* Loads of bug fixes
* [Vite 2.8.0](https://packagephobia.com/result?p=vite%402.8.0) is almost 1/4 of the [2.7.0](https://packagephobia.com/result?p=vite%402.7.0) publish size, and the install size has been reduced by 35%.
* Workers are detected and bundled when using new URL('path', import.meta.url), replacing the need for the ?worker suffix and aligning Vite with standard patterns. Instead of
```ts
import MyWorker from './worker.js?worker'
const worker = new MyWorker()
```
it is now recommended to use
```ts
const worker = new Worker(
new URL('./worker.js', import.meta.url), { type: 'module' }
)
```
* Faster Cold Start
* The envDir now correctly loads .env files in the specified directory only (defaults to root). Previously, it would load files …
=> chore: upgrade vite packages to latest

src/apps/ScopeChangeRequest/hooks/queries/useUnpackRelatedObjects.ts
Hotfix for production
Right now if you edit a scope change it will remove all punch list items
=> [Scope change] Hotfix punch not showing in edit mode

src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlSidesheet.tsx
Will fix this specific scenario Uncaught ReferenceError: Cannot access 'ReleaseControlSidesheet' before initialization
at ReleaseControlApp.tsx:11:16
=> [Portal] Fix reference error hmr vite

src/apps/DisciplineReleaseControl/Functions/statusHelpers.ts, src/apps/Handover/Garden/utility/getKeyFunctions.ts, src/apps/MechanicalCompletion/utils/helpers/getHighlightedColumn.ts, src/apps/swcr/utilities/packages.ts, src/packages/GardenUtils/src/dateUtils.ts
WeekYear yields: DateTime.local(2014, 12, 31).weekYear //=> 2015
year yields: DateTime.local(2017, 5, 25).year //=> 2017
=> [GardenUtils & SWCR & MC & Handover & DRC]- fix: date utils

src/Core/PowerBiViewer/src/Context/PbiContext.tsx, src/Core/PowerBiViewer/src/PowerBiViewer.tsx, src/Core/WorkSpace/src/Components/DataViewerHeader/PowerBIPages/PowerBIPages.tsx, src/Core/WorkSpace/src/Context/BookmarkContext.tsx
Fixes for edge cases with page navigation in power bi together with bookmarks. If you have saved a bookmark within a subpage, the page ID will differ from the external page ID (Page ID that is set in Workspace/PowerBIViewer). If these two differ, we want to use the internal page ID instead of the external one. 
Since the page IDs differ, we need another way to check if the page is active to get the correct styling. We check both page ID and page display name. Page display name for subpages should always be identical to the main page display name.
-   [ ] My code is covered by …
=> [Workspace & PowerBIViewer] - Fix/pbi sidesheet bookmark subpage

src/apps/WorkOrder/Garden/components/WorkOrderSidesheet/hooks/useMaterial.ts, src/apps/WorkOrder/Garden/components/WorkOrderSidesheet/hooks/useMccr.ts
Adding abortsignal to the sidesheet api calls so it cancels if sidesheet is closed/changed.
=> [Workorder] - fix: add abortsignal to api calls

src/components/Menu/Components/MenuItem/MenuItem.tsx
There is a bug if you have multiple apps with similar short names and groups
```ts
const pathname = "/ConstructionAndCommissioning/preservation-analytics"
const pathname2 = "/ConstructionAndCommssioning/preservation"
const shortname = "preservation-analytics";
const shortname2 = "preservation";
console.log("Does it equal?", pathname.includes(shortname2)) // logs true
```
ìncludes` is not good enough for this case, so instead we can use react-router's matchPath function.
Completes: [AB#251814](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/251814)
-   [ ] My code is covered by …
=> [Menu] - fix: match match to find active app

src/components/ParkView/Components/VirtualGarden/VirtualGarden.tsx
Completes: [AB#265764](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/265764)
Completes: [AB#259920](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/259920)
=> [Garden] - hotfix: force a recalc of row count when subgroups are toggled

src/packages/Table/Components/Table.tsx
When grouping a column in Table view, and a user clicks on the grouped rows, a sidesheet will appear and fail. Added an early return if the row the user is trying to click on is a grouped row.
Completes: [AB#263483](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/263483)
=> [Table] - fix: early return on row click if row is grouped

src/packages/Utils/createRefContext.tsx, src/packages/Utils/index.ts
A nice-to-have util. Will create a normal React Context, but using refs to store it so when some data changes, only the subscribers of the data will cause a rerender.
=> [Utils] - feat: react context with refs

src/Core/Notifications/Components/NotificationCard.tsx, src/Core/Notifications/Components/StatusCircle.tsx, src/Core/Notifications/Components/notification.styles.ts
SVG icon resizes when sidesheet gets too small. Adding a div wrapper with fixed size around the SVG.
Completes: AB#273610
=> [Notification] - fix: have a fixed size on svg icon

src/modules/powerBI/src/Components/Filter/ExpandedFilter/FilterItems/Header/Header.tsx, src/modules/powerBI/src/Components/Filter/ExpandedFilter/FilterItems/Styles.tsx, src/modules/powerBI/src/Components/Filter/Styles.tsx
PBI filter will overflow wrongly when adding too many filter groups in "Advanced Filter". 
Virtualizing filter items in each group makes it a bit weird with widths. Replaced flexbox with grid, and removed min-width property. Set a pixel width on the SearchBox component because a filter group's width couldn't dynamically resize when opening the SearchBox.
Completes: AB#253853
=> [PBI] - fix: pbi filter overflowing

src/modules/powerBI/src/Components/Filter/ExpandedFilter/ExpandedFilter.tsx, src/modules/powerBI/src/Components/Filter/ExpandedFilter/FilterItems/FilterItems.tsx, src/modules/powerBI/src/Components/Filter/ExpandedFilter/FilterItems/FilterItemsProvider.tsx, src/modules/powerBI/src/Components/Filter/ExpandedFilter/FilterItems/Header/Header.tsx
Using the hook `useClickOutside` to detect clicks outside of each FilterGroup component. Added some states in a context instead of prop drilling.
Refactored some "handle" functions.
Completes: AB#269856
=> [PowerBI] - fix: close filter search when click outside

src/modules/powerBI/src/Components/Filter/ExpandedFilter/FilterItems/FilterItems.tsx
When clicking outside of filter group, the search component will be closed and the search value will be reset.
=> [PBI] - fix: clear searchvalue when closing searchbox

src/modules/powerBI/src/Components/Filter/ExpandedFilter/FilterItems/Header/Styles.tsx, src/packages/Filter/Components/FilterGroup/FilterGroupStyles.ts
The EDS button styling is too big which causes the onHover to fire when mouse is not actually hovering the button.
Completes: [AB#211490](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211490)
=> [PBI & Filter] - fix:  Button styling width and height too large

src/apps/apps.ts
Fixing typo on "Commissioning", it's just an external link to Fusion app, so shortname can be changed without worrying about Bookmarks saving shortname is the database. 
Completes: [AB#278552](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/278552)
=> [CommissioningProcedure] - fix: typo on commissioning

src/Core/WorkSpace/src/Components/QuickFilter/FilterItemCheckbox.tsx, src/modules/powerBI/src/Components/Filter/PopoverGroup/VirtualList.tsx
Jest complains that VirtualFilterItemCheckbox is undefined:
console.error
Warning: memo: The first argument must be a component. Instead received: undefined
59 | `;
60 |
> 61 | export const FilterItemValue = memo(VirtualFilterItemCheckbox);
|                                    ^
62 |
63 | const Parent = styled.div`
64 |     height: 100%;
Fixing this by wrapping the component with memo from the filter component.
=> [Filter] - fix: export memoed component

src/apps/Loop/components/Sidesheet/sidesheet-styles.ts
When it's overflowing vertically, no scrollbar appears. This PR is a hotfix, should look into a better design for most sidesheets soon :) 
=> [Loop] - hotfix: scroll loop sidesheet

src/apps/ReleaseControl/api/releaseControl/Request/voidReleaseControl.ts
Reason for voiding/revision was added in backend API for both SCR and RC. It requires an empty body, or else the API call will fail.
=> [ReleaseControl] - chore: add empty body for void request

src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/VoidedReasonBanner.tsx, src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts
Adding more info about revision and voiding. Fixed logic for when to show revision vs void banner.
Completes: [AB#293204](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/293204)
=> [SCR] - fix: void reason text and revision reason text

src/apps/DisciplineReleaseControl/Components/Sidesheet/WorkOrderTable.tsx, src/apps/DisciplineReleaseControl/Types/workOrder.ts
Changing sourceIdentity to workOrderUrlId
Completes: [AB#296117](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/296117)
=> [Piping&HT] - chore: new url fields for pipetest/workorders

src/apps/ScopeChangeRequest/api/Search/PCS/searchQuery.ts
SCR-Origin(Query) when searching, it did not take project into account on frontend. This gave backend validation errors for documents part of another project. This fix hardcodes the correct projectId to the SavedSearch - same as done in backend today.
See WI for more information.
Completes: [AB#299261](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/299261)
Task: [AB#300276](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/300276)
=> [SCR] fix: New SavedSearch in PCS with Project for JCA hardcoded

index.html, src/Core/Client/Service/appConfig.ts
Remove ENV from browser title when in production.
Still having ENV in browser title when in dev and test.
Completes: [AB#212302](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/212302)
=> chore: update browser title

src/packages/MarkdownEditor/src/MarkdownViewer/ComponentOverrides.tsx, src/packages/MarkdownEditor/src/MarkdownViewer/MarkdownViewer.tsx
Line height for old SCR in prod are not styled correctly with the MD viewer.
=> [SCR] - fix: styling for markdown viewer

src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
When adding/removing attachments in `Edit mode`, the SCR state will get reset because of the dep array in this use effect. Removing the item from the dep array will cause the state to not update when editing the attachments in edit mode...
Completes: [AB#316915](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/316915)
=> [SCR] - fix: dont update state when editing attachments

src/packages/MarkdownEditor/src/editor.styles.ts
How it is now:
This PR will make it look like:
Completes: [AB#327579](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/327579)
=> [MarkdownEditor] - fix: add more space to new line in editor

src/components/Routes/Routes.tsx
Need to separate query clients for framework setup and applications. Calls to invalidateQueries() causes the portal to reconfigure breaking the entire thing
=> fix: query client invalidation

Changelog.md, package.json, src/packages/Workflow/src/Hooks/Search/useFAMSearch.ts
Replaced old mapping of relatedHTCables with the use of higher order functions.
Completes: equinor/lighthouse-client#1511
-   [X] I have performed a self-review of my own code.
-   [X] I have linked my DevOps task using the AB# tag.
-   [X] My code is easy to read, and comments are added where needed.
=> fix: :bug: Improved mapping of tags in create release-control workflow.

Changelog.md, package.json, src/apps/ReleaseControl/workspaceConfig/filter/filterConfig.ts
Added new filter that filters all RCs where the workflow includes a given step.
Completes: equinor/lighthouse-client#1496
-   [X] I have performed a self-review of my own code.
-   [X] I have linked my DevOps task using the AB# tag.
-   [X] My code is easy to read, and comments are added where needed.
=> feat: Added "Contains Step" filter on RC

Changelog.md, package.json, src/apps/ReleaseControl/components/Form/Inputs/Scope/HtCableTable.tsx, src/apps/ReleaseControl/components/Form/Inputs/Scope/TagTable.tsx
Fixed issue with missing area when adding new tags/HT cables before doing submit.
Combined the location and area properties to combine data from both backend and FAM API.
Completes: equinor/lighthouse-client#1554
-   [X] I have performed a self-review of my own code.
-   [X] I have linked my DevOps task using the AB# tag.
-   [X] My code is easy to read, and comments are added where needed.
=> fix: 🐛 Fixed issue with missing area in tag/HT cable tables before submitting RC

src/components/Routes/FusionAppLoader.tsx, src/components/Routes/Routes.tsx, src/components/TopBar/TopBar.tsx
added a /fusion-apps/* route that allows for loading any fusion app.
Nice for debugging and testing apps before migration work
=> feat: generic load fusion apps in JC

.docker/Dockerfile, .github/actions/pnpm-setup/action.yml, .github/workflows/ci-build.yml, package.json
Add a github action for building. This is done because it builds faster than the azure pipelines. Plan is to deprecate the pipeline integration 
I need to talk to an infra person before removing/changing the old azure pipeline configuration
=> ci: add build action

src/packages/Sidesheet/Components/ResizableSidesheet.tsx
Kinda hacky solution but if you render a different tree for when its minimized the children will lose its internal state. A caching solution was considered but the bug potential is too high
Impact: The code changed is used by all applications in the portal
Fixes: #1592
=> fix: state clears when sidesheet is minimized

src/packages/Workflow/src/Api/FAM/searchPunchListItems.ts, src/packages/Workflow/src/Hooks/Search/useCompletionSearch.ts
FAM's V2 endpoint is not working atm (internal server error). This is a temporary fix that will enable the punch search to work while they resolve the issue
=> fix: release control temporariliy fix punch search by reverting to v1 search

README.md, src/apps/apps.ts
Add JC User Statistics dashboard internal app 
Link to issue: https://github.com/equinor/lighthouse-scope-change-control-api/issues/445
> [!TIP]
> [!CAUTION]
=> feat: add power bi dashboard user statistics

.github/workflows/post-service-message.yml, src/components/Messages/Service/Hooks/useServiceMessage.ts
Radix has a limitation which is you cannot send an empty value using the rx cli. This makes it impossible to clear service messages from a github action. You can still do it in GUI. Added code to treat SM as empty if == ">"
=> fix: Ignore SM if >

src/AppClient.tsx, src/Core/Client/Types/ScopeAndUrls.ts, src/fusion-framework/AppLoader.tsx
Following the release of app management v2 api we need to migrate to the new api 
Code chunking has not been handled at this point, not sure how we should solve this. Before we enable chunking we have to solve this.
TODO: Update env variables in production before merging
Issue:
- #1858
Migration guide supplied by fusion 
- equinor/fusion-rfcs#70
=> Migrate to Fusion app mangement v2 api
