equinor/lighthouse-client

src/apps/ScopeChangeRequest/hooks/queries/useUnpackRelatedObjects.ts

[Scope change] Fix punch-list items not showing in edit mode

---

src/apps/Punch_Dev/index.tsx
src/apps/Punch_Dev/types/punch.ts
src/apps/Punch_Dev/utility/config/gardenConfig.tsx
src/apps/Punch_Dev/utility/config/index.ts
src/apps/Punch_Dev/utility/config/statusBarConfig.tsx
src/apps/Punch_Dev/utility/config/tableConfig.tsx
src/apps/apps.ts

Just for dev env, and performance testing in workspace with 130K objects

[Punch] - feat: punch for dev

---

src/packages/BookmarksManager/src/components/BookmarksSidesheet/AppBookmarks.tsx
src/packages/BookmarksManager/src/components/BookmarksSidesheet/AppGroup.tsx
src/packages/BookmarksManager/src/components/BookmarksSidesheet/BookmarksSidesheet.styles.ts

Completes: [AB#207630](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/207630)

[Bookmarks]- chore: fix styling for bookmarks sidesheet

---

src/apps/Loop/components/Sidesheet/LoopContentTable.tsx
src/apps/Loop/components/Sidesheet/LoopSidesheet.tsx
src/apps/Loop/components/Sidesheet/LoopWorkorderTable.tsx
src/apps/Loop/index.tsx
src/apps/Loop/types/index.ts
src/apps/Loop/types/loop.ts
src/apps/Loop/types/workorder.ts
src/apps/Loop/utility/api/getLoopContent.ts
src/apps/Loop/utility/api/getWorkorders.ts
src/apps/Loop/utility/api/index.ts

[Loop] - feat: workorder tab in sidesheet

---

src/components/TopBar/TopBar.tsx

[Portal] - chore: remove prod check for bookmarks portal

---

src/apps/MechanicalCompletion/index.ts

[Mechanical Completion]-  chore: add commpkg to search

---

src/apps/Punch_Dev/index.tsx
src/apps/Punch_Dev/types/punch.ts
src/apps/Punch_Dev/utility/config/filterConfig.ts
src/apps/Punch_Dev/utility/config/index.ts

[Punch dev] - feat: filter for testing

---

src/apps/MechanicalCompletion/utils/config/tableConfig.tsx
src/packages/ProCoSysUrls/procosysUrl.ts

Procosys baseurl has to be JOHAN_CASTBERG not PCS$Johan_Castberg 

[Mechanical completion] - chore: table config & procosys base url

---

src/Core/WorkSpace/src/Components/DataViewerHeader/ViewSettings/ViewSettings.tsx
src/packages/BookmarksManager/src/components/BookmarkDropdown/BookmarkDropdown.tsx

[Workspace] - fix: give popovers unique ids

---

src/components/Messages/Service/Hooks/useServiceMessage.ts

[Portal] Fix parse service message error

---

src/packages/Table/Components/ColumnPicker/ColumnPicker.tsx
src/packages/Table/Components/ColumnPicker/columnPicker.styles.ts

[Table] Fix column picker styling

---

src/apps/Loop/components/Sidesheet/LoopDetails.tsx
src/apps/Loop/components/Sidesheet/LoopSidesheet.tsx
src/apps/Loop/types/loop.ts
src/apps/Loop/utility/config/tableConfig.tsx
src/packages/GardenUtils/src/components/sidesheet/StringCell.tsx
src/packages/GardenUtils/src/dateUtils.ts

[Loop] - chore: update styling

---

Changelog.md
package.json

[Release] - Changelog 1.6.0

---

Changelog.md
package.json
src/apps/DisciplineReleaseControl/Components/Garden/gardenFunctions.ts

Changelog-1.6.1

---

src/packages/Table/Components/ColumnPicker/ColumnPicker.tsx

[Table] Fix styling column picker

---

src/apps/Loop/utility/config/gardenConfig.ts

[Loop] - feat: highlight current week column

---

src/apps/Loop/components/Sidesheet/LoopSidesheet.tsx
src/apps/Loop/components/Sidesheet/sidesheet-styles.ts

[Loop] - feat: links to procosys in sidesheet

---

src/apps/workPreparation/index.ts

[Work preparation] - chore: change strhupr page name

---

src/apps/Handover/utility/config/tableConfig.tsx

[Handover]- chore: update status cells

---

src/apps/ScopeChangeRequest/Atoms/FormAtomApi/formAtomApi.ts
src/apps/ScopeChangeRequest/Components/Attachments/AttachmentVisual.tsx
src/apps/ScopeChangeRequest/Components/Attachments/RequestAttachmentsList/RequestAttachmentsList.tsx
src/apps/ScopeChangeRequest/Components/Attachments/RevisionAttachments.tsx
src/apps/ScopeChangeRequest/Components/Attachments/Upload.tsx
src/apps/ScopeChangeRequest/Components/Form/EditFormActionBar.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/NotLatestRevisionBanner.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/RevisionForm.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/RevisionSubmitBar.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/ScopeChangeDetailView.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/WarningCreateRevisionBanner.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RequestTab.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RevisionList/RevisionList.tsx
src/apps/ScopeChangeRequest/api/ScopeChange/Request/getRevisions.ts
src/apps/ScopeChangeRequest/api/ScopeChange/Request/initiateScopeChange.ts
src/apps/ScopeChangeRequest/functions/openNewScopeChange.ts
src/apps/ScopeChangeRequest/hooks/mutations/useRequestMutations.ts
src/apps/ScopeChangeRequest/hooks/sidesheet/useSidesheetEffects.tsx
src/apps/ScopeChangeRequest/keys/queries.ts
src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[Scope change] Revisions

---

src/apps/Loop/types/loopContent.ts
src/apps/Loop/utility/api/getLoopContent.ts

[Loop] - fix: remove unused columns from FAM query

---

src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/RevisionForm.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/SidesheetWrapper.styles.ts
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RevisionList/RevisionList.tsx

[Scope change] Revision styling fixes

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[Scope change] Disable WO columns pending FAM integration

---

src/apps/Loop/index.tsx
src/apps/Loop/utility/config/filterConfig.ts

[Loop] - chore: more filters and search

---

src/apps/Loop/index.tsx
src/apps/Loop/utility/config/index.ts
src/apps/Loop/utility/config/statusBarConfig.tsx

[Loop] - feat: loop kpis

---

src/apps/Loop/components/GardenItem/CustomGardenItem.tsx
src/apps/Loop/components/GardenItem/customGardenItem.styles.ts
src/apps/Loop/components/NoStatus.tsx
src/apps/Loop/components/Popover/PopoverContent.tsx
src/apps/Loop/components/Popover/Status.tsx
src/apps/Loop/components/Popover/index.ts
src/apps/Loop/components/Popover/popoverContent.styles.ts
src/apps/Loop/components/index.ts
src/apps/Loop/utility/config/gardenConfig.ts
src/apps/Loop/utility/helpers/getGroupByKey.ts

[Loop] - feat: custom garden

---

Changelog.md
package.json

Changelog 1.6.4

---

src/Core/WorkSpace/src/Components/QuickFilter/quickFilterStyles.ts

[Filter] Fix width quickfilter

---

src/apps/Punch_Dev/index.tsx
src/apps/Punch_Dev/utility/config/analyticsConfig.ts
src/apps/Punch_Dev/utility/config/index.ts

[Punch dev] - feat: analytics view for punch dev

---

src/apps/Punch_Dev/utility/config/statusBarConfig.tsx

[Punch dev] - feat: kpis for punch

---

src/apps/DisciplineReleaseControl/Components/Electro/Components/Cable.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/HeatTracingCable.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/JunctionBox.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/Line.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/TestDot.tsx
src/apps/DisciplineReleaseControl/Components/Electro/styles.ts

Completes: [AB#228394](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/228394)

More compact circuit diagram

---

src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RevisionList/RevisionList.tsx
src/apps/ScopeChangeRequest/hooks/sidesheet/useSidesheetEffects.tsx
src/apps/ScopeChangeRequest/workspaceConfig/filter/filterConfig.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

Completes:
[AB#229280](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/229280)

[Scope change] Revision fixes

---

src/Core/WorkSpace/src/Components/DataViewerHeader/HeaderStyles.ts
src/Core/WorkSpace/src/Components/QuickFilter/FilterQuickSearch.tsx
src/Core/WorkSpace/src/Components/QuickFilter/QuickFilter.tsx
src/Core/WorkSpace/src/Components/QuickFilter/ToggleHideFilterPopover.tsx
src/Core/WorkSpace/src/Components/QuickFilter/quickFilterStyles.ts
src/modules/powerBI/src/Components/Filter/FilterItems/FilterItems.tsx
src/modules/powerBI/src/Components/Filter/Header/Header.tsx
src/packages/Filter/Components/FilterGroup/FilterGroup.tsx
src/packages/Filter/Components/FilterGroup/FilterGroupStyles.ts
src/packages/Filter/Components/FilterView/FilterView.tsx

[Filter] Fix pixels

---

src/apps/Loop/utility/config/gardenConfig.ts
src/apps/Loop/utility/config/statusBarConfig.tsx

[Loop] - fix: loop kpis and smaller cards

---

src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/RevisionForm.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/RevisionSubmitBar.tsx

[Scope change] Fix revisions unsaved changes warning

---

packages/echo3dViewer/src/services/echo3dMultiSelectionHandler.ts
src/apps/Loop/components/Sidesheet/3D/3dView.tsx
src/apps/Loop/components/Sidesheet/LoopContentTable.tsx
src/apps/Loop/components/Sidesheet/LoopSidesheet.tsx
src/apps/Loop/types/loopContent.ts
src/apps/Loop/utility/api/getLoopContent.ts
src/packages/ModelViewer/hooks/useLoadModel.ts

[Loop] - feat: WIP loop 3d

---

src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RevisionList/RevisionList.tsx

[Scope change] Hide latest revision from revisions list

---

src/apps/ScopeChangeRequest/Components/DetailView/References.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RequestTab.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RevisionList/RevisionList.tsx

[Scope change] Padding detail view

---

src/Core/WorkSpace/src/Components/QuickFilter/QuickFilter.tsx

[Filter] Scroll issue expanded filter

---

Changelog.md
package.json

Changelog 164

---

src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RevisionList/RevisionList.tsx

[Scope change] Hide state from revisionslist

---

src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/CriteriaActionBar.tsx

[Scope change] Hide reject with comment on initiate step

---

src/apps/ScopeChangeRequest/Atoms/FormAtomApi/formAtomApi.ts
src/apps/ScopeChangeRequest/Components/AtsScopeCheckbox/AtsCheckbox.tsx
src/apps/ScopeChangeRequest/Components/Form/BaseForm/ScopeChangeBaseForm.tsx
src/apps/ScopeChangeRequest/Components/Form/Inputs/AtsScopeCheckbox.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/RequestTab.tsx
src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts
src/apps/ScopeChangeRequest/workspaceConfig/filter/filterConfig.ts

[Scope change] ATS scope

---

src/apps/Loop/index.tsx

[Loop] - chore: search for loop tag

---

Changelog.md

Changelog 165

---

src/apps/apps.ts

[Loop] - chore: loop to test env

---

src/components/TopBar/HelpMenu.tsx
src/components/TopBar/TopBar.tsx
src/components/TopBar/TopBarAvatar.tsx
src/components/TopBar/TopBarStyle.ts

Top bar changes

---

src/apps/ScopeChangeRequest/Components/SearchReferences/SearchReferences.tsx

[Scope change] Remove famtag from references

---

src/packages/BookmarksManager/src/components/BookmarksSidesheet/BookmarksSidesheet.tsx

[Bookmarks] - fix: move hook call above early return

---

src/apps/Loop/components/Sidesheet/Checklists.tsx
src/apps/Loop/components/Sidesheet/LoopContentTable.tsx
src/apps/Loop/types/loopContent.ts
src/apps/Loop/utility/api/getLoopContent.ts

[Loop] - chore: url in cells

---

Changelog.md
package.json

[Changelog] - Release v1.7.0

---

src/Core/Client/Functions/getUserPresence.ts
src/components/TopBar/TopBarAvatar.tsx

[Avatar] Add default case

---

src/Core/PowerBiViewer/src/PowerBiViewerStyles.ts
src/modules/powerBI/PowerBI.styles.ts

PowerBI height issues

---

src/apps/WorkOrder/utility/tableConfig.tsx

[Workorder] - perf: table cells calcs

---

src/apps/Loop/utility/config/tableConfig.tsx

[Loop] - perf: table cell calc

---

src/apps/Handover/utility/helpers/getFilterDateValues.ts

[Handover] - fix: schedule filter return 2-4 weeks

---

src/Core/WorkSpace/src/Components/QuickFilter/QuickFilter.tsx
src/apps/ScopeChangeRequest/workspaceConfig/filter/filterConfig.ts

[Workspace] Fix filter spawning out of bounds

---

Changelog.md
package.json

[Release] - Changelog v1.7.1

---

Changelog.md
package.json
src/Core/WorkSpace/src/Components/QuickFilter/QuickFilter.tsx
src/apps/Handover/utility/helpers/getFilterDateValues.ts
src/apps/Loop/utility/config/tableConfig.tsx
src/apps/ScopeChangeRequest/workspaceConfig/filter/filterConfig.ts
src/apps/WorkOrder/utility/tableConfig.tsx

Johan Castberg Portal Release v.1.7.1

---

src/apps/Loop/utility/config/sidesheetConfig.ts

[Loop] - fix: sidesheet resolver column names fam

---

src/Core/WorkSpace/src/Components/QuickFilter/FilterGroup/FilterGroupPopoverMenu.tsx
src/modules/powerBI/src/Components/Filter/FilterItems/FilterItems.tsx
src/modules/powerBI/src/Components/Filter/Header/Header.tsx
src/modules/powerBI/src/Components/Filter/PopoverGroup/PopoverGroup.tsx
src/packages/Filter/Components/FilterGroup/FilterGroup.tsx

[Workspace / PowerBI] Filter finishing touches

---

package.json
yarn.lock

Ser det er en del ubrukte dependencies. Kan muligens fjerne alle de i denne PRen

[Dependencies] - chore: remove base64-js dep

---

src/apps/Loop/components/Sidesheet/LoopSidesheet.tsx
src/apps/Loop/components/Sidesheet/sidesheet-styles.ts
src/packages/BookmarksManager/src/components/BookmarksSidesheet/BookmarksSidesheet.styles.ts
src/packages/BookmarksManager/src/components/BookmarksSidesheet/BookmarksSidesheet.tsx
src/packages/GardenUtils/src/components/sidesheet/TabTable.tsx

chore: styling fixes

---

src/apps/apps.ts

[Loop] - chore: change loop env to prod

---

src/Core/WorkSpace/src/Components/DataViewerHeader/ViewSettings/ViewSettings.tsx

[Workspace] Give popover unique ID

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[Scope change] Reduce width disciplines column

---

Changelog.md
package.json

[Release]- chore: changelog 1.7.2

---

src/Core/GlobalSearh/Service/GlobalSearch.ts

[Gloabl Serach ] - fix search loading

---

src/Core/WorkSpace/src/Components/QuickFilter/FilterItemCheckbox.tsx
src/modules/powerBI/src/Components/Filter/FilterItems/Item.tsx
src/packages/Filter/Components/FilterItem/FilterItem.tsx

[Portal] Add tooltip to all filters

---

src/apps/swcr/utilities/filterSetup.tsx

[SWCR] Adjust SWCR filters

---

src/modules/powerBI/src/Components/Filter/FilterGroup/FilterGroup.tsx
src/modules/powerBI/src/Components/Filter/PopoverGroup/PopoverGroup.tsx
src/modules/powerBI/src/PowerBI.tsx

[PowerBI] Close filter popover menu when clicking on report

---

src/apps/Loop/components/Sidesheet/Checklists.tsx

[Loop] - fix: use checklist status instead of content status

---

Changelog.md
package.json

Changelog 1.7.3

---

Changelog.md
package.json
src/Core/GlobalSearh/Components/GlobalSearch.tsx
src/Core/GlobalSearh/Components/GlobalSearchStyles.ts
src/Core/GlobalSearh/Components/SearchResultHeadingStyles.ts
src/Core/GlobalSearh/Components/SearchResultItem.tsx
src/Core/GlobalSearh/Components/SearchResultItemContent.tsx
src/Core/GlobalSearh/Components/SearchResultItemMenu.tsx
src/Core/GlobalSearh/Components/SearchResultItemStyles.ts
src/Core/GlobalSearh/Config/Apps/appsSearchRequest.ts
src/Core/GlobalSearh/Config/ProCoSys/proCoSysSearchMapper.tsx
src/Core/GlobalSearh/Config/ProCoSys/proCoSysSearchRequest.ts
src/Core/GlobalSearh/Config/ProCoSys/utils.ts
src/Core/GlobalSearh/Service/GlobalSearch.ts
src/Core/GlobalSearh/Service/SearchApi.ts
src/Core/WorkSpace/src/Components/QuickFilter/FilterItemCheckbox.tsx
src/apps/Loop/components/Sidesheet/Checklists.tsx
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx
src/apps/Tags/Components/3D/3dView.tsx
src/apps/Tags/Components/TagsDetails.tsx
src/apps/Tags/Components/sidesheet-styles.ts
src/apps/swcr/utilities/filterSetup.tsx
src/components/TopBar/DevBar/DevBar.tsx
src/components/TopBar/DevBar/DevBarStyles.ts
src/components/TopBar/TopBarAvatar.tsx
src/modules/powerBI/src/Components/Filter/FilterGroup/FilterGroup.tsx
src/modules/powerBI/src/Components/Filter/FilterItems/Item.tsx
src/modules/powerBI/src/Components/Filter/PopoverGroup/PopoverGroup.tsx
src/modules/powerBI/src/PowerBI.tsx
src/packages/Filter/Components/FilterItem/FilterItem.tsx

Castberg release 1.7.3

---

src/apps/DisciplineReleaseControl/Functions/statusHelpers.ts

Completes: [AB#228895](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/228895)

Completion status bugfix in p&ht

---

src/apps/ReleaseControl/components/Form/ReleaseControlEditForm.tsx

Completes: [AB#214597](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/214597)

No submit button in edit mode without draft state

---

src/apps/MechanicalCompletion/index.ts

[Mechanical Completion] - fix: remove prod flag

---

src/modules/powerBI/src/Utils/filterSelectionUtils.ts
src/modules/powerBI/src/Utils/transformData.ts

[PowerBI] - fix: check for boolean strings

---

src/apps/MechanicalCompletion/utils/config/tableConfig.tsx
src/packages/Table/Components/Cells/DescriptionCell.tsx

[Mechanical Completion] - chore: prevent auto columns

---

src/apps/MechanicalCompletion/utils/config/tableConfig.tsx

[Mechanical Completion]- fix: cchange accessor on map to be status

---

Changelog.md
package.json
src/apps/DisciplineReleaseControl/Functions/statusHelpers.ts
src/apps/MechanicalCompletion/index.ts
src/apps/MechanicalCompletion/utils/config/tableConfig.tsx
src/apps/ReleaseControl/components/Form/ReleaseControlEditForm.tsx
src/modules/powerBI/src/Utils/filterSelectionUtils.ts
src/modules/powerBI/src/Utils/transformData.ts
src/packages/Table/Components/Cells/DescriptionCell.tsx

Release Castberg Portal v1.7.4

---

src/Core/WorkSpace/src/Tabs/ListTab/ListTab.tsx
src/hooks/index.ts
src/hooks/useResizeObserver.ts

Completes: [AB#231778](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/231778)

[Workspace] - feat: use resize observer to fix table height issue

---

src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTab.tsx
src/apps/ScopeChangeRequest/api/FAM/getWorkOrderById.ts

Completes: [AB#231916](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/231916)

[SCR] - fix: add help text if issue with loading wos

---

Changelog.md
package.json
src/Core/WorkSpace/src/Tabs/ListTab/ListTab.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTab.tsx
src/apps/ScopeChangeRequest/api/FAM/getWorkOrderById.ts
src/hooks/index.ts
src/hooks/useResizeObserver.ts

Release Johan Castberg Portal v1.7.5

---

src/modules/powerBI/src/Components/Filter/PowerBiQuickFilter.tsx

Completes: [AB#232344](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/232344)

[PowerBI] - feat: add chip for hidden applied filters

---

src/apps/ScopeChangeRequest/Components/DataCreator/DataCreatorWrapper.tsx
src/apps/ScopeChangeRequest/Components/Form/FormBanner/FormBanner.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/RevisionForm.tsx

Completes: [AB#224631](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/224631)

Fix for correct state in scope change edit/revision form

---

src/apps/DisciplineReleaseControl/Functions/statusHelpers.ts

Completes: [AB#231226](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/231226)

Fixed pipetest warning triangles showing up when they shouldn't

---

src/apps/DisciplineReleaseControl/Types/disciplineReleaseControl.ts
src/apps/ScopeChangeRequest/Atoms/FormAtomApi/formAtomApi.ts
src/apps/ScopeChangeRequest/Components/DetailView/OriginLink.tsx
src/apps/ScopeChangeRequest/Components/Form/Inputs/OriginSourceSelect/OriginSourceSelect.tsx
src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts

Completes: [AB#219881](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/219881)

NotApplicable -> Not Applicable

---

Changelog.md
package.json

Changelog for version 1.7.6

---

Changelog.md
package.json
src/apps/DisciplineReleaseControl/Functions/statusHelpers.ts
src/apps/DisciplineReleaseControl/Types/disciplineReleaseControl.ts
src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowCustomEditor.tsx
src/apps/ReleaseControl/components/Workflow/Criteria/Components/CriteriaActionBar.tsx
src/apps/ScopeChangeRequest/Atoms/FormAtomApi/formAtomApi.ts
src/apps/ScopeChangeRequest/Components/DataCreator/DataCreatorWrapper.tsx
src/apps/ScopeChangeRequest/Components/DetailView/OriginLink.tsx
src/apps/ScopeChangeRequest/Components/Form/FormBanner/FormBanner.tsx
src/apps/ScopeChangeRequest/Components/Form/Inputs/OriginSourceSelect/OriginSourceSelect.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
src/apps/ScopeChangeRequest/Components/Sidesheet/SidesheetWrapper/RevisionForm.tsx
src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts
src/modules/powerBI/src/Components/Filter/PowerBiQuickFilter.tsx
yarn.lock

Version 1.7.6

---

src/packages/BookmarksManager/src/components/BookmarkDropdown/BookmarkDropdown.tsx

Completes: [AB#233679](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/233679)

Changed bookmark icon in workspace to avoid confusion

---

src/components/Menu/Components/MenuItem/MenuItem.tsx

Completes: [AB#207735](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/207735)

Show icons that are favourited without hovering

---

src/apps/Checklist/index.ts
src/apps/Handover/index.tsx
src/apps/Punch/index.ts
src/apps/swcr/index.ts

Changed pages for Checklist analytics

---

Changelog.md
package.json

Changelog version 1.7.7

---

src/apps/Checklist/index.ts
src/apps/Installation/index.ts

Changes to pageids

---

src/modules/powerBI/src/PowerBI.tsx

[PBI]- fix: set active page in pbi when changing

---

src/modules/powerBI/src/PowerBI.tsx

[PBI] - fix: update report page on sub page

---

src/apps/Loop/components/Sidesheet/Checklists.tsx
src/apps/Loop/components/Sidesheet/LoopSidesheet.tsx
src/apps/Loop/types/checklistForLoop.ts
src/apps/Loop/types/index.ts
src/apps/Loop/utility/api/getChecklistsForLoop.ts

Change to new view from FAM to retrieve checklist for a loop.
Completes: [AB#239888](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/239888)

[Loop] - chore: update endpoint for checklist loop sidesheet

---

src/modules/powerBI/src/Components/Filter/PowerBiQuickFilter.tsx

Completes: [AB#241206](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/241206)

[PBI]- fix: lower z value on eds chip for extra filters

---

.docker/Dockerfile

chore: run test suites in docker

---

Changelog.md
package.json

[Changelog]: v1.8.0

---

Changelog.md
package.json

[Changelog] - v1.8.1

---

src/apps/ReleaseControl/components/Workflow/Criteria/Components/CriteriaActionBar.tsx
src/components/OverlayMenu/src/components/ButtonMenu/MiniButtonMenu.tsx
src/components/OverlayMenu/src/components/ButtonMenu/buttonMenu.styles.ts
src/components/OverlayMenu/src/components/index.ts

Completes: [AB#229858](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/229858)

Split sign button into sign and a dropdown menu

---

src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowStep.tsx

Completes: [AB#229944](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/229944)

Removed duplicate text and reduced space between steps

---

src/apps/ReleaseControl/components/Workflow/Workflow.tsx

Completes: [AB#229860](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/229860)

"..." context menu only for current step

---

src/apps/CommissioningAnalytics/index.ts
src/apps/apps.ts

Completes: [AB#245399](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/245399)

Added commissioning analytics

---

src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/NcrTab.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/PunchTab.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/QueryTab.tsx
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/SwcrTab.tsx

Completes: [AB#243402](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/243402)

[Handover] - fix: remove packages suffix

---

src/apps/ReleaseControl/__tests__/releaseControl.test.ts
src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowCustomEditor.tsx
src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowEditorHelpers.tsx
src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowStep.tsx
src/apps/ReleaseControl/components/Form/WorkflowEditor/workflow.styles.ts
src/apps/ReleaseControl/components/Workflow/ReassignBar/ReassignBar.tsx
src/apps/ScopeChangeRequest/Components/PersonRoleSearch/PCSPersonRoleSearch.tsx

Completes: [AB#232117](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/232117)

Search for and use person in workflow step edit

---

src/apps/ReleaseControl/components/Form/Inputs/Scope/ScopeSelect.tsx
src/apps/ReleaseControl/components/Form/Inputs/Scope/SearchHtCables.tsx
src/apps/ReleaseControl/components/Form/Inputs/Scope/SearchTags.tsx
src/apps/ReleaseControl/components/Form/Inputs/Scope/search.styles.ts
src/apps/ScopeChangeRequest/api/FAM/searchHtCableTagNo.ts
src/apps/ScopeChangeRequest/api/FAM/searchTagNo.ts
src/apps/ScopeChangeRequest/hooks/Search/useFAMSearch.ts
src/apps/ScopeChangeRequest/hooks/Search/useReferencesSearch.ts

Improved tag/htCable search performance by using 2 api calls

---

src/Core/WorkSpace/src/Tabs/ListTab/ListTabPopover.tsx
src/Core/WorkSpace/src/Tabs/ListTab/listTab.styles.ts
src/Core/WorkSpace/src/WorkSpaceApi/workspaceState.ts
src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/excelExport.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx
src/packages/Table/Components/ColumnPicker/ColumnPicker.tsx
src/packages/Table/Components/ColumnPicker/index.ts
src/packages/Table/Components/ExportToExcel/ExportToExcel.tsx
src/packages/Table/Components/ExportToExcel/exportToExcel.styles.ts
src/packages/Table/Components/ExportToExcel/index.ts
src/packages/Table/Components/Table.tsx
src/packages/Table/Types/tableApi.ts
src/packages/Table/Types/types.ts
src/packages/Table/index.ts
src/packages/Utils/downloadToDrive.ts
src/packages/Utils/index.ts

Updated table config to accept excelExport function. Added component for excel export in "Settings" popover for table. Added function for excel export for scope change control.
Completes: [AB#226570](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/226570)

[SCR] - Feat: scope change export to excel

---

src/Core/WorkSpace/src/Components/DataViewerHeader/ViewSettings/ViewSettings.tsx
src/Core/WorkSpace/src/Tabs/ListTab/listTab.styles.ts
src/packages/Table/Components/ColumnPicker/ColumnPicker.tsx

[Table tab] - chore: update settings popover

---

src/apps/ScopeChangeRequest/Atoms/FormAtomApi/formAtomApi.ts
src/apps/ScopeChangeRequest/Components/Form/Inputs/OriginSourceSelect/OriginSourceSelect.tsx

Validation bugfix for NotApplicable

---

src/apps/Preservation/index.ts
src/apps/apps.ts

Completes: [AB#215908](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/215908)

Added Preservation analytics

---

src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/ReleaseControlSidesheetBanner.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/sidesheetStyles.ts
src/apps/ReleaseControl/hooks/index.ts
src/apps/ReleaseControl/hooks/useIsReleaseControlMutatingOrFetching.ts
src/apps/ReleaseControl/queries/queries.ts
src/apps/ReleaseControl/queries/releaseControlMutationKeys.ts

Completes: [AB#245691](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/245691)

Release control loading spinner chip on fetching/mutating

---

Changelog.md
package.json

Changelog version 1.9.0

---

src/apps/Commissioning/index.tsx
src/apps/Construction/Components/CriticalWoTable/CriticalWoTable.tsx
src/apps/DisciplineReleaseControl/Components/Electro/Components/Line.tsx
src/apps/DisciplineReleaseControl/Types/pipetest.ts
src/apps/ReleaseControl/types/releaseControl.ts
src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts
src/apps/swcr/models/SwcrPackage.ts

[Apps] - chore: update to type instead of interface

---

src/Core/Assignments/Types/assignment.ts
src/Core/Client/Service/ClientBuilder.ts
src/Core/Client/Types/App.ts
src/Core/Client/Types/AppConfig.ts
src/Core/Client/Types/AppGroupe.ts
src/Core/Client/Types/AppManifest.ts
src/Core/Client/Types/ClientRegistry.ts
src/Core/Dashboard/Api/dashboardApi.ts
src/Core/Dashboard/Api/dashboardState.ts
src/Core/Dashboard/Components/DashboardView/Dashboard.tsx
src/Core/Dashboard/Components/Header/Header.tsx
src/Core/Dashboard/Components/Pages/Pages.tsx
src/Core/Dashboard/Context/DataProvider.tsx
src/Core/Dashboard/Hooks/useDashboard.ts
src/Core/Dashboard/Types/State.ts
src/Core/PageViewer/Api/pageViewerApi.ts

[Core] - chore/update core types

---

src/apps/ReleaseControl/components/Workflow/Criteria/Components/SignWithComment/SignWithCommentModal.tsx

Completes: [AB#252149](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/252149)

Added keyboard shortcuts and autofocus for signing modal

---

src/packages/Table/Components/ExportToExcel/ExportToExcel.tsx

[Table]- fix: no automatic retries for excel export

---

src/apps/Spools/index.ts
src/apps/apps.ts

Completes: [AB#252674](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/252674)

Added spools analytics

---

src/apps/ReleaseControl/__tests__/releaseControl.test.ts
src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowEditorHelpers.tsx
src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowStep.tsx
src/apps/ReleaseControl/types/releaseControl.ts

Completes: [AB#252312](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/252312)

Fix for workflow step responsible field not working properly

---

Changelog.md
package.json

[Release] - Changelog v.1.10.0

---

package.json
tsconfig.json
vite.config.ts
yarn.lock

Upgrading to Vite 3.0, latest versions of typescript, ts-node and vitejs/plugin-react

chore: Upgrade deps

---

package.json
yarn.lock

chore: upgrade dexie

---

src/apps/WorkOrder/Mock/groupedWorkorder.ts

[Workorder] - fix: change date in mockdata to be today

---

src/apps/DisciplineReleaseControl/utils/api/getEleNetworks.ts

[HT] - fix: remove slash prefix in url

---

src/apps/ReleaseControl/Atoms/formAtomApi.ts
src/apps/ReleaseControl/api/releaseControl/Request/findScopeChangeRequest.ts
src/apps/ReleaseControl/components/Form/Inputs/References/References.tsx
src/apps/ReleaseControl/components/RelatedObjects/ReferencesList.tsx
src/apps/ReleaseControl/components/RelatedObjects/ScopeChangeRequestReferenceItem.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/ReleaseControlDetailView.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/ReleaseControlRequestEditForm.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/ReleaseControlSidesheet.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/Tabs/ScopeTab.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/sidesheetStyles.ts
src/apps/ReleaseControl/hooks/useUnpackReferences.tsx
src/apps/ReleaseControl/types/releaseControl.ts
src/apps/ReleaseControl/workspaceConfig/table/tableConfig.tsx
src/apps/ScopeChangeRequest/hooks/Search/useReferencesSearch.ts

Completes: [AB#232118](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/232118)

Scope change references for RC + sidesheet fix

---

Changelog.md

formatted changelog file

---

src/apps/ScopeChangeRequest/types/scopeChangeRequest.ts
src/apps/ScopeChangeRequest/workspaceConfig/dataOptions.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/Cells/Comments.tsx
src/apps/ScopeChangeRequest/workspaceConfig/sTable/Cells/MakeDateCell.tsx
src/apps/ScopeChangeRequest/workspaceConfig/sTable/Cells/MhrsCells/GuessMhrs.tsx
src/apps/ScopeChangeRequest/workspaceConfig/sTable/Cells/MhrsCells/WOEstMhrs.tsx
src/apps/ScopeChangeRequest/workspaceConfig/sTable/Cells/MhrsCells/WOExpMhrs.tsx
src/apps/ScopeChangeRequest/workspaceConfig/sTable/Cells/MhrsCells/WORemMhrs.tsx
src/apps/ScopeChangeRequest/workspaceConfig/sTable/Cells/MhrsCells/index.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/Cells/PendingContributions.tsx
src/apps/ScopeChangeRequest/workspaceConfig/sTable/Cells/StateCell.tsx
src/apps/ScopeChangeRequest/workspaceConfig/sTable/Cells/cells.styles.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/Cells/index.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[SCR] - Feat/scope change work orders

---

Changelog.md
package.json

[Release] - Changelog v. 1.11.0

---

src/apps/DisciplineReleaseControl/Components/Sidesheet/WorkOrderTable.tsx

Completes: [AB#258221](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/258221)

Filter out duplicate workorders

---

src/apps/DisciplineReleaseControl/Components/Sidesheet/WorkOrderTab.tsx

Completes: [AB#258220](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/258220)

Workorder table sorting (alphabetically)

---

src/apps/DisciplineReleaseControl/Components/Sidesheet/CheckListTable.tsx
src/apps/DisciplineReleaseControl/Types/pipetest.ts
src/apps/DisciplineReleaseControl/utils/helpers/tableHelpers.ts

Completes: [AB#258217](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/258217)

Checklist table sorting

---

.eslintrc.json

So my ESlint won't go crazy on linux

[Eslint]- chore: change eol eslint rule to auto

---

src/modules/powerBI/src/Utils/updateAccessToken.ts

Need to check how dates are treated in dev environment. This works in localhost, but might be some differences in docker container..

[PBI]- chore: temp console logs for dev environment to debug

---

src/apps/DisciplineReleaseControl/utils/config/Table/tableConfig.tsx
src/apps/DisciplineReleaseControl/utils/helpers/tableHelpers.ts
src/apps/ReleaseControl/Styles/WrapperStyles.ts
src/apps/ReleaseControl/components/Form/Inputs/Scope/HtCableTable.tsx
src/apps/ReleaseControl/types/releaseControl.ts
src/apps/ReleaseControl/workspaceConfig/filter/filterConfig.ts
src/apps/ReleaseControl/workspaceConfig/table/tableConfig.tsx
src/apps/ScopeChangeRequest/api/FAM/searchHtCable.ts
src/apps/ScopeChangeRequest/api/FAM/searchTag.ts
src/packages/Table/Utils/columnGenerators.tsx
src/packages/Table/Utils/generateCommaSeperatedStringArrayColumn.ts
src/packages/Table/index.ts

Completes: [AB#245675](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/245675)

New release control fields for table, filters and tags

---

src/modules/powerBI/src/Utils/updateAccessToken.ts

[PBI] - chore: remove console logs

---

Changelog.md
package.json

Changelog init

---

src/apps/ReleaseControl/workspaceConfig/filter/filterConfig.ts

Completes: [AB#259128](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/259128)

System filter bugfix

---

src/packages/ModelViewer/utils/getCurrentContextModel.ts

Completes: [AB#257207](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/257207)

Better 3D-model error message when no access

---

src/apps/ReleaseControl/components/Form/Inputs/Scope/SearchHtCables.tsx
src/apps/ReleaseControl/components/Form/Inputs/Scope/SearchTags.tsx
src/apps/ScopeChangeRequest/api/FAM/searchHtCable.ts
src/apps/ScopeChangeRequest/api/FAM/searchTag.ts
src/apps/ScopeChangeRequest/hooks/Search/useFAMSearch.ts

Completes: [AB#245661](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/245661)

Search and select multiple tags/htCables for scope at the same time

---

Changelog.md
package.json

Changelog version 1.13.0

---

Changelog.md
package.json
src/apps/ReleaseControl/components/Form/Inputs/Scope/SearchHtCables.tsx
src/apps/ReleaseControl/components/Form/Inputs/Scope/SearchTags.tsx
src/apps/ReleaseControl/components/Form/releaseControlProcessForm.styles.ts
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/EditTabs/EditScopeTab.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/EditTabs/EditWorkflowTab.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/Tabs/HistoryTab.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/Tabs/ScopeTab.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/Tabs/WorkflowTab.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/sidesheetStyles.ts
src/apps/ReleaseControl/workspaceConfig/filter/filterConfig.ts
src/apps/ScopeChangeRequest/api/FAM/searchHtCable.ts
src/apps/ScopeChangeRequest/api/FAM/searchTag.ts
src/apps/ScopeChangeRequest/hooks/Search/useFAMSearch.ts
src/packages/CircuitDiagram/src/CircuitDiagram.tsx
src/packages/CircuitDiagram/styles/styles.ts
src/packages/ModelViewer/utils/getCurrentContextModel.ts

Release version 1.13.0

---

Changelog.md
package.json
src/apps/apps.ts

Changelog version 1.14.0

---

Changelog.md
package.json
src/apps/apps.ts

Release version 1.14.0

---

src/apps/DisciplineReleaseControl/utils/config/StatusBar/statusBarConfig.ts

Completes: [AB#218778](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/218778)

Improved status bar KPIs for piping&ht

---

src/apps/ReleaseControl/ReleaseControlApp.tsx

Completes: [AB#261087](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/261087)

Added release control analytics

---

src/apps/DisciplineReleaseControl/Components/Sidesheet/CheckListTable.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/InsulationTable.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlHTSidesheet.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlSidesheet.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlSidesheetBanner.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/SidesheetTabs.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/WorkOrderTab.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/WorkOrderTable.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/sidesheetStyles.ts
src/apps/DisciplineReleaseControl/Components/Sidesheet/workOrderTab.styles.ts
src/apps/DisciplineReleaseControl/Styles/SidesheetWrapper.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/sidesheetStyles.ts

Completes: [AB#260057](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/260057)

Improved P&HT sidesheet css and scrollbars

---

Changelog.md
package.json

Changelog version 1.15.0

---

Changelog.md
package.json
src/apps/DisciplineReleaseControl/Components/Sidesheet/CheckListTable.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/InsulationTable.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlHTSidesheet.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlSidesheet.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/ReleaseControlSidesheetBanner.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/SidesheetTabs.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/WorkOrderTab.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/WorkOrderTable.tsx
src/apps/DisciplineReleaseControl/Components/Sidesheet/sidesheetStyles.ts
src/apps/DisciplineReleaseControl/Components/Sidesheet/workOrderTab.styles.ts
src/apps/DisciplineReleaseControl/Styles/SidesheetWrapper.tsx
src/apps/DisciplineReleaseControl/utils/config/StatusBar/statusBarConfig.ts
src/apps/ReleaseControl/ReleaseControlApp.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/sidesheetStyles.ts
src/apps/ReleaseControl/workspaceConfig/statusBar/statusBarConfig.ts

Release version 1.15.0

---

src/apps/DisciplineReleaseControl/Components/Garden/ReleaseControlGardenItem.tsx
src/apps/DisciplineReleaseControl/utils/config/Garden/gardenConfig.tsx
src/apps/ReleaseControl/components/Garden/GardenItemStyles.ts
src/apps/ReleaseControl/components/Garden/ReleaseControlGardenItem.tsx
src/apps/ReleaseControl/workspaceConfig/garden/gardenConfig.ts

Completes: [AB#217513](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/217513)

Split description from item in RC and P&HT gardens

---

src/apps/ReleaseControl/components/Workflow/Criteria/Components/CriteriaActionBar.tsx

Completes: [AB#263978](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/263978)

Remove reject option from RC workflow

---

src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx

[Piping & HT] - chore: remove prod flag for report

---

Changelog.md
package.json

[Release] - changelog v1.15.1

---

src/apps/apps.ts

Change URL for Quality deviation

---

Changelog.md
package.json

[Release] - Changelog v1.15.2

---

Changelog.md
package.json
src/apps/apps.ts
src/packages/Table/Components/Table.tsx

[Release] - Johan Castberg Portal v1.15.2

---

src/apps/ProgressStatus/index.ts
src/apps/apps.ts

Completes: [AB#269943](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/269943)

Added new report, Progress Status

---

Changelog.md
package.json

[Release] - Changelog v1.15.3

---

Changelog.md
package.json
src/apps/ProgressStatus/index.ts
src/apps/apps.ts

[Release] - Johan Castberg Project Portal v1.15.3

---

src/apps/apps.ts

Progress Status app not ready for prod yet.

[Progress Status] - chore: prod flag on progress status

---

Changelog.md
package.json

[Release] -  Changelog v1.15.4

---

src/apps/ReleaseControl/workspaceConfig/statusBar/statusBarConfig.ts

Completes: [AB#272428](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/272428)

Include state in RC overdue calculation

---

src/apps/DisciplineReleaseControl/Components/3D/3dView.tsx
src/apps/DisciplineReleaseControl/Mock/mockData.ts
src/apps/DisciplineReleaseControl/Types/pipetest.ts
src/apps/DisciplineReleaseControl/utils/config/Filter/filterConfig.tsx
src/apps/DisciplineReleaseControl/utils/config/Table/tableConfig.tsx
src/packages/CircuitDiagram/src/Components/HeatTracingCable.tsx
src/packages/CircuitDiagram/src/Components/Line.tsx
src/packages/CircuitDiagram/src/types/pipetestTypes.ts

Critical line filter + new name and data structure

---

src/apps/ReleaseControl/ReleaseControlApp.tsx

Removing prod flag from RC PBI report
Completes: AB#261087

[ReleaseControl] - chore: remove prod flag from pbi

---

src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx
src/apps/Handover/index.tsx
src/apps/Loop/index.tsx
src/apps/MechanicalCompletion/index.ts
src/apps/ReleaseControl/ReleaseControlApp.tsx
src/apps/WorkOrder/index.tsx
src/apps/swcr/index.ts

Adding description as a search options.
Completes: AB#257282

[Apps]- fix: add description to search options

---

Changelog.md
package.json

[Release] - Changelog v.1.16.0

---

src/components/ParkView/Utils/groupBy.ts

Completes: [AB#276370](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/276370)

Fix for array grouping in hanging garden

---

src/apps/DisciplineReleaseControl/utils/config/Garden/gardenConfig.tsx

Completes: [AB#266420](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/266420)

P&HT garden grouping by circuit

---

src/apps/DisciplineReleaseControl/Mock/mockData.ts
src/apps/DisciplineReleaseControl/Types/pipetest.ts
src/apps/DisciplineReleaseControl/utils/config/Garden/gardenConfig.tsx
src/apps/DisciplineReleaseControl/utils/config/StatusBar/statusBarConfig.ts
src/apps/DisciplineReleaseControl/utils/helpers/gardenFunctions.ts
src/apps/DisciplineReleaseControl/utils/helpers/statusHelpers.ts

Completes: [AB#266419](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/266419)

P&HT current step or ht cable garden group option

---

src/apps/DisciplineReleaseControl/utils/config/Filter/filterConfig.tsx
src/apps/ReleaseControl/types/releaseControl.ts
src/apps/ReleaseControl/workspaceConfig/filter/filterConfig.ts

Completes: [AB#215473](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/215473)

Filters for isolated and disconnected equipment

---

src/apps/DisciplineReleaseControl/DisciplineReleaseControlApp.tsx

Completes: [AB#250637](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/250637)

Search option for ht cable

---

Changelog.md
package.json

Changelog version 1.17.0

---

src/components/ParkView/Context/ParkViewContext.ts
src/components/ParkView/Context/ParkViewProvider.tsx

Completes: [AB#276376](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/276376)

[Garden] - fix: update garden data when its empty array

---

src/packages/Filter/Components/FilterGroup/FilterGroup.tsx

Adding useClickOutside hook to workspace filter. 
Refactoring onKeyPress function outside of JSX return into its own function for readability.

[Filter] - fix: add useclickoutside on workspace filter

---

Changelog.md
package.json

Changelog version 1.18.0

---

Changelog.md
package.json
src/packages/CircuitDiagram/src/CircuitDiagram.tsx

Enable edit isolation button in prod

---

src/apps/WorkOrder/Garden/components/WorkOrderSidesheet/Tabs/3dView.tsx
src/apps/WorkOrder/Garden/components/WorkOrderSidesheet/WorkOrderSidesheet.tsx

Completes: [AB#233996](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/233996)

[Workorder] - feat: add 3d to workorder sidesheet tab

---

src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowCustomEditor.tsx
src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowEditorHelpers.tsx

Completes: [AB#278370](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/278370)

Fix for workflow step drag and drop

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

Completes: [AB#283164](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/283164)

[SCR] - fix: correct spelling mistake of category

---

Changelog.md
package.json

[Release] - chore: changelog v1.19.0

---

Changelog.md
package.json

Changelog version 1.19.1

---

src/apps/ReleaseControl/Atoms/formAtomApi.ts
src/apps/ReleaseControl/components/Form/Inputs/Scope/HtCableTable.tsx
src/apps/ReleaseControl/components/Form/Inputs/Scope/TagTable.tsx
src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowEditorHelpers.tsx
src/apps/ReleaseControl/types/releaseControl.ts
src/apps/ScopeChangeRequest/api/FAM/searchHtCable.ts
src/apps/ScopeChangeRequest/api/FAM/searchTag.ts
src/apps/ScopeChangeRequest/hooks/Search/useFAMSearch.ts

Completes: [AB#275796](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/275796)

Update to use v1 of custom_scope_tag endpoint

---

src/packages/Admin/src/Components/Workspace/WorkflowStatuses.tsx
src/packages/Admin/src/Components/Workspace/WorkflowSteps.tsx
src/packages/Admin/src/Components/Workspace/Workflows.tsx
src/packages/Admin/src/Hooks/useAdminMutation.ts
src/packages/Admin/src/Hooks/useAdminMutations.ts
src/packages/Admin/src/Hooks/useIsAdminMutatingOrFetching.ts
src/packages/Admin/src/Hooks/useIsTemplateLoading.ts
src/packages/Admin/src/Queries/adminQueryKeys.ts
src/packages/Admin/src/Queries/queries.ts

Query refetching and invalidation in admin

---

Changelog.md
package.json

Changelog release version 1.20.0

---

src/apps/apps.ts

[Punch] - chore: change punch to prod env

---

Changelog.md
package.json

[Release] - Changelog v1.21.0

---

Changelog.md
package.json

Changelog 1.22.0

---

src/apps/ScopeChangeRequest/ScopeChangeRequestApp.tsx

Changing search from sequence number to serial number. (Sequence number is the serial number without SCR- prefix).
Completes: [AB#292326](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/292326)

[SCR] - chore: change search from sequence to serial number

---

src/apps/ScopeChangeRequest/workspaceConfig/filter/filterConfig.ts

Completes: [AB#289199](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/289199)

Comm pkg filter in scope change request

---

src/apps/DisciplineReleaseControl/Mock/mockData.ts
src/apps/DisciplineReleaseControl/Types/pipetest.ts
src/apps/DisciplineReleaseControl/utils/config/Garden/gardenConfig.tsx
src/apps/DisciplineReleaseControl/utils/config/Table/tableConfig.tsx
src/apps/DisciplineReleaseControl/utils/helpers/statusHelpers.ts

Completes: [AB#291371](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/291371)

Group option for Current Step (Circuit)

---

Changelog.md
package.json

Changelog version 1.23.0

---

src/apps/ReleaseControl/ReleaseControlApp.tsx

Prod flag workflow admin until permissions are correct

---

src/apps/Punch/components/PunchGardenItem/PunchGardenItem.tsx
src/apps/Punch/components/PunchGardenItem/punchGardenItem.styles.ts
src/apps/Punch/components/PunchGardenItem/utils.ts
src/apps/Punch/components/icons/FlagIcon.tsx
src/apps/Punch/types/punch.ts
src/apps/Punch/utility/config/gardenConfig.tsx
src/apps/Punch/utility/config/tableConfig.tsx

Added flag and category to GardenItem, and RFC and RFO plan to garden groupBy

Flag and category to gardenItem

---

src/apps/apps.ts

Remove old queries app. Use query workspace instead.

[apps] - chore: remove old queries app

---

src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/Request/VoidedReasonBanner.tsx

[SCR] - chore: add some gap between text in revision reason banner

---

Changelog.md
package.json

[Changelog] - Release v.1.24.0

---

src/apps/Query/components/QuerySidesheet/QuerySidesheet.tsx
src/apps/Query/components/QuerySidesheet/Tabs/DetailsTab.tsx

Completes: [AB#297558](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/297558)
Completes: [AB#297561](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/297561)

[Query] - chore: add more fields to query sidesheet

---

src/apps/Punch/components/PunchSidesheet/Tabs/DetailsTab.tsx
src/apps/Punch/index.tsx

Completes: [AB#297562](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/297562)

[Punch] - chore: add description to sidesheet and search

---

Changelog.md
package.json

[Release] - Changelog v.1.24.1

---

Changelog.md
package.json
src/apps/Punch/components/PunchSidesheet/Tabs/DetailsTab.tsx
src/apps/Punch/index.tsx
src/apps/Query/components/QuerySidesheet/QuerySidesheet.tsx
src/apps/Query/components/QuerySidesheet/Tabs/DetailsTab.tsx

[Release] - Castberg Portal v.1.24.1

---

src/packages/ProcosysUrls/src/procosysUrl.ts

[ProcosysUrls] - fix: remove pipe from url

---

Changelog.md
package.json

[Release] - Changelog v1.24.2

---

src/apps/ScopeChangeRequest/Components/AdvancedDocumentSearch/AdvancedDocumentSearch.tsx
src/apps/ScopeChangeRequest/api/PCS/Batch/batchDocuments.ts
src/apps/ScopeChangeRequest/api/Search/STID/searchDocuments.ts
src/apps/ScopeChangeRequest/hooks/Search/useStidSearch.ts
src/apps/ScopeChangeRequest/types/STID/document.ts

Completes: [AB#285452](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/285452)

Document batch search

---

src/apps/Punch/components/PunchSidesheet/Tabs/DetailsTab.tsx
src/apps/Query/components/QuerySidesheet/QuerySidesheet.tsx
src/apps/Query/components/QuerySidesheet/Tabs/CommpkgTab.tsx
src/apps/Query/components/QuerySidesheet/Tabs/DetailsTab.tsx
src/apps/Query/components/QuerySidesheet/Tabs/QuerySignatureTable.tsx
src/apps/Query/types/sidesheetResources.ts
src/apps/Query/utility/api/getQueryCommpkgs.ts

Completes: [AB#215786](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/215786)
Completes: [AB#298098](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/298098)
Completes: [AB#298099](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/298099)

[Query & Punch] - chore: sidesheet fixes

---

Changelog.md
package.json

[Release] - Changelog v.1.24.3

---

src/apps/ScopeChangeRequest/hooks/sidesheet/useSidesheetEffects.tsx

Temporary so people can test this functionality.. Revert this if needed.
Completes: [AB#298454](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/298454)

[SCR] - feat: create revision when its closed

---

src/apps/Punch/types/punch.ts
src/apps/Punch/utility/config/sidesheetConfig.ts
src/apps/Punch/utility/config/tableConfig.tsx

Completes: [AB#296115](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/296115)

[Punch] - chore: punch new url fields

---

src/apps/WorkOrder/Garden/components/WorkOrderSidesheet/Tabs/MccrTab.tsx
src/apps/WorkOrder/Garden/components/WorkOrderSidesheet/WorkOrderSidesheet.tsx
src/apps/WorkOrder/Garden/models/workOrder.ts
src/apps/WorkOrder/Garden/models/workOrderMccr.ts
src/apps/WorkOrder/Mock/groupedWorkorder.ts
src/apps/WorkOrder/index.tsx
src/apps/WorkOrder/utility/tableConfig.tsx

[Workorder] - chore: workorder new url fields

---

src/apps/ScopeChangeRequest/Components/WorkOrderTable/CompactWorkOrder/CompactWorkOrder.tsx
src/apps/ScopeChangeRequest/Components/WorkOrderTable/WorkOrderTable.tsx
src/apps/ScopeChangeRequest/api/FAM/getWorkOrderById.ts
src/apps/ScopeChangeRequest/types/FAM/workOrder.ts

Completes: [AB#296118](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/296118)

[SCR] - chore: new url fields for custom workorder api

---

Changelog.md
package.json

[Release] - Changelog v1.25.0

---

src/apps/MechanicalCompletion/utils/config/statusBarConfig.tsx

Completes: [AB#299116](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/299116)

Fixed MC to Com KPI

---

src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

Completes: [AB#299206](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/299206)

[SCR] - chore: date fields to normal dates

---

Changelog.md
package.json

[Release] - Changelog 1.25.1

---

Changelog.md
package.json
src/apps/MechanicalCompletion/utils/config/statusBarConfig.tsx
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

[Release] - Castberg Portal v1.25.1

---

src/apps/CommissioningPackageTask/index.ts
src/apps/apps.ts

Completes: [AB#262417](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/262417)

Added commissioning task

---

src/apps/ReleaseControl/components/Workflow/Criteria/Components/CriteriaActionBar.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/CriteriaActionBar.tsx

Completes: [AB#298561](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/298561)

Loading spinners while signing steps in SCR and RC

---

Changelog.md
package.json

[Release] - Changelog v.1.26.0

---

src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/NcrTab.tsx

Completes: [AB#211181](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/211181)

[Handover] - fix column width in sidesheet for Tab NCr

---

Changelog.md
package.json

[Release] Changelog 1.26.1

---

Changelog.md
package.json

[Release] - Changelog v1.26.2

---

src/packages/MarkdownEditor/src/editor.styles.ts

Ability to resize vertically and border bottom when not focused.

[MarkdownEditor] - chore: styling improvements

---

Changelog.md
package.json

[Release] - Changelog v.1.26.3

---

package.json
yarn.lock

chore: bump luxon

---

Changelog.md
package.json

[Release] - Changelog 1.26.4

---

Changelog.md
package.json
src/packages/MarkdownEditor/src/editor.styles.ts
yarn.lock

Castberg Portal Release v.1.26.4

---

src/apps/Loop/components/Sidesheet/LoopContentTable.tsx
src/apps/Loop/types/loopContent.ts
src/apps/Loop/utility/api/getLoopContent.ts

Use Checklist status instead of mechanical completion status for loop content 
Completes: [AB#306450](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/306450)

[Loop] - fix: use cl status instead of mc status

---

src/apps/TagsAnalytics/index.ts
src/apps/apps.ts

Completes: [AB#301313](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/301313)

Added Tags analytics

---

README.md

Made a short how-to publish changes in dev to test/prod.

Added section about release deployment in readme

---

src/apps/ScopeChangeRequest/Components/Form/Inputs/DescriptionInput/DescriptionInput.tsx
src/packages/MarkdownEditor/src/editor.styles.ts

Add placeholder text to SCR description and add styling to it.

[SCR & MarkdownEditor] - chore: add placeholder text and style

---

Changelog.md
package.json

[Release] - Changelog v1.26.5

---

Changelog.md
package.json

[Release]- Changelog v1.26.6

---

Changelog.md
package.json
src/apps/ScopeChangeRequest/Components/Form/Inputs/DescriptionInput/DescriptionInput.tsx
src/packages/MarkdownEditor/src/editor.styles.ts

Johan Castberg Portal Release v.1.26.6

---

src/packages/MarkdownEditor/src/MarkdownViewer/ComponentOverrides.tsx
src/packages/MarkdownEditor/src/MarkdownViewer/MarkdownViewer.tsx

[MarkdownEditor]  - fix: font sizes for md viewer

---

Changelog.md
package.json

[Release] - Changelog v1.26.7

---

Changelog.md
package.json
src/packages/MarkdownEditor/src/MarkdownViewer/ComponentOverrides.tsx
src/packages/MarkdownEditor/src/MarkdownViewer/MarkdownViewer.tsx

Johan Castberg Portal Release v.1.26.7

---

src/apps/Query/components/QuerySidesheet/Tabs/DetailsTab.tsx
src/apps/Query/types/query.ts
src/apps/Query/utility/config/sidesheetConfig.ts

Add description to Query
Completes: [AB#297744](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/297744) 
Completes: [AB#298150](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/298150)

add description to Query

---

src/apps/apps.ts

Adding link to operation garden
Completes: [AB#313856](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/313856)

[apps] - feat: add link to operation garden

---

src/apps/apps.ts

Change URL for operation garden.

[apps] - fix: update url for operation garden

---

Changelog.md
package.json

[Release] - Changelog v1.26.8

---

src/packages/Workflow/src/Api/PCS/Batch/batchTag.ts
src/packages/Workflow/src/Components/AdvancedDocumentSearch/AdvancedDocumentSearch.tsx

[Workflow]  - feat: new batch search for tags using saved search

---

Changelog.md
package.json

[Release] - Changelog v1.26.9

---

src/apps/ScopeChangeRequest/workspaceConfig/filter/filterConfig.ts

Add filter "Has contributors"
Completes: [AB#316359](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/316359)

[SCR] feat: add filter Has Contributors

---

Changelog.md
package.json

[Release] - Changelog v1.26.10

---

Changelog.md
package.json
src/apps/ScopeChangeRequest/workspaceConfig/filter/filterConfig.ts

Castberg Portal Release v.1.26.10

---

src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/Criteria.tsx

Show contributors after signing in sidesheet 
Completes: [AB#316362](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/316362)

[SCR] feat: show contributors after signing

---

Changelog.md
package.json

[Release] - Changelog 1.26.11

---

Changelog.md
package.json
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/Criteria.tsx

Castberg Portal Release v.1.26.11

---

src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/Criteria.tsx

fix show contributors also before signing
Completes: [AB#316362](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/316362)

fix: fix show contributors also before signing

---

Changelog.md
package.json

[Release] - Changelog v1.26.12

---

Changelog.md
package.json
src/apps/ScopeChangeRequest/Components/Form/Inputs/ScopeChangeReferences/ScopeChangeReferences.tsx
src/apps/ScopeChangeRequest/Components/Form/ScopeChangeRequestEditForm.tsx
src/apps/ScopeChangeRequest/Components/Workflow/Criteria/Components/Criteria.tsx
src/packages/Workflow/src/Api/Search/PCS/searchTags.ts
src/packages/Workflow/src/Api/Search/searchType.ts
src/packages/Workflow/src/Components/PersonRoleSearch/typedSelectOption.ts

Castberg Portal Release v.1.26.12

---

src/apps/apps.ts

Completes: [AB#301313](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/301313)

[apps] - chore: update tags analytics env to prod

---

Changelog.md
package.json

[Release] - Changelog 1.26.13

---

Changelog.md
package.json
src/apps/apps.ts

Castberg Portal Release v.1.26.13

---

src/apps/ScopeChangeRequest/Components/Form/Inputs/ScopeChangeReferences/ScopeChangeReferences.tsx

Completes: [AB#322043](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/322043)

[SCR] -  fix: don't add voided commpkgs with tag search

---

Changelog.md
package.json

[Release] - Changelog v1.26.14

---

Changelog.md
package.json
src/apps/ScopeChangeRequest/Components/Form/Inputs/ScopeChangeReferences/ScopeChangeReferences.tsx

Castberg Portal Release v.1.26.14

---

src/apps/ScopeChangeRequest/Components/Form/Inputs/ScopeChangeReferences/ScopeChangeReferences.tsx
src/packages/Workflow/src/Api/PCS/getCommPkgsByIds.ts

add comm pkg description to comm pkg from mc pkg referance
Completes: [AB#321703](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/321703)

[SCR] Feat/add comm pkg description to comm pkg from mc pkg referance

---

src/apps/Loop/components/Sidesheet/Checklists.tsx

Completes: [AB#304125](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/304125)

[loop] - chore: rename header

---

src/apps/apps.ts

Completes: [AB#324164](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/324164)

fix: :bug: fix broken dcp link

---

Changelog.md
package.json

[Release] - Changelog v1.26.15

---

Changelog.md
package.json
src/apps/Loop/components/Sidesheet/Checklists.tsx
src/apps/ScopeChangeRequest/Components/Form/Inputs/ScopeChangeReferences/ScopeChangeReferences.tsx
src/apps/apps.ts
src/packages/Workflow/src/Api/PCS/getCommPkgsByIds.ts

Castberg Portal Release v.1.26.15

---

src/apps/Loop/utility/config/filterConfig.ts

Add comm pk filter to loop
Completes: [AB#323985](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/323985)

[Loop] Add commpkg filter to loop

---

src/packages/Workflow/src/Api/PCS/Batch/batchTag.ts

* Removed limit on api in batch search
* Add duplicateObjects to batch search tags so it adds commpkgs automatically
Completes: [AB#326568](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/326568)
Completes: [AB#326547](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/326547)

fix: remove limit in api and add duplicate obj logic

---

Changelog.md
package.json

[Release] - Changelog v1.26.16

---

Changelog.md
package.json
src/apps/Loop/utility/config/filterConfig.ts
src/packages/Workflow/src/Api/PCS/Batch/batchTag.ts

Castberg Portal Release v.1.26.16

---

src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/McPkg/McPkg.tsx
src/packages/Workflow/src/Api/PCS/Batch/batchMcPkg.ts
src/packages/Workflow/src/Api/Search/PCS/searchMcPkg.ts

show metadata for associated commpkg after adding mcpckg
Completes: [AB#327403](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/327403)

feat: show metadata for associated commpkg after adding mcpckg

---

src/packages/MarkdownEditor/src/MarkdownEditor.tsx

add hardbreak to markdown
Completes: [AB#328261](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/328261)

[SCR] fix: add hardbreak to markdown

---

Changelog.md
package.json

[Release] - Changelog v1.26.17

---

Changelog.md
package.json
src/apps/Loop/components/Sidesheet/Checklists.tsx
src/apps/Loop/components/Sidesheet/LoopSidesheet.tsx
src/apps/Loop/types/checklistForLoop.ts
src/apps/Loop/types/loop.ts
src/apps/Loop/utility/api/getChecklistsForLoop.ts
src/apps/ScopeChangeRequest/Components/DetailView/RelatedObjects/McPkg/McPkg.tsx
src/packages/MarkdownEditor/src/MarkdownEditor.tsx
src/packages/Workflow/src/Api/PCS/Batch/batchMcPkg.ts
src/packages/Workflow/src/Api/Search/PCS/searchMcPkg.ts

Castberg Portal Release v1.26.17

---

src/apps/EIT/index.ts
src/apps/apps.ts

feat: :sparkles: Added EIT analytics

---

src/apps/Loop/components/Sidesheet/3D/3dView.tsx
src/apps/Loop/types/loopContent.ts
src/apps/Loop/utility/api/getChecklistsForLoop.ts
src/apps/Loop/utility/api/getLoopContent.ts

fix: :bug: Removed mechanicalcompletionstatus for API call to work

---

Changelog.md
package.json

[Release] - Changelog 1.26.18

---

Changelog.md
package.json
src/apps/EIT/index.ts
src/apps/Loop/components/Sidesheet/3D/3dView.tsx
src/apps/Loop/types/loopContent.ts
src/apps/Loop/utility/api/getChecklistsForLoop.ts
src/apps/Loop/utility/api/getLoopContent.ts
src/apps/apps.ts
src/packages/MarkdownEditor/src/editor.styles.ts

Castberg Portal Release v1.26.18

---

src/apps/apps.ts

chore: :lipstick: Change name from EIT to EIT79

---

src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTab.tsx

Adding missing WOs from FAM (but has been added to a SCR) to the WO table with the title/description of "WORK ORDER NOT FOUND".
Completes: [AB#329827](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/329827)

[SCR] - feat: add not found wos to wo table

---

Changelog.md
package.json

[Release] - Changelog v1.26.19

---

Changelog.md
package.json
src/apps/ScopeChangeRequest/Components/Sidesheet/Tabs/WorkOrders/WorkOrderTab.tsx
src/apps/apps.ts

Castberg Portal Release v1.26.19

---

Changelog.md
package.json

[Release] - Changelog v1.26.20

---

src/apps/Activities/index.ts
src/apps/apps.ts

feat: :sparkles: Added activities app

---

Changelog.md
package.json

[Release] - Changelog v1.26.21

---

Changelog.md
package.json
src/apps/Activities/index.ts
src/apps/ScopeChangeRequest/Components/WorkOrderTable/CompactWorkOrder/CompactWorkOrder.tsx
src/apps/ScopeChangeRequest/Components/WorkOrderTable/WorkOrderTable.tsx
src/apps/apps.ts

Castberg Portal Release v1.26.21

---

Changelog.md
package.json

[Release] - Changelog v1.26.22

---

src/apps/WorkOrder/index.tsx
src/apps/WorkOrder/utility/analyticsConfig.ts

feat: :sparkles: Added workorder analytics

---

src/apps/Loop/components/Sidesheet/3D/3dView.tsx

Completes: [AB#349940](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/349940)

[loop] - fix: cache key for 3d loop content interferring with loop content

---

Changelog.md
package.json

[Release] - Changelog v1.26.3

---

src/apps/DisciplineReleaseControl/utils/config/Table/tableConfig.tsx

[P&HT] - chore: remove mcpkgUrlId from table view

---

src/apps/apps.ts

Completes: [AB#349942](https://dev.azure.com/Equinor/fa63ceea-8883-41e2-8823-a3b54e4be178/_workitems/edit/349942)

[loop] - chore: add help page to loop

---

src/apps/WorkOrder/Garden/components/WorkOrderSidesheet/hooks/useMaterial.ts
src/apps/WorkOrder/Garden/components/WorkOrderSidesheet/hooks/useMccr.ts
src/apps/WorkOrder/Garden/models/workOrder.ts
src/apps/WorkOrder/Mock/groupedWorkorder.ts
src/apps/WorkOrder/index.tsx
src/apps/WorkOrder/utility/sidesheetConfig.ts
src/apps/functions.ts
src/apps/widgets.ts

[Workorder] - chore: update fam wo endpoints to v1

---

src/apps/DisciplineReleaseControl/Api/getWorkOrdersById.ts
src/apps/DisciplineReleaseControl/Types/workOrder.ts

[Piping&HT] - chore: update fam endpoints

---

src/packages/Workflow/src/Api/FAM/Batch/getBatchPunch.ts
src/packages/Workflow/src/Api/FAM/getPunchListItemByNo.ts
src/packages/Workflow/src/Api/FAM/getWorkOrderById.ts
src/packages/Workflow/src/Api/FAM/searchHtCableTagNo.ts
src/packages/Workflow/src/Api/FAM/searchPunchListItems.ts
src/packages/Workflow/src/Api/FAM/searchTagNo.ts

[workflow] - chore: update fam endpoints

---

src/apps/Query/index.ts
src/apps/Query/utility/api/getQueryCommpkgs.ts
src/apps/Query/utility/api/getQuerySignatureData.ts
src/apps/Query/utility/config/sidesheetConfig.ts

[query] - chore: update fam endpoints

---

src/apps/Loop/index.tsx
src/apps/Loop/utility/api/getChecklistsForLoop.ts
src/apps/Loop/utility/api/getLoopContent.ts
src/apps/Loop/utility/api/getWorkorders.ts
src/apps/Loop/utility/config/sidesheetConfig.ts

feat: update loop endpoints to v1

---

src/apps/Punch/index.tsx
src/apps/Punch/utility/config/sidesheetConfig.ts
src/packages/Workflow/src/Api/FAM/searchHtCable.ts
src/packages/Workflow/src/Api/FAM/searchTag.ts

[punch] - chore: update fam endpoints for punch

---

Changelog.md
package.json

chore: :bookmark: release Lighthouse@1.27.0

---

Changelog.md
package.json
src/packages/Workflow/src/Api/FAM/searchHtCable.ts
src/packages/Workflow/src/Api/FAM/searchTag.ts

Release@1.27.1

---

src/Core/WorkSpace/src/Components/QuickFilter/QuickFilter.tsx
src/apps/Handover/utility/config/filterSetup.ts

chore(handover):add phase,priority1 to quickfilter

---

Changelog.md
package.json

release 1.27.2

---

Changelog.md
package.json
src/Core/WorkSpace/src/Components/QuickFilter/QuickFilter.tsx
src/apps/Handover/utility/config/filterSetup.ts
src/apps/Loop/components/Sidesheet/LoopContentTable.tsx
src/components/Menu/Components/CompactMenu/CompactMenu.tsx

Castberg Portal Release v.1.27.2

---

src/packages/Workflow/src/Api/FAM/searchTag.ts

chanded view version to v1 to enable tag selection in release control.

fix: enable tag selection in release control

---

src/apps/apps.ts

chore: set allowance only to test

---

src/packages/Workflow/src/Api/FAM/searchHtCable.ts

update search ht cable enbpoint to view v1

fix: search ht cable

---

Changelog.md
package.json
src/apps/Allowance/index.ts
src/apps/apps.ts
src/packages/Workflow/src/Api/FAM/searchHtCable.ts
src/packages/Workflow/src/Api/FAM/searchTag.ts

Release@1.28.0

---

src/apps/apps.ts

feat: :sparkles: change test to prod

---

Changelog.md
package.json

chore: :memo: update changelog and bump version

---

Changelog.md
package.json
src/apps/apps.ts
src/packages/Workflow/src/Api/FAM/searchHtCable.ts

Publish version 1.30.0

---

src/apps/ReleaseControl/workspaceConfig/filter/filterConfig.ts

feat: default filter for state uncheck voided

---

src/apps/WorkOrder/Garden/models/workOrder.ts
src/apps/WorkOrder/utility/filterConfig.tsx
src/apps/WorkOrder/utility/tableConfig.tsx

This reverts commit 91e64bb49cd820f5adf7fc3e62e63468f4a0db78.

Revert "Add WBS to model"

---

Changelog.md
package.json

chore: update chglog bump version

---

Changelog.md
package.json
src/apps/WorkOrder/index.tsx

Also included changelog and version update.

chore: [workorder] change to api v1

---

src/Core/WorkSpace/src/WorkSpaceApi/WorkSpaceTypes.ts
src/Core/WorkSpace/src/WorkSpaceApi/workspaceApi.ts
src/apps/ReleaseControl/ReleaseControlApp.tsx
src/apps/ReleaseControl/components/Admin/adminConfig.tsx
src/packages/Workflow/src/Api/Access/checkIfReleaseControlAdmin.ts
src/packages/Workflow/src/index.ts

Calls the /options API and verifies if the user has POST auth.
A joint effort from @Jossilainen, @ken-mellem and @Noggling 🥳

feature(release-control): enable access control for release control workflow template admin 

---

Changelog.md
package.json
src/Core/Client/Home/PbiHome/PbiHome.tsx
src/Core/Client/Home/clientHome.tsx
src/Core/Client/Home/clientHomeStyles.ts

bugfix 🐛  Responsive landing page 1920x1080p (#1399)

---

src/packages/GardenUtils/src/components/sidesheet/SidesheetHeaderContent.tsx
src/packages/Sidesheet/Components/ResizableSidesheet.tsx

fix: :bug: Add ellipsis and make procosys button to stay to right of header

---

Changelog.md
package.json

chore: :memo: update changelog and vesion in package.json

---

src/apps/WorkOrder/Garden/utility/gardenSetup.ts
src/apps/WorkOrder/utility/filterConfig.tsx

feat: :sparkles: add priority 1, 2, 3

---

src/apps/ScopeChangeRequest/workspaceConfig/filter/filterConfig.ts
src/apps/ScopeChangeRequest/workspaceConfig/sTable/tableConfig.tsx

feat(scopechange): add phase as filter and column

---

Changelog.md
package.json

chore: :bookmark: release@1.36.0

---

src/Core/Client/Home/PbiHome/PbiHome.tsx
src/apps/DisciplineReleaseControl/__tests__/gardenFunctions.test.ts
src/apps/DisciplineReleaseControl/__tests__/pipetestStatusHelpers.test.ts
src/apps/DisciplineReleaseControl/__tests__/tableHelpers.test.ts
src/apps/Handover/__tests__/sidesheetStatuses.test.ts
src/packages/CircuitDiagram/src/__tests__/circuitDiagramHelpers.test.ts

fix: :bug: token not refreshing powerbi

---

public/client-config.json
src/Core/Client/Home/PbiHome/PbiHome.tsx
src/apps/DisciplineReleaseControl/__tests__/gardenFunctions.test.ts
src/apps/DisciplineReleaseControl/__tests__/pipetestStatusHelpers.test.ts
src/apps/DisciplineReleaseControl/__tests__/tableHelpers.test.ts
src/apps/Handover/Garden/components/HandoverSidesheet/HandoverSidesheetTabs/NcrTab.tsx
src/apps/Handover/__tests__/sidesheetStatuses.test.ts
src/apps/WorkOrder/index.tsx
src/packages/CircuitDiagram/src/__tests__/circuitDiagramHelpers.test.ts
yarn.lock

Castberg release

---

src/packages/BookmarksManager/src/components/BookmarksSidesheet/BookmarkEntry.tsx
src/packages/BookmarksManager/src/components/BookmarksSidesheet/MenuOptions.tsx
src/packages/Components/Icon/ClickableIcon.tsx

feat: copy bookmark url

---

Changelog.md
package.json
src/apps/Punch/utility/config/filterConfig.tsx
src/apps/Punch/utility/config/tableConfig.tsx
src/packages/BookmarksManager/src/components/BookmarksSidesheet/BookmarkEntry.tsx
src/packages/BookmarksManager/src/components/BookmarksSidesheet/MenuOptions.tsx
src/packages/Components/Icon/ClickableIcon.tsx

Dev into main

---

Changelog.md
package.json

chore:release@1.37.1

---

Changelog.md
package.json
src/modules/powerBI/src/Components/Filter/ExpandedFilter/FilterItems/FilterItems.tsx
src/modules/powerBI/src/Components/Filter/FilterGroup/FilterGroup.tsx
src/modules/powerBI/src/Types/powerBiFilter.ts

fix: :bug: powerbi filters breaking in production

---

Changelog.md
package.json
src/modules/powerBI/src/Components/Filter/ExpandedFilter/FilterItems/FilterItems.tsx
src/modules/powerBI/src/Components/Filter/FilterGroup/FilterGroup.tsx
src/modules/powerBI/src/Types/powerBiFilter.ts

* fix: :bug: powerbi filters breaking in production

Release Castberg@1.37.2

---

Changelog.md
package.json
src/packages/Sidesheet/Components/ResizableSidesheet.tsx

fix: :bug: fix sidesheet header overflow:hidden

---

Changelog.md
package.json
src/packages/Sidesheet/Components/ResizableSidesheet.tsx

fix: :bug: fix sidesheet header overflow:hidden (#1427)

---

src/AppClient.tsx

fix: :bug: fix loading to use suspense

---

src/AppClient.tsx
src/packages/BookmarksManager/src/components/BookmarksSidesheet/BookmarksSidesheet.tsx
src/packages/BookmarksManager/src/components/BookmarksSidesheet/MenuOptions.tsx
src/packages/BookmarksManager/src/utils/api/unfavouriteBookmark.ts

Will prevent the application suspending the application or content if the setup queries were to rerun

fix: small cache fix

---

src/apps/ReleaseControl/components/Form/ReleaseControlProcessForm.tsx
src/apps/ReleaseControl/hooks/useReleaseControlMutation.ts
src/apps/ReleaseControl/hooks/useReleaseControlMutationWatcher.ts
src/apps/ReleaseControl/hooks/useWorkflowSigning.ts
src/apps/ScopeChangeRequest/hooks/mutations/useRequestMutations.ts
src/components/Routes/Routes.tsx

* fix: invalidation rc
* fix: :bug: fix scope change invalidation

fix: RC query invalidation (#1453)

---

Changelog.md
package.json
src/apps/ScopeChangeRequest/workspaceConfig/filter/filterConfig.ts

feat: :sparkles: SCR: change default selection for the state filter

---

Changelog.md
package.json
src/Core/WorkSpace/src/Components/DataViewerHeader/Header.tsx
src/components/TopBar/HelpMenu.tsx
src/components/TopBar/TopBar.tsx
src/hooks/useContactPerson.ts

Easily reach out to the Fusion Digital Coach with this new feature

feat: add help person

---

Changelog.md
package.json
src/apps/ReleaseControl/types/releaseControl.ts
src/apps/ReleaseControl/workspaceConfig/dataOptions.ts
src/apps/ReleaseControl/workspaceConfig/filter/filterConfig.ts
src/apps/ReleaseControl/workspaceConfig/table/tableConfig.tsx

feat: :sparkles: add "Time on step" column and filter

---

Changelog.md
package.json
src/apps/ReleaseControl/workspaceConfig/filter/filterConfig.ts

feat: :sparkles: add more options to Time on step filter

---

Changelog.md
package.json
src/fusion-framework/AppLoaderWrapper.tsx
src/packages/BookmarksManager/src/hooks/useBookmarks.ts

fix: bookmark bugs

---

Changelog.md
package.json
pnpm-lock.yaml

fix: :bug: fix bookmark refreshing the page

---

Changelog.md
package.json
src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowCustomEditor.tsx
src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowStep.tsx
src/packages/Workflow/src/Components/Workflow/WorkflowEditor.tsx

feat: :sparkles: change selection of workflowsteps when create a RC

---

Changelog.md
package.json
src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowCustomEditor.tsx
src/packages/Admin/src/Components/Workspace/WorkflowSteps.tsx
src/packages/Admin/src/Queries/queries.ts
src/packages/Workflow/src/Api/getWorkflowSteps.ts

fix: :bug: fix change selection of workflowsteps when create a RC

---

src/apps/ReleaseControl/components/Workflow/Criteria/Components/CriteriaActionBar.tsx
src/apps/ReleaseControl/components/Workflow/Workflow.tsx
src/fusion-framework/config.ts

feat: allow contributors on all step

---

src/apps/ReleaseControl/components/Form/Inputs/Scope/SearchHtCables.tsx
src/apps/ReleaseControl/components/Form/Inputs/Scope/SearchTags.tsx

feat: dedupe tag selection

---

Changelog.md
package.json
src/apps/ReleaseControl/components/Workflow/Criteria/Components/Criteria.tsx
src/apps/ReleaseControl/components/Workflow/Criteria/Components/CriteriaDetail.tsx

feat: show functional role signed

---

src/apps/ReleaseControl/components/Workflow/Criteria/Components/Criteria.tsx

feat: show contributors on finished steps

---

Changelog.md
package.json
src/apps/apps.ts
src/fusion-framework/config.ts

add job analytics

---

Changelog.md
package.json
src/packages/BookmarksManager/src/components/BookmarksSidesheet/AppBookmarks.tsx
src/packages/BookmarksManager/src/components/BookmarksSidesheet/BookmarkEntry.tsx

fix: broken bookmarks jca-job-analytics

---

Changelog.md
package.json
src/packages/BookmarksManager/src/components/BookmarksSidesheet/MenuOptions.tsx

fix: job analytics copy url

---

Changelog.md
package.json
src/apps/Loop/utility/api/getChecklistsForLoop.ts
src/apps/Punch/index.tsx
src/apps/Punch/utility/config/sidesheetConfig.ts

Updates FAM queries for views that have been preprocessed and updated.
Completes: equinor/lighthouse#499
-   [X] I have performed a self-review of my own code.
-   [X] I have linked my DevOps task using the AB# tag.
-   [X] My code is easy to read, and comments are added where needed.

fix: FAM preprocessed views update

---

Changelog.md
package.json
src/apps/ReleaseControl/components/Form/Inputs/Scope/SearchTags.tsx

fix: :bug: scopetag table was not showing in edit mode

---

Changelog.md
package.json
src/apps/ReleaseControl/components/Form/Inputs/Scope/CreateRcTagTable.tsx

refactor: :lipstick: add and reorder columns in CreateRcTagTable

---

Changelog.md
package.json
src/index.tsx

fix: :bug: Icon bug

---

Changelog.md
package.json
src/apps/ReleaseControl/workspaceConfig/statusBar/statusBarConfig.ts

fix: :bug: KPI "% closed" shows NaN

---

Changelog.md
package.json
src/Core/WorkSpace/src/Components/QuickFilter/QuickFilter.tsx

fix: :bug: quickfilter infochip overlaps advanced search in createRC

---

Changelog.md
package.json
src/apps/ReleaseControl/hooks/useSidesheetEffects.tsx

fix: :bug: voiding wrong RC

---

Changelog.md
package.json
src/Core/WorkSpace/src/Context/LocationProvider.tsx

Fixes Breadcrumb navigation issue within all apps.
Completes: equinor/lighthouse-client#1663

🐛 : Navigating via Breadcrumbs in apps doesnt work

---

Changelog.md
package.json
pnpm-lock.yaml
src/apps/ReleaseControl/workspaceConfig/filter/filterConfig.ts

Aggregates all roles/persons that are assigned a criteria in a workflowstep

feat: :sparkles: add new filter "Contains Person"

---

Changelog.md
package.json
src/apps/ReleaseControl/components/Form/Inputs/Description/Description.tsx

feat: :sparkles: change default description in create RC sidesheet

---

src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/ReleaseControlSidesheetBanner.tsx
src/apps/ReleaseControl/workspaceConfig/dataOptions.ts

Update RC sidesheet banner so it shows relevant data

feat: :sparkles: update rc sidesheet banner

---

src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/ReleaseControlSidesheetBanner.tsx
src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/Tabs/ScopeTab.tsx

Move due date to banner and change name to "Target date"

feat: :sparkles: Move due date to banner and change name

---

src/packages/CircuitDiagram/src/CircuitDiagram.tsx

Remove "Edit isolation" button in circuit diagram in rc

feat: :sparkles: Remove "Edit isolation" button in circuit diagram in rc

---

src/apps/ReleaseControl/workspaceConfig/filter/filterConfig.ts

add default unchecked "closed" in filter

feat: :sparkles: add default unchecked "closed" in filter

---

src/apps/ReleaseControl/components/Form/Inputs/Scope/HtCableTable.tsx

feat: :sparkles: adjust column width in htCableTable

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/bump-deps.md
.github/ISSUE_TEMPLATE/enh_report.md
.github/ISSUE_TEMPLATE/feat_report.md
.github/ISSUE_TEMPLATE/scaling_report.md
.prettierrc

chore: Add github issue template

---

src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/ReleaseControlSidesheetBanner.tsx
src/apps/ReleaseControl/types/releaseControl.ts

fix: :ambulance: fix RC sidesheet banner bug

---

.github/ISSUE_TEMPLATE/scaling_report.md

chore: Update issue template 2

---

README.md

⛔ I understand by merging my pr the changes will be deployed to production immediately ⛔

docs: :memo: which apps has read only and which has write back

---

.github/pull_request_template.md

Update PR template
Link to issue: https://github.com/equinor/lighthouse/issues/536
> [!TIP]
> [!CAUTION]

chore: Update the PR template

---

src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowStep.tsx

Fix reordering of workflow steps not working

fix: reorder workflow steps

---

src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowStep.tsx

Add Divider component from EDS to WorkflowStep
Link to issue: Doesn't exist :(
> [!TIP]
> [!CAUTION]

feat: :sparkles: Add Divider to WorkflowStep

---

src/apps/ReleaseControl/components/Form/WorkflowEditor/WorkflowStep.tsx

Fix undraggable steps bug.
The solution was to add the divider to the first row in the grid (undraggable steps)
Link to issue: No issue
> [!TIP]
> [!CAUTION]

fix: :bug: Fix undraggableSteps

---

src/apps/ReleaseControl/components/sidesheet/ReleaseControlSidesheet/ReleaseControlSidesheetBanner.tsx

Fix curr. step in RC sidesheet banner
Link to issue: doesn't exist
> [!TIP]
> [!CAUTION]

fix: :bug: fix curr. step in RC sidesheet banner

---

src/packages/Workflow/src/Hooks/Search/useCompletionSearch.ts

Fam v2 dynamic endpoint is now fixed

fix: release control punch search revert back to v2

---

Dockerfile

Remove Dynatrace logging
Link to issue: https://github.com/equinor/lighthouse-scope-change-control-api/issues/445
> [!TIP]
> [!CAUTION]

chore: remove dynatrace

---

src/fusion-framework/config.ts

We are getting a lot of exceptions in application insights from the frontend code. After reviewing these exceptions it was determined they are out of our control. I added two more exception types in the filter to avoid spamming AI logs for exceptions which we will not be fixing.

try ignore some ai exceptions

---

.github/actions/pnpm-setup/action.yml
Dockerfile
radixconfig.yaml

Enables buildkit for deployments in radix. Will fix a temporary issue with deployments in radix as of 02.08.2024. Will also speed up deployments

feat: enable buildkit radix
